### ISSUE TITLE
API V1 Config

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#1018]
Kleinere offene Punkte, welche noch angepasst werden sollten:
- [ ] [Rename some methods](https://github.com/ecamp/ecamp3/pull/827#issuecomment-784582427)
- [ ] [Use lowercase method name](https://github.com/ecamp/ecamp3/pull/827#discussion_r583221527)
- [ ] [Move logic to build method](https://github.com/ecamp/ecamp3/pull/827#discussion_r583222139)
- [ ] [Rename some methods](https://github.com/ecamp/ecamp3/pull/827#discussion_r583223816)

**Comment by carlobeltrame** [comment]
Obsoleted by the move to API Platform
