### ISSUE TITLE
vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer not writable, please chmod to 777

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#1153]
https://sentry.io/organizations/ecamp/issues/2013897768/?project=5353935&query=is%3Aunresolved

Why do we write anything with HTMLPurifier?
Why do we try to write into that directory?
Goal: This Exception does not occur anymore

**Comment by carlobeltrame** [comment]
This library needs a cache directory, and by default apparently uses a subdirectory of the package installation directory. This [can be configured](https://github.com/ezyang/htmlpurifier/issues/71#issuecomment-173651202) though, a temp directory or a subdirectory in `backend/data` would probably be better.
