### ISSUE TITLE
DB index on TEXT column without key length

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#1195]
The backend of dev.ecamp3.ch can not start at the moment, because Doctrine throws an exception while migrating the database:
```
SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'username' used in key specification without a key length
```

Probably caused by #1169

**Comment by BacLuc** [comment]
Jup, mariadb erlaubt das, mysql nicht.
@see https://gist.github.com/BacLuc/0ffb97c8d32b1190b649a955134d0625

Sorry, in diesem Fall wohl revert, weil: https://ideas.digitalocean.com/ideas/DBAAS-I-40
Und ein Pluspunkt für z.b Postgres

**Comment by pmattmann** [comment]
Ich würde nicht gleich alles reverten... nur die User.Username-Spalte.
Dort reicht wohl eine endliche Anzahl Zeichen - zB. 128.
Das wäre wohl ausreichend.

**Comment by BacLuc** [comment]
Man muss es leider für alle Spalten mit Index (meistens unique Index) machen.
Ich reverte für die spalten mit unique index darauf.

**Comment by carlobeltrame** [comment]
Revert oder nur die unique Spalten zu varchar machen + dokumentieren? Migration später ist zwar schwierig wenn wir mal eine spalte neu unique machen wollen, aber das ist so oder so nicht trivial.
