### ISSUE TITLE
Welche ID-Generation-Strategy soll verwendet werden

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#1196]
https://github.com/ecamp/ecamp3/pull/1187#pullrequestreview-628170490

**Comment by carlobeltrame** [comment]
UUID und Auto Increment sind keine Option für uns. In Laravel wird für Tokens auch `random_bytes` verwendet. Daher lassen wir es für den Moment so.
In Zukunft ist es je nach Bedarf möglich, einen anderen Generator für IDs und für Tokens zu verwenden.

**Comment by carlobeltrame** [comment]
Nachtrag: Ich habe noch [`Laminas\Math\Rand`](https://docs.laminas.dev/laminas-math/rand/) gefunden, was Methoden anbietet, um zufällige Werte zu generieren. Langfristig können wir unseren [`IdGenerator`](https://github.com/ecamp/ecamp3/blob/devel/backend/module/eCampLib/src/Util/IdGenerator.php) also damit wieder ablösen, oder intern im `IdGenerator` einfach `Rand` verwenden. So müssen wir uns nicht darum kümmern, falls z.B. in zukünftigen PHP-Versionen noch bessere Zufallsmechanismen eingeführt werden.
