### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#1264]
- Usability
  - Testing mit heavy eCamp User
    - Was haben wir (nicht) vergessen?
    - Was wäre einen Quickwin?
  - Testing mit noob eCamp User muss Lager erstellen
    - Ist die Struktur logisch?
    - Fehlbedienungen / "falsche" mentale Modelle
- Help on site
  - Tutorial overlay?
  - Helptext / What is what?
  - FAQ (==> Landingpage)
- Mobile
  - was will man auf mobile? (usecase ist anders als desktop)
  - Konzept, was sind wir überhaupt
  - Navigation vereinfachen
    - Meine Lager
    - Roter Faden
    - Program
    - Material
    - Lager / Profil
- Autosaving Design
  -  #3513

**Comment by BacLuc** [comment]
Seems to be ok now.
Closing this.
