### ISSUE TITLE
Berechtigungen / Administration / Vorlagen

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#1265]
Admin-Interface für die Verwaltung von Vorlagen, Debugging von User-Problemen, etc.

## UseCases MVP
- Google Analytics oder alternative

- Sentry

- DB Sanity-Check
  - Periode-Dauer & anzahl Tage passt

- Server Monitoring
  - Response-Time
  - Query-Dauer
  - Transaction-Dauer
  - Benötigte Dienste überwachen
    - Browserless.io
  

- Neue Camp-Vorlage erfassen
  - Besser als "Lager erstellen & in DB Prototype-Flag setzen"
- Camp-Vorlage bearbeiten
  - Heute via CampCollaboration möglich (siehe User admin/test)
- Camp-Vorlage inaktiv / löschen

- Zugang auf DB
  - PG Admin 4?
  - API Platform React Admin?
  - Zugang beschränken

- Benutzer zum Admin machen
  - via DB möglich

- Camp Support
  - CampCollaboration  mit Support-Rolle?
    (Per Berechtigung schützen; Admin)
  - So auch für PBS nutzbar

- Berechtigungen
  - Wer darf was - ganze Seite
  - Welche Rollen braucht es?
  - Beispiel
    - Admin: Vorlagen & Support
    - Support: nur Support
    - Anwender

## UseCases Post-MVP
- Neuen Content-Type erstellen
  - DB-Strukturen per Migration
  - Stammdaten per Migration
- Content-Type inaktiv

- Backup pro Lager?

- User / Benutzer-Daten löschen

- Wartungs-Fenster Anzeige

- Wartungs-Fenster Ankündigung

**Comment by BacLuc** [comment]
Most of this is implemented.
I will close this for now.
