### ISSUE TITLE
Letzte Periode nicht löschbar

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#1278]
# Periode
- [x] Letzte Periode soll nicht löschbar sein
- [x] Fehlermeldung an Benutzer anzeigen

**Comment by carlobeltrame** [comment]
Fixed in #1297 and #1308

**Comment by usu** [comment]
> Fixed in #1297 and #1308

#1297 was in the old backend. Is this really implemented in the new API? I cannot find a test for this in https://github.com/ecamp/ecamp3/blob/devel/api/tests/Api/Periods/DeletePeriodTest.php

**Comment by carlobeltrame** [comment]
Ah oops, true. I have now added this to #1579 where I plan to start on implementing all the validations soon, but if you want we can also reopen this issue
