### ISSUE TITLE
Profile-Entpoint with User as Reference

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#1334]
Just a small glitch I found:
Wenn der Name im Profil geändert wird, dann synchronisiert dass hier mit dem Avatar und displayName nicht direkt mit. Änderung passiert auf dem Profile-Endpunkt, gelesen wird aber vom auth().user().

Gleicher Effekt übrigens im Avatar welches im Lager angezeigt wird.

Bin nicht sicher, ob das vor den letzten Änderungen schon so war oder erst jetzt am Schluss hinein gekommen ist.

Lösungsvorschlag: user reloaden, wenn Profil aktualisiert wurde? Oder user Object auf dem `/profile` endpoint embedded einbinden. Dann hätten wir eventuell auch das Problem mit Public-data/nonpublic-data gelöst. Alle öffentlichen Daten liegen im User-Objekt und im Profile liegt nur das private. Und wir haben keine rendundaten Daten client-seitig --> displayName liegt dann immer auf User-Object.

Z.B. sowas:
```javascript
{
    "language": "de",
    "isAdmin": false,
    "_embedded": {
        "user": {
            "id": "ad76048b2007",
            "username": "test-user",
            "displayName": "Smiley",
            "mail": "test@ecamp3.dev",
            "relation": "me",
            "role": "user",
            "_links": {
                "self": {
                    "href": "http://localhost:3001/api/users/ad76048b2007"
                }
            }
        }
    },
    "_links": {
        "self": {
            "href": "http://localhost:3001/api/profile"
        }
    }
}
```

_Originally posted by @usu in https://github.com/ecamp/ecamp3/pull/1313#discussion_r623580073_

**Comment by usu** [comment]
Also related to this discussion: #685
