### ISSUE TITLE
Tests for PostQueryParamsInjectLIistener

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#1372]
Sieht gut aus so. Trotzdem würde ich diesen Mechanismus noch ausgiebig testen, z.B. dass der POST body Vorrang hat, und was passiert wenn eine oder beide der Parameter-Quellen eine oder verschiedene Validierungen triggern. Von mir aus kannst du dafür aber auch ein Issue erstellen und das hier mal mergen, vielleicht mach ichs dann sogar selber irgendwann.

_Originally posted by @carlobeltrame in https://github.com/ecamp/ecamp3/pull/1274#discussion_r628198405_

**Comment by carlobeltrame** [comment]
Obsoleted by the move to API platform
