### ISSUE TITLE
Update node/npm (node v16, npm v7, package-lock.json v2

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#1390]
For some updates we maybe need npm v7
#1387
And the update of nodev16 was anyway proposed by renovate:
#1361
And maybe there is an elegant solution for #1391 with the workspaces of package-lock.json v2

Do we want to update to 
npm v7?
package-lock.json v2
node v16?

**Comment by BacLuc** [comment]
Analyse update:

node: Kein Problem.

npm v7: Kein Problem bis auf lock version 2
Es könnte sein, dass das herunterladen von npm packages weniger stabil ist.
Beim Builden mit github actions ist mir folgender Fehler 2 mal mit unterschiedlichen packages passiert.
npm ERR! request to https://registry.npmjs.org/object-visit/-/object-visit-1.0.1.tgz failed, reason: Socket timeout
Npm hat kein Problem gemeldet.
https://github.com/ecamp/ecamp3/runs/2796647205?check_suite_focus=true

lock version 2:
Bound to npm v7, somit kommen wir nicht darum herum.
v.a. Performance improvements nach doku, andere struktur, Links dazu:
https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json
https://nitayneeman.com/posts/catching-up-with-package-lockfile-changes-in-npm-v7/

**Comment by BacLuc** [comment]
Es gibt doch noch bisschen Probleme:
Nach npm ci haben wir in den node_modules im ci (die wir cachen) noch alte dependencies.

Einerseits haben wir bei npm build einen FATAL:
 FATAL 

Vue packages version mismatch:

- vue@2.6.12
- vue-server-renderer@2.6.14

Obwohl im package-lock.json beide Versionen auf 2.6.12 gelockt sind.

Weiter haben wir noch eine WARN Message:
 npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
 
 Obwohl chockidar auf 3.5.1 gelockt ist.
 
 Das npm ci macht nicht das, was ich will

**Comment by carlobeltrame** [comment]
Hm, das Problem tritt aber nur beim Print Service auf oder? Wir haben ja glaube ich das dependency caching so eingestellt dass es ignoriert wird, sobald sich etwas am package-lock.json ändert. Könnte es sein dass wir dabei bisher nur das package-lock.json des Frontends berücksichtigen?

Habs gleich nachgeschaut: Wir hashen `**/package-lock.json` um zu entscheiden, ob sich etwas geändert hat, also sollte es eigentlich korrekt funktionieren...

Vielleicht ist irgendwo sonst noch ein npm install versteckt? In einem entrypoint irgendwo?
