### ISSUE TITLE
Team verwalten: Rollen

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#1415]
Spezifikation: 
# Rollen
- [x] Gast wählbar; readonly
  - Lese-Recht
  - Mit Materialliste
  - Kann Zuteilungen haben 
- [x] Member
  -  Lese-Recht
      - Admin
      - Team
  - Schreiben
      - Material
      - Story
      - Picasso / Inhalte
- [x] Manager
  - Schreiben alles

Todo:

- [x] Gast hinzufügbar machen #1416

Programm:
v-calendar ist nicht wirklich für einen readonly mode ausgelegt.
- Guest #2376
  - [x] Aktivität erstellen disablen
  - [x] + Knopf unten rechts ausblenden
  - [x]  edit icon auf ScheduleEntry ausblenden
  - [x] Resize von ScheduleEntry disablen
  - [x] Verschieben von ScheduleEntry disablen
  - [x] Aktivität kann man anklicken -> aktivität Detail ansicht

Aktivität Detail ansicht #1416
- Guest
  - [x] Layout bearbeiten Knopf ausblenden
  - [x] Klick auf Category -> Category Edit ausblenden
  - [x] Wenn man auf den Activity Namen klickt wird dieser editierbar -> deaktivieren
  - [x] Location Text disablen
  - [ ] ~~ScheduleEntry Hinzufügen/löschen etc ausblenden~~ Does not seem to be implemented in the near future
  - [x] Responsible DropDown disablen
  - [x] ContentNodes: Icon ändern disablen
  - [x] ContentNodes: Menu entfernen
  - [x] ContentNodes: Textareas disablen

Story #1416
- Guest
  - [x] Editierbar Knopf disablen

Team
- Guest/Member
  - [x] Dropdown für Rolle disablen
  - [x] Deactivate Knopf entfernen (ausser bei eigenen)
  - [x] Resend Email Knopf entfernen
  - [x] Invite Area entfernen
  - [x] Delete Knopf entfernen
- Manager
  - [x] Wenn nur noch ein Manager im Team: Dropdown für Manager disablen, deactivate Knopf disablen, beides mit Tooltip: "Es muss mindestens ein Manager im Lager verbleiben"

Materials
- Guest
  - [x]  Felder in Materiallist disablen (Auch Menu für löschen)
  - [x] Hinzufügen row entfernen

Print
- Nothing to do

Admin
- Guest/Member
  - [x] Textfelder disablen
  - [x] Periods editieren disablen (add knopf weg, edit + menu weg
  - [x] Danger Zone nicht anzeigen #1382
  - [x] Activity Categories: add weg, Edit Knopf bei der Category weg, Edit Layout weg, Delete weg
  - [x] Material-list: create/edit/delete weg

Further improvements:

- Make UX for disabled Links better:
Remove hover on disabled links -> e-href component
Remove hover on disabled buttons -> e-button

**Comment by carlobeltrame** [comment]
@BacLuc ist der Teil Guest wirklich noch offen oder hast du das inzwischen umgesetzt?

**Comment by BacLuc** [comment]
> @BacLuc ist der Teil Guest wirklich noch offen oder hast du das inzwischen umgesetzt?

Leider nein. Das Programm muss man noch read only machen, und in der Aktivitäts Ansicht das hinzufügen von ScheduleEntries für Guests disablen. (Wenn es dann implementiert wird).

**Comment by BacLuc** [comment]
I will close this issue.
When modifying ScheduleEntries on the Activity View is implemented, the ACL have to be implemented correctly.
