### ISSUE TITLE
Doctrine Annotationen durch PHP 8 Attribute ersetzen

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#1921]
Seit 2.9 [unterstützt](https://www.doctrine-project.org/2021/05/24/orm2.9.html) Doctrine PHP 8 Attribute.

**Comment by usu** [comment]
Doctrine 2.11 ist released: https://www.doctrine-project.org/2022/01/11/orm-2.11.html

Wobei es ausschaut, als ob sie nun `Index` und `JoinColumn` doch nicht nesten wollen sondern als Top-Level Attribute sein lassen.

Nach Merge von #2370 evt. nochmals einen Versuch Wert mit rector.

**Comment by BacLuc** [comment]
Closed with #2585 ?
