### ISSUE TITLE
Production build broken 2021-09-26

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#1962]
Since 0bbecd5, the production build is broken with the Error "z is not a function".
Z refers to HalJsonVuex in https://github.com/ecamp/ecamp3/blob/0bbecd519f64fd5ec6575b60b8839ae0b542047f/frontend/src/plugins/store/index.js.

Currently @BacLuc and @carlobeltrame  followed 3 possible solutions:

1. Fix hal-json-vuex: did not work yet: https://github.com/ecamp/hal-json-vuex/commit/4a07f1dec0e7e6547ecc26b787f5ac653d61736a
2. Add hack to the index.js to support both import variants: #1960 (This worked)
3. Downgrade vite: #1961 (This worked)

Which Path should we follow?

Further improvements to detect such fails earlier:

- [ ] Test the production build in the ci

**Comment by carlobeltrame** [comment]
I would suggest option 2 for quickly fixing the problem, and then work on option 1 as a long-term solution

**Comment by BacLuc** [comment]
> I would suggest option 2 for quickly fixing the problem, and then work on option 1 as a long-term solution

If you would like to fix the production build with your chosen variant, you can approve the corresponding PR (Except solution 1)

**Comment by BacLuc** [comment]
Machen wir hier einen Issue in hal-json-vuex und schliessen den Issue hier?

**Comment by carlobeltrame** [comment]
Ja, an den Rückbau von #1960 werden wir dann ja automatisch erinnert wenn sich hal-json-vuex im Verhalten ändert.
