### ISSUE TITLE
GraphQL Security (needs API platform 2.7)

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#2032]
Refs #1906 

Einerseits gibts noch Bugs in API Platform, die in 2.7 gelöst sein werden (bei einem Query der eine nested Collection abfragt wird fälschlicherweise die `item_query` Security-Rule auf der Collection aufgerufen).

Andererseits braucht die GraphQL Security noch fundamentale [Verbesserungen](https://github.com/api-platform/core/pull/4143), die ebenfalls erst mit 2.7 kommen. Security Rules werden für GraphQL nicht nur auf Operationen, sondern auf allen Assoziationen nötig sein. Z.B. muss auf der Assoziation CampCollaboration#user auch die Security Rule für User stehen, sonst kann man mit einem GraphQL Query die Assoziation traversieren. Solche Assoziations-Security wird mit dem verlinkten Verbesserungs-PR in 2.7 erst möglich. Siehe auch die Vorschau der Dokumentation [hier](https://github.com/api-platform/docs/pull/1338/files).

**Comment by BacLuc** [comment]
We don't use GraphQL now, will be important again if we want to use GraphQL.
