### ISSUE TITLE
Decide how to handle dev oauth client secrets

### ISSUE THREAD

**Issue by simfeld** [ecamp/ecamp3#2034]
https://github.com/ecamp/ecamp3/pull/2030#discussion_r720867241

Should we check in dev oauth client secrets into our repository? If not, how do we onboard new contributors?

**Comment by pmattmann** [comment]
check in erlaubt - für dev

**Comment by carlobeltrame** [comment]
Mit "dev" meinen wir hier den lokalen Entwicklungssetup. Alle Deployments (auch dev.ecamp3.ch) sollten dafür aber Secrets verwenden.
