### ISSUE TITLE
API Platform Migration: Frontend CampProgram

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#2060]
- [x] No ScheduleEntries of an Activies are shown (camp.scheduleEntries is not a function) #2062
- [x] It's not possible to create an Activity -> @BacLuc da bin ich dran, hab es schon fast
    ("Extra attributes are not allowed (\"scheduleEntries\", \"categoryId\" are unknown)."
    #2213
- [x] Error in v-on handler: "ReferenceError: TouchEvent is not defined" [sentry](https://sentry.io/organizations/ecamp/issues/2729170836/)
    Hat wahrscheinlich damit zu tun: https://github.com/vuetifyjs/vuetify/issues/14276, ist gefixt mit vuetify 2.5.13, und bei uns schon drin: https://github.com/ecamp/ecamp3/pull/2201
- [x] Error in VCalendar: color.match is not a function. fixed in https://github.com/ecamp/ecamp3/pull/2267

**Comment by carlobeltrame** [comment]
Siehe auch #2062, möglicherweise habe ich dort schon ein Problem gelöst das dich auch betreffen könnte

**Comment by carlobeltrame** [comment]
Hier ist alles erledigt oder?
