### ISSUE TITLE
Redis server not found - php_redis.dll installed

### ISSUE THREAD

**Issue by ghost** [ecamp/ecamp3#209]
D:\xampp\htdocs\ecamp3-devel\ecamp3-devel\vendor\kamisama\php-resque-ex\lib\Redisent\Redisent.php:61
Message:
10061 - Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte.
Stack trace:
#0 D:\xampp\htdocs\ecamp3-devel\ecamp3-devel\vendor\kamisama\php-resque-ex\lib\Redisent\Redisent.php(55): Redisent->establishConnection()
#1 D:\xampp\htdocs\ecamp3-devel\ecamp3-devel\vendor\kamisama\php-resque-ex\lib\Resque.php(96): Redisent->__construct('localhost', '6379')
#2 D:\xampp\htdocs\ecamp3-devel\ecamp3-devel\vendor\kamisama\php-resque-ex\lib\Resque.php(114): Resque::redis()
#3 D:\xampp\htdocs\ecamp3-devel\ecamp3-devel\vendor\kamisama\php-resque-ex\lib\Resque\Job.php(77): Resque::push('bootstrapped', Array)
#4 D:\xampp\htdocs\ecamp3-devel\ecamp3-devel\vendor\kamisama\php-resque-ex\lib\Resque.php(160): Resque_Job::create('bootstrapped', 'EcampCore\Job\S...', Array, false)
#5 D:\xampp\htdocs\ecamp3-devel\ecamp3-devel\module\EcampLib\src\EcampLib\Job\AbstractJobBase.php(21): Resque::enqueue('bootstrapped', 'EcampCore\Job\S...', Array)
#6 D:\xampp\htdocs\ecamp3-devel\ecamp3-devel\module\EcampCore\src\EcampCore\Job\SendActivationMailJob.php(25): EcampLib\Job\AbstractJobBase->enqueue()
#7 D:\xampp\htdocs\ecamp3-devel\ecamp3-devel\module\EcampCore\src\EcampCore\Service\RegisterService.php(65): EcampCore\Job\SendActivationMailJob::Create(Object(EcampCore\Entity\User))
#8 [internal function]: EcampCore\Service\RegisterService->Register(Object(Zend\Stdlib\Parameters))
#9 D:\xampp\htdocs\ecamp3-devel\ecamp3-devel\module\EcampLib\src\EcampLib\Service\ServiceWrapper.php(26): call_user_func_array(Array, Array)
#10 D:\xampp\htdocs\ecamp3-devel\ecamp3-devel\module\EcampWeb\src\EcampWeb\Controller\Auth\RegisterController.php(37): EcampLib\Service\ServiceWrapper->__call('Register', Array)
#11 D:\xampp\htdocs\ecamp3-devel\ecamp3-devel\module\EcampWeb\src\EcampWeb\Controller\Auth\RegisterController.php(37): EcampLib\Service\ServiceWrapper->Register(Object(Zend\Stdlib\Parameters))
#12 D:\xampp\htdocs\ecamp3-devel\ecamp3-devel\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractActionController.php(83): EcampWeb\Controller\Auth\RegisterController->registerAction()
#13 D:\xampp\htdocs\ecamp3-devel\ecamp3-devel\module\EcampWeb\src\EcampWeb\Controller\BaseController.php(53): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#14 [internal function]: EcampWeb\Controller\BaseController->onDispatch(Object(Zend\Mvc\MvcEvent))
#15 D:\xampp\htdocs\ecamp3-devel\ecamp3-devel\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#16 D:\xampp\htdocs\ecamp3-devel\ecamp3-devel\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#17 D:\xampp\htdocs\ecamp3-devel\ecamp3-devel\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractController.php(116): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#18 D:\xampp\htdocs\ecamp3-devel\ecamp3-devel\vendor\zendframework\zendframework\library\Zend\Mvc\DispatchListener.php(113): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#19 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#20 D:\xampp\htdocs\ecamp3-devel\ecamp3-devel\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#21 D:\xampp\htdocs\ecamp3-devel\ecamp3-devel\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#22 D:\xampp\htdocs\ecamp3-devel\ecamp3-devel\vendor\zendframework\zendframework\library\Zend\Mvc\Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#23 D:\xampp\htdocs\ecamp3-devel\ecamp3-devel\public\index.php(16): Zend\Mvc\Application->run()
#24 {main}

**Comment by carlobeltrame** [comment]
This issue is obsolete since Redis is not part of the project any more at this time. If we re-add redis and problems arise, open a new issue.

**Comment by feigenmann** [comment]
Geil also kei redis meh;)



Von meinem Samsung Galaxy Smartphone gesendet.


-------- Ursprüngliche Nachricht --------
Von: Carlo Beltrame <notifications@github.com>
Datum: 25.06.18 10:46 (GMT+01:00)
An: ecamp/ecamp3 <ecamp3@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [ecamp/ecamp3] Redis server not found - php_redis.dll installed (#209)


This issue is obsolete since Redis is not part of the project any more at this time. If we re-add redis and problems arise, open a new issue.
