### ISSUE TITLE
camnp type and owner menu not displayed

### ISSUE THREAD

**Issue by ghost** [ecamp/ecamp3#210]
I am not able to create a camp, i remeber that we had to manually fix this with @pmattmann , but i cant remeber how.

Would be nice to know how so that i can add it to the setup documentiation which i am trying to write..

![image](https://cloud.githubusercontent.com/assets/10007669/8801342/27581dce-2fba-11e5-9cf6-353abe5a784b.png)

**Comment by carlobeltrame** [comment]
Wohl nicht mehr relevant nach 5 Jahren.
