### ISSUE TITLE
GET: normalization_context für collections vs items

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#2148]
Momentan ist der normalization_context für GET bei collections nicht definiert.
Wollen wir:

1. ~~Immer den gleichen Context haben für Item und Collection GET. (z.b. Bei User kann man das einzelne Item dann gar nicht fetchen)~~ Wollen wir nicht
2. ~~Von Fall zu Fall optimieren, damit man nicht für eine kleine Liste gleich den ganzen Objektbaum bekommt.
Bedingt aber auch, dass man je nach dem im Frontend wissen muss, dass man z.b. nur über die Item GET an gewisse Daten heran kommt.~~ Macht das Frontend unnötig kompliziert
3. Das Problem entsteht v.a. mit der User Entitiy. Wollen wir dort einfach die Permissions öffnen. (z.b. man darf alle User sehen, mit denen man in einem Camp ist)
    - Mit Profile Endpoint der die privaten Benutzerdaten exposed
    - User exposed nur Daten, die öffentlich sind

_Originally posted by @BacLuc in https://github.com/ecamp/ecamp3/pull/2121#discussion_r735159806_

**Comment by pmattmann** [comment]
1. Item & Collection Normalization_Context dürfen verschieden sein.


## Aktuell vorgesehen:

https://api.ecamp3.ch/users/{id}
https://api.ecamp3.ch/profiles/{id}

https://api.ecamp3.ch/users/{id}
```
{
  "id": "ad76048b2007",
  "displayName": "Smiley"
  "_links": {
      "self": {
          "href": "http://localhost:3001/api/users/ad76048b2007"
      },
      "profile": {
          "href": "http://localhost:3001/api/profiles/ad76048b2007"
      }
  }
}
```

https://api.ecamp3.ch/profiles/{id}
```
{
  "id": "ad76048b2007",
  "username": "test-user",
  "mail": "test@ecamp3.dev",
  "mobile": "079 000 00 00",
  "_links": {
      "self": {
          "href": "http://localhost:3001/api/profiles/ad76048b2007"
      }
      "user": {
          "href": "http://localhost:3001/api/users/ad76048b2007"
      }
  }
}
```



## Möglicher Alternative:

https://api.ecamp3.ch/users/{id}
https://api.ecamp3.ch/friends/{id}
https://api.ecamp3.ch/profiles/{id}


https://api.ecamp3.ch/public-users/{id}
```
{
  "id": "ad76048b2007",
  "displayName": "Smiley"
  "_links": {
      "self": {
          "href": "http://localhost:3001/api/public-users/ad76048b2007"
      },
      "protectedData": {
          "href": "http://localhost:3001/api/private-users/ad76048b2112"
      }
      "privateData": {
          "href": "http://localhost:3001/api/profile/ad76048b2345"
      }
  }
}
```

https://api.ecamp3.ch/private-users/{id}
```
{
  "id": "ad76048b2112",
  "username": "test-user",
  "mail": "test@ecamp3.dev",
  "mobile": "079 456 23 21",
  "_links": {
      "public-user": {
          "href": "http://localhost:3001/api/public-users/ad76048b2007"
      },
      "self": {
          "href": "http://localhost:3001/api/private-users/ad76048b2112"
      }
      "profile": {
          "href": "http://localhost:3001/api/profile/ad76048b2345"
      }
  }
}
```

https://api.ecamp3.ch/profiles/{id}
```
{
  "id": "ad76048b2345",
  "role": "user",
  "language": "en",
  "_links": {
      "public-user": {
          "href": "http://localhost:3001/api/public-users/ad76048b2007"
      },
      "private-user": {
          "href": "http://localhost:3001/api/private-users/ad76048b2112"
      }
      "self": {
          "href": "http://localhost:3001/api/profile/ad76048b2345"
      }
  }
}
```

**Comment by manuelmeister** [comment]
Wer hat da jetzt Zugriff auf was?

**Comment by carlobeltrame** [comment]
Auf `/users` darf jeder eingeloggte Benutzer zugreifen, für zukünftige Suchfunktion nach neuen Collaborators. Daher sind auch nur die minimal nötigen Daten `id` und `displayName` dort drin.
Von dort kommt man dann via `_link` zu den Profildaten, welche nur Personen abrufen dürfen die mit diesem User in mindestens einem Camp sind (nur aktive Collaborations zählen, Invitations nicht).
Wenn das gut funktioniert können wir dann in Zukunft noch einen dritten Endpoint / zweiten `_link` anbieten, der Daten enthält die nur ich über mich selber sehen darf (z.B. Sprache würden wir dann dorthin verschieben).

Wir haben noch überlegt ob das overengineered ist und ob es nicht einfacher wäre, im Payload beim `/users/{id}` Endpoint abhängig von den Zugriffsrechten Felder ein- oder auszublenden. API Platform bietet so was an, aber es ist unklar wie gut sich das dann in Swagger, GraphQL und hal-json-vuex integriert. Daher probieren wir für den Moment mal, wie gut es sich mit diesen mehreren Endpoints anfühlt.

**Comment by BacLuc** [comment]
Weitere Fragen:
Wo kommen die Patch, Delete, Post, Activate Operationen hin?
Beim User machen sie dann nicht wirklich sinn...

Vorschlag: es wandert alles auf den /profile endpoint, bis auf GET /users{/id} und GET /users. (Wobei GET /users braucht es eigentlich auch nicht)

**Comment by carlobeltrame** [comment]
GET /users brauchts für ein zukünftiges Such-Feature, man kann dann ja die Collection via Query-Parameter filtern.

**Comment by carlobeltrame** [comment]
Wurde in #2241 umgesetzt
