### ISSUE TITLE
Multiple deployments

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#2283]
We need to decide how to handle multiple deployments. At the moment we want at least dev.ecamp3.ch and test.ecamp3.ch running at the same time, but if we can enable feature branch deployments now, that would be even better.

The problem why we can't run multiple instances in the same droplet yet is that we have an nginx reverse proxy for each instance which needs to listen on port 80 of the droplet. Cloudflare doesn't support forwarding traffic to arbitrary ports, so that won't change. So we have two options:
* run a separate droplet for each deployment. This is easier to implement, but does not scale for feature branch deployments...
* run another shared nginx reverse proxy that looks at the requested subdomain and forwards the traffic to the nginx of the relevant deployment. E.g. requests to api-dev.ecamp3.ch get forwarded to the nginx listening on port 1000, requests to api-test.ecamp3.ch get forwarded to the nginx listening on port 1001, requests to api-2193.ecamp3.ch get forwarded to the nginx listening on port 2193. Or any other scheme we come up with.

**Comment by manuelmeister** [comment]
## Core Meeting Decision

- @carlobeltrame versucht sich an Kubernetes

**Comment by usu** [comment]
Just a few links I came across:

API platform seems to be configured out of the box to deploy to Google Cloud via Kubernetes+Helm:
https://api-platform.com/docs/deployment/kubernetes/

The API platform demo app contains an example for GitHub Deploy workflow:
https://github.com/api-platform/demo/blob/main/.github/workflows/cd.yml

The workflow seems to be prepared for Branch + PR deployment. Not sure how much effort it is to change this to Digitalocean environment. But maybe it's easier to just copy & paste this "as-is" and deploy to Google Cloud instead.

For the frontend, we could also think of using Netlify for PR previews (and maybe even consider for production).

**Comment by carlobeltrame** [comment]
Yes, I found that as well, and it's exactly what I'm working on at the moment. I regularly push my commits to devel on my fork, but I'm also keeping a log of what I do in a text file, for writing documentation later, and thatfile is not in git yet.

Netlify looks nice, but I doubt it's a real solution because it will only work for frontend-only PRs. Or did I get that wrong?

**Comment by carlobeltrame** [comment]
Using a helm chart, it shouldn't matter whether we're deploying to DO or google or aws, or in theory even to some openshift. But we have modified the containers (e.g. running as non root, no force https redirect, loading fixtures on startup, ecamp-specific env variables), we have some different containers (frontend, print, files) than api platform (admin interface react pwa), and there is some more configuration necessary in the kubernetes cluster that isn't evident from the api platform workflow (so far I've stumbled upon installing kubectl and helm locally, ingress + ingress controller, ssl certificate and cloudflare).
So either way, I think it's a good idea for us to build up some knowledge in this area, document it and try to make it as easy to reproduce as possible, on most any kubernetes.

**Comment by usu** [comment]
> Netlify looks nice, but I doubt it's a real solution because it will only work for frontend-only PRs. Or did I get that wrong?

Yes, Netlify would be for frontend-deployment only. API/backend would need to be deployed separately and the API-URL needs to be injected as environment variable to Netlfiy (this only works if the API has a predictable URL, e.g. including the PR number).

As we try to deploy to Kubernetes, maybe it's easier to include everything in one package in Kubernetes. On the other hand, Netlify could also be a production-ready alternative for the frontend (CDN, load balancing, etc. already included for free).
