### ISSUE TITLE
List view for schedule entries

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#2349]
Re-enable or reimplement list view for schedule entries
(as alternative for calendar view)

See discussion here:
https://github.com/ecamp/ecamp3/pull/2334#discussion_r767297270

To be discussed: Go or no-go? 
If go --> more detailed spec needed

**Comment by manuelmeister** [comment]
## Core Meeting Decision

Machen wir Post MVP gemäss: https://github.com/ecamp/ecamp3/issues/1243
- PR #1260

**Comment by manuelmeister** [comment]
Has been implemented as the dashboard
