### ISSUE TITLE
DialogActivityEdit: cannot edit scheduleEntries

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#2350]
Edit timing of of schedule entries in the activity edit dialog doesn't work at the moment

To discuss:
- Do we want this or only possible via v-calendar drag & drop (probably we want, especially for mobile)
- Multiple schedule entries? (if I remember correctly, MVP shall be with single schedule entry only, correct?)

Open tasks

- [ ] Try to refactor `period: () => (this.period)()` from function into object (https://github.com/ecamp/ecamp3/pull/2366/files#r780648578)

**Comment by manuelmeister** [comment]
I thought, we did want multiple schedule entries for the mvp. We haven't fully implemented this just yet. (But on the Activity view it is already implemented, just not for adding)

**Comment by pmattmann** [comment]
Auf Activity
- Schedule-Entry erzeugen
- Schedule-Entry bearbeitne
- Schedule-Entry löschen

Perioden-Wahl durch Datum
