### ISSUE TITLE
Deprecation Warnings in tests fill the console output

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#2352]
Since symfony/security-http 5.4: The $authManager argument of "Symfony\Component\Security\Http\Firewall\AccessListener::__construct" is deprecated.

**Comment by usu** [comment]
Most of the deprecation warnings are not fixed in PR #2296
--> ready for review & merge

**Comment by usu** [comment]
Further improved with #2370

**Comment by BacLuc** [comment]
> Further improved with #2370

With #2370 its the same as 2 months ago. (I think these deprecation warnings came up with some symfony package updates.)
This last warning will be fixed with #2359
