### ISSUE TITLE
Delete EagerLoadingExtension

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#2359]
From the commit message were it was inserted:
This is until https://github.com/api-platform/core/pull/4377 is merged,
see that PR and https://github.com/api-platform/core/issues/2444 for
details.

https://github.com/api-platform/core/pull/4377 is merged, so we need to check if this class is still needed (maybe update needed), and remove it if not.

**Comment by usu** [comment]
https://github.com/api-platform/core/pull/4377 was merged into main branch. So probably it's only available in API platform 2.7.

**Comment by usu** [comment]
Fixed with #2649
