### ISSUE TITLE
Vue component auto registration was enabled by accident

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#2360]
In vite.config.js, we accidentally enabled auto registration of all our Vue SFC components.

**Todo:** Decide if we should continue with auto registered components

If not, disable auto registration:
```javascript
   ViteComponents({
      dirs: [], // disable auto component registration for our own components
      customComponentResolvers: [VuetifyResolver()]
    }),
```

\+ check for broken code that relied on auto registration
\+ Migrate to https://github.com/antfu/unplugin-vue-components

**Comment by manuelmeister** [comment]
## Core Meeting Decision

Disable auto registration for all except for Form Base
