### ISSUE TITLE
Language switcher + i18n issues

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#2421]
Placeholder for various issues with language/translation:

- [x] After login, the frontend is not immediately shown in user's language (only after reload)
- [x] After switching the language in the profile, the frontend language is not changed
- [x] When hitting the login page, the frontend is displayed in German, although my highest prio language is "en-US" (consider parsing the first 2 characters when searching for an available language)
- [x] Consider disabling developer language switcher in production mode (but maybe not on login page)

**Comment by BacLuc** [comment]
Everything works now
