### ISSUE TITLE
Migrations job on Kubernetes is not cleaned up correctly

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#2440]
When deploying using helm, we have a helm [hook](https://github.com/ecamp/ecamp3/blob/devel/.helm/ecamp3/templates/hook_db_migrate.yaml) that runs before the deployment. This hook creates a Kubernetes job, which tries to run a migration pod, and re-tries in case that pod fails. After success of one pod and with it success of the job, the job should be cleaned up by helm. We have annotated this hook with `"helm.sh/hook-delete-policy": hook-succeeded` to accomplish this.

But for some reason, the job sometimes is not deleted. So far, it happens most of the times or all of the times when `dev` was deployed, and it has started happening since we merged #2410. The deployment still works, it just marks the GitHub action as failed and sends out alert emails. The logs say:
```
Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://charts.bitnami.com/bitnami/" chart repository
Saving 1 charts
Downloading postgresql from repo https://charts.bitnami.com/bitnami/
Deleting outdated charts
Error: UPGRADE FAILED: post-upgrade hooks failed: timed out waiting for the condition
```

One example failure of job deletion:
https://github.com/ecamp/ecamp3/runs/5078801774?check_suite_focus=true

And a following example of "failed" deployment because the next time around no job can be created with the same name:
https://github.com/ecamp/ecamp3/runs/5079514649?check_suite_focus=true

To fix the situation manually, we can go to the Kubernetes cluster and delete the job manually. But this problem should be fixed permanently.

**Comment by carlobeltrame** [comment]
The migration pods actually fail. Example logs:
```
Waiting for database to be ready...
The database is now ready and reachable
{"message":"Error thrown while running command \"doctrine:migrations:migrate --no-interaction\". Message: \"Cannot load migrations from \"/srv/api/dev-data\" because it is not a valid directory\"","context":{"exception":{"class":"Doctrine\\Migrations\\Finder\\Exception\\InvalidDirectory","message":"Cannot load migrations from \"/srv/api/dev-data\" because it is not a valid directory","code":0,"file":"/srv/api/vendor/doctrine/migrations/lib/Doctrine/Migrations/Finder/Exception/InvalidDirectory.php:15"},"command":"doctrine:migrations:migrate --no-interaction","message":"Cannot load migrations from \"/srv/api/dev-data\" because it is not a valid directory"},"level":500,"level_name":"CRITICAL","channel":"console","datetime":"2022-02-08T18:53:15.728884+00:00","extra":{}}
18:53:15 CRITICAL  [console] Error thrown while running command "doctrine:migrations:migrate --no-interaction". Message: "Cannot load migrations from "/srv/api/dev-data" because it is not a valid directory" ["exception" => Doctrine\Migrations\Finder\Exception\InvalidDirectory { …},"command" => "doctrine:migrations:migrate --no-interaction","message" => "Cannot load migrations from "/srv/api/dev-data" because it is not a valid directory"]
{"message":"Command \"doctrine:migrations:migrate --no-interaction\" exited with code \"1\"","context":{"command":"doctrine:migrations:migrate --no-interaction","code":1},"level":100,"level_name":"DEBUG","channel":"console","datetime":"2022-02-08T18:53:15.754405+00:00","extra":{}}
In InvalidDirectory.php line 15:
                                                                               
  Cannot load migrations from "/srv/api/dev-data" because it is not a valid d  
  irectory                                                                     
                                                                               
doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration CONFIGURATION] [--em EM] [--conn CONN] [--] [<version>]
```

CC @BacLuc any ideas what could be going wrong?

**Comment by BacLuc** [comment]
> The migration pods actually fail. Example logs:
> ```
> Waiting for database to be ready...
> The database is now ready and reachable
> {"message":"Error thrown while running command \"doctrine:migrations:migrate --no-interaction\". Message: \"Cannot load migrations from \"/srv/api/dev-data\" because it is not a valid directory\"","context":{"exception":{"class":"Doctrine\\Migrations\\Finder\\Exception\\InvalidDirectory","message":"Cannot load migrations from \"/srv/api/dev-data\" because it is not a valid directory","code":0,"file":"/srv/api/vendor/doctrine/migrations/lib/Doctrine/Migrations/Finder/Exception/InvalidDirectory.php:15"},"command":"doctrine:migrations:migrate --no-interaction","message":"Cannot load migrations from \"/srv/api/dev-data\" because it is not a valid directory"},"level":500,"level_name":"CRITICAL","channel":"console","datetime":"2022-02-08T18:53:15.728884+00:00","extra":{}}
> 18:53:15 CRITICAL  [console] Error thrown while running command "doctrine:migrations:migrate --no-interaction". Message: "Cannot load migrations from "/srv/api/dev-data" because it is not a valid directory" ["exception" => Doctrine\Migrations\Finder\Exception\InvalidDirectory { …},"command" => "doctrine:migrations:migrate --no-interaction","message" => "Cannot load migrations from "/srv/api/dev-data" because it is not a valid directory"]
> {"message":"Command \"doctrine:migrations:migrate --no-interaction\" exited with code \"1\"","context":{"command":"doctrine:migrations:migrate --no-interaction","code":1},"level":100,"level_name":"DEBUG","channel":"console","datetime":"2022-02-08T18:53:15.754405+00:00","extra":{}}
> In InvalidDirectory.php line 15:
>                                                                                
>   Cannot load migrations from "/srv/api/dev-data" because it is not a valid d  
>   irectory                                                                     
>                                                                                
> doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration CONFIGURATION] [--em EM] [--conn CONN] [--] [<version>]
> ```
> 
> CC @BacLuc any ideas what could be going wrong?

Alte Version des docker Containers. Hier ist das neue Secret (dev-data statt dev-data-migrations) kombiniert mit dem alten Container (/srv/api/dev-data statt /srv/api/Migrations/dev-data.
Nochmals neu mergen, rebasen, so etwas sollte es lösen (oder evtl build Cache)

**Comment by carlobeltrame** [comment]
You are right it seems. Dev deployments run through smoothly.
