### ISSUE TITLE
UX for printing

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#2456]
Wann / wie / wo / was kann der Benutzer drucken?
Wie stellt der Benutzer sein PDF zusammen?

**Comment by pmattmann** [comment]
Hier mein Vorschlag:

Es gibt vermutlich zwei Arten wie etwas gedruckt werden kann.
- Druck-Seite
  Druck kann konfiguriert werden.
- Aktuelle Ansicht
  - Picasso
  - Activity
  - Story
  - ...

## Konfigurierter Druck
![image](https://user-images.githubusercontent.com/470237/155887004-89618be5-4b3d-4ec1-89c5-97dc1cb4ed5a.png)
https://wireframe.cc/884e4v

**Ideen:**
- Mit [ + Inhalt hinzufügen ] können neue Blöcke angefügt werden
- Blöcke können per Drag&Drop sortiert werden
- Blöcke können mit [x] entfernt werden
- Blöcke können abhängig ihres Types konfiguriert werden
  - Picasso
    - Periode/n
    - Hoch-/Querformat
  - Story
    - Periode/n
  - Detail-Programm
    - Periode/n
    - Tagesübersicht drucken
  - Activity
    - Schedule-Entry

Beim Besuch soll eine sinnvolle Konfiguration vorgeschlagen werden.
- Deckblatt
- Picasso  (alle Perioden; Querformat)
- Pro Periode
  - Story
  - Detail-Programm  (Tagesübersicht drucken ja)
- Inhaltsverzeichnis

**Fragen**
- Soll es möglich sein, die Konfiguration du speichern?
  - pro Camp?
  - pro CampCollaboration?

  **Vorschlag**: Post-MVP


## Druck auf Ansichten

Auf einigen Ansichten soll ein Druck-Button angeboten werden.
Die Technik hinter einem Druck-Button ist im wesentlich die Gleiche, wie bei **Konfigurierter Druck**. 
Ein Druck-Button hat eine fixierte Konfiguration hinterlegt - und führt beim Klick sofort Druck aus.

- Programm
  - Picasso (aktuelle Periode; Querformat)
- Geschichte
  - Story (alle Perioden)
  - Story (aktuelle Periode)
- Activity / ScheduleEntry
  - Activity

**Comment by manuelmeister** [comment]
## Core Meeting Decision

- JSON Objekt das die Konfiguration abbildet
  - Sprache wird auch gespeichert (default Sprache des Nutzers)
  - Daten wie ContentNodes sind nicht im Objekt enthalten, sondern nur URI der Referenzen
- [ ] Struktur Vorschlag
- Logik für Feature Toggle momentan als Dropdown Button. Beide, nur eine oder keine sollte einstellbar / konfigurierbar sein.

**Comment by pmattmann** [comment]
```json
{
  "language": "de",
  "documentName": "SoLa 2022.pdf",
  "contents": [
    {
      "type": "cover",
      "options": {}
    },
    {
      "type": "picasso",
      "options": {
        "periods": [
          "https://api.ecamp3.ch/periods/1ea343b5",
          "https://api.ecamp3.ch/periods/e29d4fa2"
        ],
        "orientation": "L"
      }
    },
    {
      "type": "story",
      "options": {
        "periods": [ "https://api.ecamp3.ch/periods/1ea343b5" ]
      }
    },
    {
      "type": "program",
      "options": {
        "periods": [ "https://api.ecamp3.ch/periods/1ea343b5" ],
        "dayOverview": true
      }
    },
    {
      "type": "story",
      "options": {
        "periods": [ "https://api.ecamp3.ch/periods/e29d4fa2" ]
      }
    },
    {
      "type": "program",
      "options": {
        "periods": [ "https://api.ecamp3.ch/periods/e29d4fa2" ],
        "dayOverview": true
      }
    },
    {
      "type": "activity",
      "options": {
        "activity": "https://api.ecamp3.ch/activities/5b32e9f",
        "scheduleEntry": null,
      }
    },
    {
      "type": "toc",
      "options": {}
    }
  ]
}
```
