### ISSUE TITLE
Dev-Daten verbessern / vervollständigen

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#2467]
Im Lager "Harry Potter Lager" in den [Development-Daten](https://github.com/ecamp/ecamp3/blob/devel/api/migrations/dev-data/Version202202051218_data.sql) fehlt der fünfte und sechste "Day". Das führt zu Konsolenfehlern, weil das Dropdown für Tagesverantwortliche nicht damit rechnet, keinen Tag zu finden.

Sobald der [Wiki-Eintrag](https://github.com/ecamp/ecamp3/pull/2410#issuecomment-1032984007) über die Aktualisierung der Dev-Daten erstellt ist, könnte das auch ein good-first-issue sein: 
Neuen Dev Daten dump erstellen mit:

- [ ] Periode um einen Tag verlängern, Periode um einen Tag verkürzen, 
- [ ] DayResponsibles
- [ ] ActivityResponsibles
- [ ] evtl den richtigen Materiallists
- [ ] hashes für inviteKey und inviteKey2 in db packen #2543

**Comment by BacLuc** [comment]
Done with #3701
