### ISSUE TITLE
Nuxt print issues (placeholder for various issues)

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#2481]
### To be checked
- [ ] Check if sentry still works (both for Nuxt & server middleware?)
- [ ] Check font handling

### Known issues
- [ ] Page break for multi column layout (as demonstrated in #2418)

**Comment by carlobeltrame** [comment]
How does this issue relate to #1241? Should we move all the Nuxt-related TODOs from there to here, and reference this issue in #1241?

**Comment by usu** [comment]
Integrated into #1241
