### ISSUE TITLE
Remove old backend

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#2485]
Ich denke, es gibt keinen Grund mehr, noch am alten backend festzuhalten.
Kann es entfernt werden?
- Ja: 👍 
- Nein: 👎

**Comment by BacLuc** [comment]
@carlobeltrame möchte das alte backend noch behalten, um die validations zu kopieren

**Comment by manuelmeister** [comment]
## Core Meeting Decision

- [x] Altes Backend aus docker-compose entfernen
