### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by janismueller** [ecamp/ecamp3#2495]
Hello 

I'm a scout leader who is interested in the new ECamp. I've tried to login to the new ecampv3 with several methodes, but non of them Worked.
Ecamp: Login Failed
Applepay: no reaction
Google : no reaction

New Account: no reaction

If you need any further informations please contact me. 

be prepared

**Comment by BacLuc** [comment]
Hey
the new ecamp version is under heavy development and many features are not yet implemented.
The environment under https://dev.ecamp3.ch/ is here to play around with the features, but we may at any time
erase the data there.
You may use the register Link to create a new account. The verification of the email is not yet implemented.
The missing validation messages for the registration form do not help the user experience, you have to choose a sure unique user name. ("test" is already taken).
The Google Login is more or less ready but not merged yet, will come with #2030 

Have fun
