### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#2539]
# Features
- Kontaktmöglichkeit
- Feature Vorschläge
- Contribution (Github)
- News / Blog
  Wir sind in Beta, keine Datenmigration, Kurse sind noch nicht abgedeckt,…
  … neue Features
- Was ist eCamp überhaupt?
- Team
- FAQ
- Privacy Policy (Needed for Google OAuth)
- Terms of Use

## Offene Fragen:
- Mehrsprachigkeit?

Landingpage: ecamp3.ch
Application: app.ecamp3.ch

# Technologie
- Statischer Seiteninhalt
- Low maintenance / sinnvolle / existierende Presets/Themes
- Generator: VitePress, VuePress, Gridsome, Nuxt/content
- Content: Markdown (mit Sprinkles wenn nötig)
  - Dynamischer Inhalte sollte vue können

Empfehlung: Gridsome

**Comment by usu** [comment]
Gridsome is more or less dead. Schade. Habe mal damit begonnen, was auf Gatsby aufzubauen (Gridsome war stark inspiriert von Gatsby).

Code: https://github.com/usu/ecamp-site

Deployment: https://resilient-mousse-5fc09a.netlify.app/

Das Template ist dieses hier: https://www.gatsbyjs.com/starters/netlify-templates/gatsby-starter-netlify-cms

Mehrsprachigkeit habe ich zusätzlich noch eingebaut + eine grobe mögliche Seitenstuktur eingebaut. Footer muss man noch aufräumen und dann noch mit Inhalten füllen. Übersetzungen fehlen grössenteils noch.

**Comment by BacLuc** [comment]
Can we close this issue?
