### ISSUE TITLE
TranslationKeys in Vue-Komponente sollte dessen Pfad entsprechen

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#2552]
Seit Restrukturierung einiger Vue-Komponenten stimmen vermutlich nicht mehr alle Translation-Keys mit dessen Pfad überein.
See: 
96111ea7992b2ad974d32a213fbe37b82206229b
272382ee8275d979697b2060b88c4ea0f7d6833b

**Comment by BacLuc** [comment]
Fixed with #3101
