### ISSUE TITLE
open migration from MaterialList

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#2591]
> Does bin/console make:migration do nothing now, as one would expect? Or why did you remove the migration?

The migration is not empty, but it's a leftover from PR #2452. Exactly the same migration is also generated in devel, so it's not connected to changing from annotation to attribute.

I first wanted to include the migration to clean it up. However, the migration is not compatible with the current data and will fail (e.g. our `MaterialList` entity says that `name` property cannot be `null`, but we have `null` data - and we actually want to allow it). This should be fixed in a separate PR.

_Originally posted by @usu in https://github.com/ecamp/ecamp3/issues/2585#issuecomment-1099207135_

**Comment by usu** [comment]
@BacLuc Do you want to have a look at this?

**Comment by BacLuc** [comment]
> @BacLuc Do you want to have a look at this?

yes, i will

**Comment by BacLuc** [comment]
closed with #2620
