### ISSUE TITLE
Installations-Doku korrigieren

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#262]
- Apache mit vHost Beispiel
- Englisch
- ... (gemäss Protokoll)
#283

**Comment by carlobeltrame** [comment]
Zusätzlich zu installieren für Apache auf Ubuntu:
``$ sudo add-apt-repository -y ppa:ondrej/php``
``$ sudo apt-get update -y``
``$ sudo apt-get install -y php7.1 libapache2-mod-php7.1 php7.1-cli php7.1-common php7.1-mbstring php7.1-gd php7.1-intl php7.1-xml php7.1-mysql php7.1-mcrypt php7.1-zip libapache2-mod-php7.1 php7.1-curl php7.1-xdebug php7.1-sqlite``
``$ sudo a2dismod php7.0``
``$ sudo a2enmod php7.1``
``$ sudo service apache2 restart``
``$ sudo chmod -R a+w <path/to/ecamp3>/data/DoctrineORMModule``

**Comment by usu** [comment]
Notizen vom 24. Juni:

- Check environment variable
- Domain (Freigabe bei Google Sign-In)
- PHP version requirements
- File permission
- Vhost/Apache Beispielkonfiguration
- Apache mods: mod_rewrite, php curl
- Schreib-Recht in Proxy-Cache-Ordner
- PHP.ini error-configurations

**Comment by usu** [comment]
- Copy to Wiki
- Google Auth
- English
