### ISSUE TITLE
User-Profil + Profil bearbeiten

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#263]

**Comment by pmattmann** [comment]
V1) 2 Routen  ->  2 Controller
V2) 1 Route  ->  1 Controller, 2 Actions
V3) 1 Route  ->  1 Controller, 1 Action  ->  Unterscheidung im GUI (Twig)

**Comment by manuelmeister** [comment]
@pmattmann gibt es bereits ein Paradebeispiel wo Daten verändert werden im GUI?

**Comment by pmattmann** [comment]
https://gist.github.com/pmattmann/e2cd2465a4e211ffb1bf232530316b6a

**Comment by pmattmann** [comment]
https://gist.github.com/pmattmann/d849a771b51305ca5367ba675ac2b3ca
