### ISSUE TITLE
500 on ContentNode collection endpoint

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#2647]
When not logged in, GET operation on the ContentNode collection endpoint (i.e. /content_nodes) returns a 500 server error instead of 401.

Same behavior on the individual content type endpoints (e.g. /content_node/storyboards).

**Comment by BacLuc** [comment]
i could not reproduce this.
See https://dev.ecamp3.ch/api/content_nodes
and https://dev.ecamp3.ch/api/content_node/single_texts
