### ISSUE TITLE
eCamp2 Aufgaben (Tageschef) - prüfen, wie intensiv verwendet

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#266]

**Comment by usu** [comment]
`SELECT job_counter, count(*) as histogram FROM (SELECT camp_id, count(*) as job_counter FROM job WHERE 1 GROUP BY camp_id) as job_counter_table GROUP BY job_counter`

ergibt folgendes Resultat:
```
|1|8214
|2|804
|3|320
|4|110
|5|78
|6|39
|7|36
|8|15
|9|12
|10|10
|11|9
|12|4
|13|3
|14|3
|15|1
|17|1
|22|1
```

D.h. ca. 15% der Lager/Kurse verwenden die Funktion von mehreren Jobs.

Die am häufigst genutzen Job-Namen sind folgende:

```
|Tageschef|9479
|Fahrer|180
|Küche|88
|Fotochef|72
|Materialchef|72
|Tageschef 2|64
|Notfallfahrer|62
|Ämtlichef|42
|Sanität|38
|Apotheke|37
|Fotograf|37
|Material|35
|Fotos|34
|Matchef|30
|Beifahrer|28
|Küchenchef|27
|Transport|25
|Ämtliplan|24
|Sani|18
|Tagesclown|18
|Budget|17
|Alkoholfrei|16
|Finanzen|16
|Lagerdraht|16
|TV|14
|2. Tageschef|14
|Reise|14
|Driver|14
|Wecken|14
|ämtli|14
|Materialwart|13
|Andacht|13
```

**Comment by usu** [comment]
Entscheid Sitzung vom 2018-08-06: Für die erste Version implementieren wir nur den Tageschef ohne Möglichkeit, weitere Tagesjobs zu definieren.

**Comment by manuelmeister** [comment]
Closed in meeting on 2018-08-06
