### ISSUE TITLE
Fix reCaptcha

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#2669]
@carlobeltrame Bräucht es nicht in `api_deployment.yaml` noch einen Eintrag unter `env`? Ist für alle anderen secrets so der Fall. Bin etwas confused, dass es trotzdem funktioniert.

_Originally posted by @usu in https://github.com/ecamp/ecamp3/pull/2628#discussion_r857159867_

- api_secrets: b64encode
- api_deployment: add env-Eintrag
- values.yaml add  recaptcha-Eintrag erstellen

**Comment by manuelmeister** [comment]
Kommt dieser Fehler von diesem Issue? https://github.com/ecamp/ecamp3/runs/6183574019?check_suite_focus=true#step:10:132
