### ISSUE TITLE
Doku Datamodel

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#269]

**Comment by pmattmann** [comment]
- Bild
- Doctrine Auto-Generator?

**Comment by usu** [comment]
UML kann via Zend Developer Tools generiert werden.
Zusätzlich grobe Aufstellung mit Kurzbeschreibung pro Entität.

**Comment by usu** [comment]
Habe mal einen Draft erstellt:
https://github.com/ecamp/ecamp3/wiki/4-Domain-Object-Model

@pmattmann Bitte um kritisches Review.
Die Kardinalität müsste stimmen, aber bei den Beziehungstypen wäre ich froh um ein Review. Ich habe die Beziehungen wie folgt umgesetzt:
- Black arrow: Nur eine Seite kennt die Beziehung.
- Black line: Beide Seite kennen die Beziehung.
- Black diamond: Das Kind gehört eindeutig zum Parent und wird beim Löschen des Parents zerstörts (Cascade delete + orphanRemoval).

Ein paar weitere Kommentare:
- Der yUML code ist im Markdown als Kommentare hinterlegt. Das macht es etwas einfacher, die Diagramme anzupassen, da die Formattierung ein wenig verloren geht bei yUML.
- Die Anordnung der Diagramme kann nur beschränkt beeinflusst werden und ein paar Texte sind verdeckt, aber ich denke für einen ersten Wurf sollte es reichen. Ist einiges schneller als selber zu zeichnen.
- UserRelationship, Jobs und EventTypeFactory hab ich wie an den letzten Sitzungen besprochen weggelassen.

Sobald wir das Review der Seite durch haben, werd ich dann den Sourcecode der Entitäten nochmals prüfen, damit der Code konsistent ist mit den Diagrammen.

**Comment by pmattmann** [comment]
MailAddress:
Vorteil von eigenes Entität ist, dass ein einfacher Unique-Index erstellt werden kann.
Ohne eigene Entität müsste der Unique-Index über zwei Spalten gehen (trusted und untrasted MailAddress). Das ist leider nicht so einfach.

Organization:
Abschaffen und CampType an Root-Groups hängen wäre eine Möglichkeit. Wäre für mich auch ok.

Group:
Wieso ist die Parent-Group Referenz mit weisser Route abgebildet? Was bedeutet eine weisse Route?

CampType:
N:N von CampType zu Organization (oder Root-Group) wäre auch denkbar. Da CampType <-> EventType bereits N:N ist, glaube ich ist der OverHead von doppelt erfassten CampType nicht so gross. Für mich sind jedoch beide Lösungen gültig.

Medium:
Ja, ich könnte auch mit Konstanten leben.


Evtl. würde ich noch zwei Bemerkungen ergänzen:
- Was wird alles erzeugt wenn ein neues Camp erstellt wird.
   (Periods, Days, EventCategories, ...)
- Was wird alles erzeugt, wenn ein neues Event erstellt wird.
   (EventInstance, EventPlugin, ...)

**Comment by usu** [comment]
**MailAddress**: ok, so gelassen

**Organization**: Hab ich mal so gelassen, da wir ja in einem ersten Schritt gar keine Gruppen wollen, die Organization aber trotzdem benötigen.

**Group**: Beziehung sollte black-diamond sein (composition/owning). Weiss wäre Aggregation. Hab ich korrigiert.

**CampType**: Hab ich mal so gelassen.

**Medium**: Entfernt und machen wir mit Konstante. Ich glaube die Bedeutung von Medium reduziert sich jetzt mit SPA sowieso auf das printing.

Bemerkungen zum Erstellen von Camp und Event habe ich hinzugefügt.

Jetzt schau ich mir noch den Sourcecode an, damit die Implementation mit der Doku übereinstimmt.
