### ISSUE TITLE
MockUp Entwurf

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#277]

**Comment by usu** [comment]
Für ersten Prototyp:
-	Bootstrap
-	SASS
-	Mockups mit ein paar weiteren View-Vorschlägen mit 2 Headmenus

**Comment by manuelmeister** [comment]
Ich habe ein einfaches Mockup gemacht, in dem man die Seitenleiste ausklappen kann und die auch auf Mobile funktioniert.
http://ecamp.42m.ch/2018-10-23-15-25/

Es kann hat no nicht mehr Views als an der letzten Sitzung besprochen.

**Comment by manuelmeister** [comment]
**Pendenzen aus der Sitzung:**
- S/W Icon-Library wählen
- Farbschema definieren
- Auf Dashboard-Ebene Items finden
- Meine Gruppen analog zu Dashboard von Lager
 
**Idee**
- Auf Mobile die Tagesansicht alle Blöcke als Karten anzeigen

**Comment by manuelmeister** [comment]
@usu @pmattmann @carlobeltrame 
Wie findet ihr diese Icons?
<img width="702" alt="screen shot 2018-10-31 at 10 07 25" src="https://user-images.githubusercontent.com/3001985/47777366-e4968200-dcf4-11e8-85f2-9b3afb91ffa5.png">

**Comment by carlobeltrame** [comment]
Gar noch nicht gesehen, aber die gefallen mir gut.

**Comment by manuelmeister** [comment]
An der Sitzung am 27. November haben wir beschlossen, dass wir grundsätzlich mit dem Layout zufrieden sind:  
- Hauptnavigation
- Unternavigation
- Sidebar / Overview
- Inhalte / Formulare 
  
Ich beginne nun Use Cases zu erstellen: #308
