### ISSUE TITLE
Code Architecture dokumentieren

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#279]

**Comment by usu** [comment]
@pmattmann Siehe https://github.com/ecamp/ecamp3/wiki/6-Code-architecture. Was meinst du dazu als starting point für Dokumentation der Architektur? Was würdest du noch dazu nehmen? Wo würdest du die Grenze ziehen?

Ich würde dann ähnlich wie beim DOM zu den wichtigsten Komponenten eine kurze Erklärung dazustellen.

**Comment by pmattmann** [comment]
- OtherServices gepunktet (möglich aber möglichst wenig)
- Einzelne Blöcke beschreiben

**Comment by usu** [comment]
- Änderungen des letzten Jahres übernommen (kein eCampWeb mehr und alles via API)
- Beschreibung der einzelnen Blöcke

https://github.com/ecamp/ecamp3/wiki/6-Code-architecture-(backend)

**Comment by usu** [comment]
@pmattmann can you review?

**Comment by carlobeltrame** [comment]
Zum Problem mit der `HAL\Link` Dependency in den Hydrators: Aus meiner (uninformierten) Sicht gehörten die Hydrators eigentlich eher in eCampApi als Core, da sie sich mit der Präsentation der Core-Daten in der API beschäftigen. Weiss aber nicht ob da technische Gründe dagegen sprechen.
