### ISSUE TITLE
Add API endpoint to receive route information

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#282]
Bis jetzt ist in der API nur `GET /api/camp/{id}` möglich. Damit das Vue.js-Frontend ohne Hilfe von PHP / direktem DB-Access auf ein Camp zugreifen kann, brauchen wir einen Endpoint `GET /api/camp/byname/{name}` oder ähnlich.

Alternative wäre, in der Route im Frontend nicht den Camp-Namen sondern die id einzubetten, dann könnte man in Vue die aktuelle URL parsen.

**Comment by pmattmann** [comment]
Vorschlag:
Route /group/.../camp/name(.route).json soll JSON-Objekt mit Info zu Route zurückschicken.
z.B. Camp-Id
