### ISSUE TITLE
PUT camp details

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#284]
Add an endpoint `PUT /api/camp/{id}` or `PUT /api/camp/{name}` that allows updating the details of a camp.
Alternative: PATCH instead of PUT, with a payload format to be defined (e.g. http://jsonpatch.com/)

**Comment by pmattmann** [comment]
API-Methods sind in /moduel/eCampApi/config/autoload/camp.config.php eingestellt
