### ISSUE TITLE
Assets direkt im Web Modul

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#285]
URL für assets:
- module/EcampWeb/assets/web/js/***.js
- http://localhost/assets/web/js/***.js

Module:
https://github.com/zfcampus/zf-asset-manager

**Comment by usu** [comment]
@carlobeltrame und @pmattmann : 
Nicht sicher, ob wir das überhaupt brauchen, da Webpack ja genau das macht für JS, CSS und sogar Images, wenn korrekt konfiguriert.

https://codeburst.io/using-vue-js-components-in-php-applications-e5bfde8763bc

**Comment by carlobeltrame** [comment]
Wir brauchen schon den assets-Ordner, denn das von Webpack generierte .js-File muss unser Apache o.ä. ja trotzdem serven, und zwar auch Modul- bzw. Plugin-spezifisch. Aber es sollten nicht nur ***.js Files sein, sondern einfach alle Files im assets-Ordner direkt unter localhost/assets/web/ veröffentlichen, wie in #289 implementiert

**Comment by pmattmann** [comment]
Ich habe das noch nicht untersucht - aber ich teile die Einschätzung von @usu.
Mit grosser Wahrscheinlichkeit brauchen wir den garnicht. 
Müssen wir unbedingt prüfen - würd in der Tat viel mehr Sinn ergeben!
