### ISSUE TITLE
Keep i18n keys to our rules

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#2932]
According to our rules defined in https://github.com/ecamp/ecamp3/wiki/localization-and-translations#rules-for-working-with-translations

_Originally posted by @carlobeltrame in https://github.com/ecamp/ecamp3/pull/2780#discussion_r955197174_

**Comment by carlobeltrame** [comment]
Maybe write a custom ESLint rule: https://developers.mews.com/how-to-write-custom-eslint-rules/
