### ISSUE TITLE
Test setup: Cannot use 2 API requests within the same test

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#2943]
The following test fails although it should pass:
```php
public function testDeleteActivityAlsoDeletesContentNodes() {
        $client = static::createClientWithCredentials();

        $client->request('DELETE', $this->getIriFor(static::$fixtures['activity1']));
        $this->assertResponseStatusCodeSame(204);

        $client->request('GET', $this->getIriFor(static::$fixtures['columnLayout1']));
        $this->assertResponseStatusCodeSame(404);
    }
```

**Why it fails?**
Each API request is encapsulated within a transaction (`RequestTransactionListener`). In addition, each test is encapsulated within a transaction/rollback (`RefreshDatabaseTrait`).

After each API request, the database connection is removed (by design in `doctrine/DoctrineBundle`).

When the 2nd API-request (GET) is booted, no connection is available (removed after 1st request). Hence, a new connection is created which triggers a new transaction. Because the earlier transcation was never closed, this earlier transaction is being rolled back.

Rollback resets the data, hence `columnLayout1` which should have been deleted with the 1st request is now again in the DB.

Further context:
- https://github.com/doctrine/DoctrineBundle/issues/407
- potential solution: https://github.com/dmaicher/doctrine-test-bundle

**Comment by carlobeltrame** [comment]
We already have such tests, and have already "solved" the problem: https://github.com/ecamp/ecamp3/blob/6b209e307cb86ff913ba178b8cf085ebb2b4dbe8/api/tests/Api/Users/CreateUserTest.php#L30

**Comment by usu** [comment]
Ah nice, thanks for the hint
