### ISSUE TITLE
Period display in Camp Admin shows NaN

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#2960]
https://dev.ecamp3.ch/camps/c4cca3a51342/GRGR/admin
![Screenshot 2022-09-03 at 14-00-25 eCamp3](https://user-images.githubusercontent.com/7566995/188269513-5755d2b3-5873-4e26-8185-44040c3a7ea4.png)

It should instead show the start and end dates of the period.

The same happens in the dropdown menu for selecting a period:
https://dev.ecamp3.ch/camps/c4cca3a51342/GRGR/admin
![Screenshot 2022-09-03 at 14-02-25 eCamp3](https://user-images.githubusercontent.com/7566995/188269601-e9ca40d1-362e-4f92-9a15-27f2328cd7ab.png)

**Comment by VincentWoglo** [comment]
Can you assign me to this. I'll take a look at it
