### ISSUE TITLE
Json data: verify handling of empty objects

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#2969]
Storyboard sections currently have the following json format (both in DB and in api response).
```json
{
  "data": {
    "sections": {
      "2736647e-cebd-4d1d-8447-80080d8740a3": {
        "column1": "<p>1.00</p>",
        "column2": "<p>Section1</p>",
        "column3": null,
        "position": 1
      },
      "34b6f7f9-fbc6-41c4-bb26-037ce38f8143": {
        "column1": "<p>00.00</p>",
        "column2": "<p>Section2</p>",
        "column3": null,
        "position": 0
      }
    }
  }
}
```

When there's no section, the format in DB looks like this (empty object):
```json
{
  "data": {
    "sections": {}
  }
}
```

The response from API however looks like this (empty array):
```json
{
  "data": {
    "sections": []
  }
}
```

Didn't dig into this further so far, but probably this is the limitation of how PHP handles both formats as arrays (one as associative array and one as lists). When it's empty, they cannot be distinguished.

A potential solution could be to avoid usage of empty object and setting null values instead:
```json
{
  "data": {
    "sections": null
  }
}
```

**Comment by usu** [comment]
The issue seems to come from DBAL, which uses `json_decode` with parameter `$associative = true`:
https://github.com/doctrine/dbal/blob/3.4.x/src/Types/JsonType.php#L60

This seems to be by design. Quote from https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html:
> The json type doesn't preserve the type of PHP objects. PHP objects will always be encoded as (anonymous) JSON objects. JSON objects will always be decoded as PHP associative arrays.
> To preserve the type of PHP objects, consider using [Doctrine JSON ODM](https://github.com/dunglas/doctrine-json-odm)

I could see the following options:

1. Fix in frontend to detect empty arrays as empty objects (current workaround as per commit https://github.com/ecamp/ecamp3/pull/2971/commits/033f8f3a039f8f99a818a9a0d7c6faaeb4aecfcd)
2. Avoid using empty objects (e.g. by using null values instead)
3. Write own DBAL type which uses `json_decode` with parameter `$associative = false`. This might not be that simple (depends on how symfony/API-platform can handle this for serialization/deserialization)
4. Use [Doctrine JSON ODM](https://github.com/dunglas/doctrine-json-odm). Might be an overkill.

**Comment by manuelmeister** [comment]
## Core Meeting Decision
Storyboard, muss immer mind. eine Section haben
