### ISSUE TITLE
Split Backend/Frontend

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#299]

**Comment by pmattmann** [comment]
#293  und  #298 
Sorry - push auf #293 war 'ausversehen'

**Comment by carlobeltrame** [comment]
Splitten wir jetzt Backend und Frontend unabhängig von Outcome der beiden POCs? Je nach dem ist ja ecampWeb doch noch ein Zend Modul.
Falls doch, hat es in #298 noch mehr Commits drin die nicht nötig sind, könntest du nur den split commit auf einen eigenen Branch cherry-picken?

**Comment by usu** [comment]
Habe es gleich verstanden wie @carlobeltrame 
Splitting Backend/Frontend gehört für mich zu #295 und macht nur Sinn, wenn wir dann tatsächlich auf SPA wechseln
