### ISSUE TITLE
Implement clarification between camp.name and camp.title

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#2992]
What should be the difference between name and title property of the camp? How do we explain the difference to users?

At the moment both cannot be empty and both are limited to 32 characters.

At some places we use the name, at some we use the title. E.g.
- invitation email reads "Invitation to Sola 2023"
- the invitation page reads "Invitation to Camp Harry Potter Lager"

**Comment by usu** [comment]
camp.name: rename to camp.shortname, mandatory, max. 16 characters, will always be displayed
camp.title: non-mandatory, max. 64, will be displayed where we have sufficient space
camp.motto -- > translation "Motto / Thema"

**Comment by manuelmeister** [comment]
I agree with shortname, title or camp name and different translation for motto.
We can also create placeholders:

Shortname: SoLa 23
Camptitle: Sommerlager 2023 Hogwards
Motto: Harry Potter und der Unittest

**Comment by manuelmeister** [comment]
# Core Meeting Decision
Implement this as specified by usu, but set max length of shortname to 12 characters.
Migration for existing data. Notify users with mismatching data about the deadline when we cut the prod data to match.
First change the frontend to disallow longer content, watch out to respect current lengths.
In a second step try to migrate or else cut down.

**Comment by nstni** [comment]
it would be really nice if the organisation culd be seen on the overview with the selection!this would make it much easier to distinguish. especially if camps are opened before the theme is known, the risk that they are named very similar is high.

also, if the organisation is mandatory on the picasso, shouldn't it be a mandatory entry when creating the camp?

**Comment by carlobeltrame** [comment]
> also, if the organisation is mandatory on the picasso, shouldn't it be a mandatory entry when creating the camp?

It's only mandatory in J+S camps, not in courses nor in other types of non-J+S camps. Also, we can't make a newly added field required retroactively, because not all existing camps will have it filled in

**Comment by manuelmeister** [comment]
I've received the feedback multiple times, that for the pdf "Cover" they expect the short name to be used instead of the long full title for the big font.
