### ISSUE TITLE
Changing profile names is not reactive

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#2994]
Changing `nickname`, `surname` or `firstname` in profile is not reactive, because `user.displayName` is used to display the name of the user in the frontend.

**Potential solution:**
- Reload user entity after changing any of these properties in profile
- Or: embedd user entity in response from API

<img width="486" alt="image" src="https://user-images.githubusercontent.com/449555/192129795-6b9bf831-55de-4db2-bd4f-5d65fa52214e.png">

**Comment by carlobeltrame** [comment]
Another solution would be, if we ever get around to implementing https://github.com/ecamp/hal-json-vuex/issues/2. Then we could automatically define a getter user.displayName in the frontend which assembles the displayName from the linked profile data.

**Comment by usu** [comment]
Yep, that would be a nice application of this feature.

If we're concerned about the authenticated user only, then another option would be to add a vuex getter to the new vuex module introduced here: https://github.com/ecamp/ecamp3/pull/2993/files#diff-40fa57b3059ed8e2b66c007c75f7c73bfb5426ab13b62a029adb31cc8ee91d49

**Comment by carlobeltrame** [comment]
Immediate problem was fixed in #3403. Further refactoring is being done in #3404.
