### ISSUE TITLE
No support for IE11

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#302]
Ich möchte IE11 nicht unterstützen, sonst müssen wir den ganzen Frontend-Code von ES6 auf ES5 transpilieren.

**Comment by carlobeltrame** [comment]
Dazu vielleicht interessant der geplante spezielle Support für IE11 in der nächsten Vue.js-Version: https://medium.com/the-vue-point/plans-for-the-next-iteration-of-vue-js-777ffea6fabf

**Comment by manuelmeister** [comment]
Keinen Support für Zombies!
