### ISSUE TITLE
Vee-Validate rules which reference other fields do not work

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#3027]
While implementing password / password confirmation validation, I noticed that neither our own `pwConfirmed` nor the built-in `confirmed` validation rule of vee-validate work in our setup. Maybe our setup with validation provider on each `<e-input>` does not allow for that? Should we move the `<validation-provider>`s to the `<v-input>` components and add a combined `<validation-provider>` to all forms with plain `<e-input>` fields?

We also have another custom rule `minDate` which isn't working either right now, due to the same problem. This one is in use in the period creation and editing (and camp creation) forms.

**Comment by usu** [comment]
> We also have another custom rule `minDate` which isn't working either right now, due to the same problem. This one is in use in the period creation and editing (and camp creation) forms.

date validation was fixed in #2967 - eagerly waiting for reviews 😄

**Comment by usu** [comment]
Fixed with #3028 and #2967
