### ISSUE TITLE
Warum sind UserIdentity und User verschiedene Entities?

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#305]
Damit ein User mehrere Login-Methoden / Login-Provider haben kann? Brauchen wir das?

**Comment by manuelmeister** [comment]
Ja, dass ist wichtig. Sonst sind wir von einem Identityprovider abhängig.

**Comment by carlobeltrame** [comment]
Mehrere Optionen für Login-Provider aus denen der User eine auswählen kann könnten wir auch haben, wenn wir die UserIdentity-Felder (provider und providerId, also z.B. 'google' und 'mygmailaddress@gmail.com') direkt auf dem User speichern. Im Moment besteht aber die Möglichkeit für einen einzelnen User, gleichzeitig mehrere UserIdentities von verschiedenen oder gleichen Providern zu haben.
Bei allen anderen Webservices die mir einfallen die mehrere Social-Logins anbieten habe ich auch keine Möglichkeit, mehrere zu erfassen. Ein bestimmter Webservice sagt es mir sogar regelmässig wenn ich mich aus Vergesslichkeit versuche mit email/Passwort einzuloggen: "It seems you usually log in via Facebook with that address" o.ä..
Ich bin nicht dagegen, mich interessiert nur die Idee hinter dieser Trennung ;)
