### ISSUE TITLE
Vuex + REST  Beispiel

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#309]
- State laden
- Action, Mutation
- Error-Handling (&ACL)

**Comment by manuelmeister** [comment]
VUEX Ressource Store mit URIs

**Comment by manuelmeister** [comment]
### Spezifikation:
Ein Objekt ist entweder leer oder vollständig.

Nur Embeded:
- Leer (Proxy):  Self-Link (+ evtl ID)
- Vollständig: Alle Properties + Alle Relations (entweder Embeded oder als Link verfügbar)

Eine Embeded-Liste muss Element-vollständig sein.

Frage ist, gibt es Proxies für Embeded-Listen, nur Link oder Kombination?

@usu rechechiert die Originale Spez
https://tools.ietf.org/html/draft-kelly-json-hal-08

**Comment by carlobeltrame** [comment]
Mein Vorschlag für das REST-Format, basiert auf dem HAL JSON Format das von Spring Data REST generiert wird, mit einigen Modifikationen um ähnlicher wie ZF-hal / apigility zu sein. Offen zur Diskussion.
```
// GET root endpoint
GET /
Accept: application/json


HTTP 200/OK
Content-Type: application/json

{
  _links: {
    self: { href: "/", },
    logout: { href: "/logout", },
    me: { href: "/me", },
    camps: { href: "/camps", },
  }
}

###

// GET collection, always paginated, but page parameters have sensible defaults
GET /camps?page=1&per_page=3
Accept: application/json


HTTP 200/OK
Content-Type: application/json

{
  _page: 1,
  _per_page: 3,
  _total: 7,
  _links: {
    self: { href: "/camps", },
    first: { href: "/camps?page=0&per_page=3" },
    prev: { href: "/camps?page=0&per_page=3" },
    next: { href: "/camps?page=2&per_page=3" },
    last: { href: "/camps?page=2&per_page=3" },
  },
  _embedded: {
    items: [ // key should always be "items"
      {
        // ... should look exactly like the response from GET single entity (see below)
      },
      {
        // ...
      },
      {
        // ...
      },
    ],
  },
}

###

// GET single entity
GET /camps/1
Accept: application/json


HTTP 200/OK
Content-Type: application/json

{
  name: "Mein Lager",
  motto: "Piraten",
  
  // Embedded single entity
  campType: {
    name: "camp",
    js: true,
    targetGroup: "Kids",
    _links: {
      self: { href: "/campTypes/20", },
    },
  },
    
  // Embedded collection (not paginated, full list)
  periods: [
    {
      start: "01-01-2019",
      end: "03-01-2019",
      _links: {
        self: { href: "/periods/104", },
        camp: { href: "/periods/104/camp", }, // Never embed backreferences, that would lead to infinite nesting
        events: { href: "/periods/104/events", },
      },
    },
    {
      start: "12-04-2019",
      end: "19-04-2019",
      _links: {
        self: { href: "/periods/128", },
        camp: { href: "/periods/128/camp", },
        events: { href: "/periods/128/events", },
      },
    },
  ],
  
  _links: {
  
    self: { href: "/camps/1", },
    
    // Link to single entity (single entities always use absolute link)
    mainLeader: { href: "/users/83", },
    
    // Link to collection (paginated, relative link)
    events: { href: "/camps/1/events", },
    
  },
}

###

// GET nested collection (from relative link). Same as normal collection, except the entries' self links aren't sub-paths of the relative link (instead, entries have absolute URLs)
GET /camps/1/events
Accept: application/json


HTTP 200/OK
Content-Type: application/json

{
  _page: 0,
  _per_page: 10,
  _total: 3,
  _links: {
    self: { href: "/camps/1/events", }, // next and prev links are only sent if they exist
    first: { href: "/camps/1/events" }, // first is always sent, optimally without page=xx parameter
    last: { href: "/camps/1/events?page=0" }, // last is optional
  },
  _embedded: {
    items: [
      {
        title: "Volleyball",
        type: {
          name: "LS",
          color: "#00aa00",
          _links: { self: { href: "/eventTypes/8877" }, },
        },
        _links: { self: { href: "/events/2394" }, },
      },
      {
        title: "Geländespiel",
        type: {
          name: "LP",
          color: "#aaaa00",
          _links: { self: { href: "/eventTypes/8879" }, },
        },
        _links: { self: { href: "/events/2362" }, },
      },
      {
        title: "TABS",
        type: {
          name: "LP",
          color: "#aaaa00",
          _links: { self: { href: "/eventTypes/8879" }, },
        },
        _links: { self: { href: "/events/2402" }, },
      },
    ],
  },
}

###

// POST to a collection to create a new entry
POST /camps
Content-Type: application/json

{
  name: "Herbstlager",
  motto: "Pippi Langstrumpf",
  
  // Single entity
  campType: "/campTypes/20",
  
  // Collection
  periods: [
    "/periods/104",
    "/periods/128",
  ],
  
  // Doesn't matter if it's normally embedded or in _links, associating works the same way
  mainLeader: "/users/83",
  
  events: [], // empty lists can optionally be omitted
}


HTTP 201/Created
Location: /camps/7
```

**Comment by manuelmeister** [comment]
# Spezifikation
- [x] Im Store sollten Metadaten ` _meta: { etag, expire, … }` verfügbar sein.
- [x] `self: 'uri'` ist geschützte Referenz auf sich selber
- [x] Auf dem Store muss `purge('uri')` und `reload('uri')` gemacht werden können. Reactivity muss hier gut getestet werden! Purge muss Daten aus dem Objekt löschen und die Referenz aus dem Store entfernen. Reload muss das bestehende Objekt updaten (rekursiv), damit die Referenz nicht ändert.
- [x] Proxy sind stark gewünscht, werden aber im Moment noch nicht eingeführt, da sie im Moment nicht verwendet werden. (Use Case: `ETag`, `EXPIRES`) 
- [x] Im Store wird für jede Page einer Collection einen Eintrag erstellt. (auch für `?page=0` in der URI)
- [x] Store-Einträge ohne Page-Angabe sind Element-vollständig (`Store.getAll()`)
- [x] Next & Prev ist im Store-Eintrag-Meta nicht bei `Store.getAll()` vorhanden
- [x] Nicht-Primitive-Child-Objekte liegen im `_embedded`. Bei Naming-Konflik gewinnt niemand ==> Error
- [x] Discriminator zwischen normalen Objekt und Paginator ist, dass auf dem normalen Objekt das Attribut `id` gesetzt ist
- [x] Frontend muss Parameter immer gleich in der URI sortieren (das soll der Store automatisch übernehmen)
- [x] Auf dem Store gibt es folgende Actions: CREATE, UPDATE, PATCH, DELETE
- [x] CREATE nimmt einen Collection-Endpunkt und alle Daten genau nach Backend-Spezifikation
- [x] UPDATE(put), PATCH(delta) & DELETE nimmt einen Objekt-Endpunkt und Daten gemäss Backend-Spezifikation
- [x] Folgende Daten-Übertragungsmechanismen sind für die Spezifikation erlaubt,
 widerspruch führt zu Error:
  - `/camp/1/events {…}` (wird in apigility nicht unterstützt)
  - `/events?camp=1 {…}`
  - `/events {camp: 1, …}`
- [x] nach allen CRUD Operation wird der neue IST-Zustand geantwortet

**Comment by pmattmann** [comment]
Mit Apigility gibt es noch ein Problem:
Es kann pro Resource bei der Serialisierung die maximale Referenz-Tiefe angegeben werden.
Sobald diese Tiefe erreicht ist, werden die entsprechenden Entitäten nicht weiter aufgelöst.

Ein Abbruch bei erreichter Referenz-Tiefe sieht wie folgt aus:
```
"plugin": {
  "_links": {
    "self": { "href": "http://localhost:8888/api/plugin/64d1554a" }
  }
}
```
Also ein Objekt nur mit einem self-Link... sonst NIX.
=> Also ein Proxy ohne Meta-Daten.

Ich stelle daher den Antrag, dass wir die Proxies bereits jetzt implementieren.

**Comment by carlobeltrame** [comment]
Also ein Link ausserhalb des `_links` (und stattdessen im `_embedded`) Objekts? Wie kann ich dann unterscheiden ob es ein Proxy oder einfach eine vollständig geladene Entity ist die zufällig keine Felder hat?

**Comment by pmattmann** [comment]
## Hier mein Vorschlag:
Es gibt Objekte, Listen und Referenzen.
Bei einer Referenz ist vor dem laden unklar, ob ein Objekt oder eine Liste referenziert wird.



### Objekt:
```json
{
    "_meta": {
        "etag": "..."
    },

    "id": "123ab",
    
    "key1": "value1",
    "key2": "value2",
    
    "_embedded": {
        "obj1": "objekt-or-referenz",
        "list1": "embedded-list"
    },

    "_links": {
        "self": { "href": "self-uri" },
        "link1": { "href": "link1-uri" }
    }
}
```

**Regeln**
- "ID" ist pflicht
- Self-Link ist pflicht

**Erkennung:**
- Property "ID" vorhanden



### Liste:
```json
{
    "_meta": {
        "etag": "..."
    },

    "_links": {
        "self": { "href": "self-uri?page=3" },
        "first": { "href": "self-uri?page=1" },
        "last": { "href": "self-uri?page=6" },
        "prev": { "href": "self-uri?page=2" },
        "next": { "href": "self-uri?page=4" }
    },

    "_embedded": {
        "items": [
            "objekt-or-referenz",
            "objekt-or-referenz"
        ]
    }
}
```

**Regeln**
- Self-Link ist pflicht
- First/Last-Link ist pflicht
- Prev/Next-Link vorhanden falls Vorgänger-/Nachfolger-Seite existiert
- Page-Number startet bei 1
- _embedded ist pflicht
- _embedded enthält die Elemente unter dem Property "items"
- Enthaltene Elemente können Objekte oder Referenzen sein

**Erkennungs-Kriterium:**
- Kein Property "ID" vorhanden
- Property "_embedded" vorhanden



### Embedded-Liste:
```json
[
    "objekt-or-referenz",
    "objekt-or-referenz"
]
```

**Beispiel**
```json
{
    "_meta": { "etag": "..." },
    "id": "123ab",
    
    "_embedded": {
        "list1": [
            "objekt-or-referenz",
            "objekt-or-referenz",
        ]
    },

    "_links": { "self": { "href": "self-uri" } }
}
```

**Regeln**
  - Liste ist Element-Komplett (Objekte oder Referenzen erlaubt)

**Erkennungs-Kriterium:**
Nicht notwendig, da Embedded-List



### Objekt- / Listen-Referenz:
```json
{
    "_meta": {
        "etag": "..."
    },

    "_links": {
        "self": { "href": "self-uri" }
    }
}
```

**Regeln**
- Nur "_meta" und "_links" sind erlaubt
- Self-Link ist pflicht

**Erkennungs-Kriterium:**
- Kein Property "ID" vorhanden
- Kein Property "_embedded" vorhanden
- Self-Link vorhanden

**Comment by carlobeltrame** [comment]
Okay, dann unterscheide ich nach folgender Logik:
* (Ist das Subjekt in einer Superstruktur namens _embedded und ist es eine Liste? Dann ist es eine embedded list.)
* Hat das Subjekt keinen Self-Link? Dann ist es primitiv.
* Hat das Subjekt eine Property "id"? Dann ist es ein embedded Objekt.
* Hat das Subjekt eine Property "_embedded"? Dann ist es eine Liste.
* Sonst ist es eine Referenz.

Ist halt schon recht spezifisch für unsere API so, aber ich versuche diese Logik konfigurierbar zu machen falls wir den Parser mal als Library extrahieren wollen.

**Comment by carlobeltrame** [comment]
Related, sehr interessant zu lesen: https://forum.vuejs.org/t/vuex-best-practices-for-complex-objects/10143
Und https://vuex-orm.github.io/vuex-orm/

**Comment by pmattmann** [comment]
Create - Entity:
Apigility erstellt Entity und füllt Daten mit Hydrator ab
> Entity: JSON-Objekt
  > Properties gemäss Doku (array, objekte, skalare)
     z.B. Array von Referenzen; es muss das ganze Array übermittelt werden
  > Referencen: { href: "https://domain.tld/api/obj/id" }

Patch - Entity:
Apigility lädt Entity und füllt vorhandene Daten aus Request mit Hydrator ab
> Entity: JSON-Objekt
  > Properties gemäss Doku (array, objekte, skalare)
     z.B. Array von Referenzen; es muss das ganze Array übermittelt werden
  > Referencen: { href: "https://domain.tld/api/obj/id" }

Update - Entity:
Apigility lädt Entity und füllt alle Daten aus Request mit Hydrator ab (fehlende werden mit NULL befüllt)
> Entity: JSON-Objekt
  > Properties gemäss Doku (array, objekte, skalare)
     z.B. Array von Referenzen; es muss das ganze Array übermittelt werden
  > Referencen: { href: "https://domain.tld/api/obj/id" }

Delete - Entity:
No Body; Apigility löscht Objekt.




```
{
  title: "Post-Title",
  auther: { href: "https://domain.tld/api/user/1" }, 
  tags: [
    { href: "https://domain.tld/api/tag/3" }, 
    { href: "https://domain.tld/api/tag/4" }, 
  ]
}
```

**Comment by pmattmann** [comment]
Laden / Mutieren

```javascript
this.api.get(uri);

this.api.create(uri, { .... });

this.api.update(uri, {
  title: "Post-Title",
  author: {
    id: 1,
    name: "Hans",
    ...
  }, 
  tags: [
    { 
      id: 3,
      name: green
    }, 
    { 
      id: 4,
      name: red
    }, 
  ]
});
this.api.update(obj, {...});

this.api.patch(uri, { ... });
this.api.patch(obj, { ... });

this.api.delete(uri);
this.api.delete(obj);
```

**Comment by carlobeltrame** [comment]
Purge und reload habe ich in einem [Branch](https://github.com/carlobeltrame/ecamp3/tree/vuex-hal-write-operations) implementiert.

Für create stellt sich die Frage, wie wir mit POST in eine embedded collection umgehen wollen. Beispiel: `/camp/1` hat eine embedded collection periods. Auf welche URI POSTe ich eine neue Periode? Ich möchte ja wenn möglich nicht `/period` im frontend hardcoden.

Delete bin ich dran, habe noch Store-Probleme zu lösen (wenn ich ein camp lösche, muss ich es auch aus allen camp-listen im Store löschen, oder alle camp-listen im store neu von der API fetchen). Aber backendseitig wird ein camp auch momentan gar nicht gelöscht mit `DELETE /camp/1`, kann das sein? HTTP response 204 kommt, aber das Camp kann nachher genau gleich wie vorher immer noch abgerufen werden.

**Comment by pmattmann** [comment]
Korrekt, es gibt noch einen Bug im Backend, so dass das DELETE am Schluss auf der DB nicht comitted wird. Werde ich ansehen.

Hier ein Vorschlag, wie DELETE auf dem Client funktionieren könnte:
1. DELETE an Server schicken
2. Wenn OK (204) zurück kommt, Entity im VuexStore als gelöscht markieren (in  _meta  als deleted markieren)

So sollte es möglich sein, die gelöschten Entitäten auf der Client-Site auszufiltern:
- Get() auf Store gibt NULL zurück
- Beim Zugriff auf eine Liste werden die gelöschten Element gefiltert

Beispiel:
Camp.Events() liefert nur Events, welche nicht als gelöscht markiert sind.

Zudem kann bei einem Reload einer Entität, welche inzwischen auf dem Server gelöscht wurde (Server antwortet auf Reload mit 404), diese auf dem Client ebenfalls als gelöscht markiert werden - so verschwindet diese Entität vom GUI.

Ich hoffe, die Idee ist verständlich beschrieben ;)

**Comment by pmattmann** [comment]
Siehe #336
