### ISSUE TITLE
Update kubernetes documentation with DNS safety settings

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#3097]
Add the newly used parameters for our multi-cluster shared-dns setup to our wiki: https://github.com/ecamp/ecamp3/wiki/installation-deployment-kubernetes#dns

**Comment by BacLuc** [comment]
Updated with https://github.com/ecamp/ecamp3/wiki/installation-deployment-kubernetes/_compare/1ad82476db35f83f76d4dfd6239530a4c37d8d29...3eb3f140cf4ed18baae871bb2db958a20c18c5a7
