### ISSUE TITLE
CreateCamp in Vue.js

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#310]
- Name
- Owner
  - /* Gruppe gemäss Auswahl */
  - /* Gruppe (neu erzeugen) */
  - User (angemeldeter Benutzer)
- /* Einladung */
(Rest gemäss MockUp)

~ Validation (Vuelidate ??)

**Comment by manuelmeister** [comment]
Gruppe noch nicht implementieren gemäss #312

**Comment by manuelmeister** [comment]
## Meeting Notes

- Umsetzung im ersten Schritt in einem Dialog (Möglichkeit in Zukunft ein spezielle Form dafür verwenden)
- Periods edit wird im Dialog bleiben (für das spätere Hinzufügen, da man so dem Benutzer die Auswirkungen besser "erklären" kann)

**Comment by usu** [comment]
Eventuell mit Stepper?
https://vuetifyjs.com/en/components/steppers/
