### ISSUE TITLE
Docker-Container mit WebServer, PHP und MySql Datenbank

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#311]

**Comment by manuelmeister** [comment]
Auf Mac/Windows ist jeder PHP Code unbrauchbar langsam in Docker (5s pro Sekunde).
Schau mal noch http://docker-sync.io/ an.
http://blog.michaelperrin.fr/2017/04/14/docker-for-mac-on-a-symfony-app/

**Comment by Tschet1** [comment]
Alternativ kann auf OS X die Performance auch mit Caching von Volumes verbessert werden (https://docs.docker.com/docker-for-mac/osxfs-caching/). Ich verwende ein solches Setup für eine PHP Entwicklungsumgebung in Docker.

**Comment by carlobeltrame** [comment]
Danke für die Inputs! Wenn ich das richtig verstehe läuft docker-sync nur mit Ruby (kann jedenfalls nur mit `gem` installiert werden). Ich fände es bizarr, wenn man Ruby (und gem und Make) installiert haben müsste aber nicht PHP und Composer, nur um eine PHP-Applikation laufen zu lassen.

@manuelmeister kannst du testen ob die Performance verbessert wird wenn du in docker-compose.yml auf den Zeilen 10 und 22 `:delegated` oder sogar nur schon `:cached` anhängst? Und ob auf den ersten Blick noch alles weiter funktioniert?

```
    volumes:
      - ./frontend:/app:delegated
...
    volumes:
      - ./backend:/var/www/ecamp3:delegated
```

Edit: Nach der Änderung am besten `docker-compose down && docker-compose up` ausführen, um sicherzugehen dass die Volumes neu erstellt werden.

**Comment by Tschet1** [comment]
Noch bessere Perfomance solltet ihr erhalten, wenn ihr die Volumes so anlegt, dass ihr einen Teil (vendors, php, style, ...) als read-only (:ro) kennzeichnet und log-Ordner als :delegated markiert.
