### ISSUE TITLE
Group-Code still legen  (experimental)

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#312]

**Comment by manuelmeister** [comment]
Um die Komplexität zu reduzieren, soll in der Initial-Version die Gruppen nicht zum Zug kommen, da sie für den Benutzer nicht so relevant ist.

**Comment by usu** [comment]
Die Gruppen haben sich in der Zwischenzeit auch ins Frontend eingeschlichen...

@pmattmann @manuelmeister @carlobeltrame 
Seid ihr auch nach wie vor der Meinung, dass wir für eine erste Version keine Gruppen implementieren? Falls ja, kann ich das grad auf beiden Seiten Backend & Frontend entfernen.

**Comment by carlobeltrame** [comment]
Ja, sehe ich immer noch so
