### ISSUE TITLE
Missing keys on alpha deployment

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#3143]
> Additional defined key(s): "SENTRY_ENVIRONMENT,RECAPTCHA_SITE_KEY" in frontend/public/environment.js   Maybe you forgot to add them here to the requiredKeys

Why are those keys missing on alpha?

**Comment by usu** [comment]
The keys are not missing, they are too much (at least according to the check in index.html).

I fixed this in #3094

**Comment by usu** [comment]
Fixed in #3094
