### ISSUE TITLE
Postgresql Helm chart v10 not supported anymore

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#3213]
v10 was recently removed, so now we cannot defer upgrading any longer:
https://github.com/bitnami/containers/commit/7e633328ace9d3392cc73c4786b2e9b275878ea0

Deployment currently fails:
https://github.com/ecamp/ecamp3/actions/runs/3793920491/jobs/6451505499

**Comment by carlobeltrame** [comment]
Was fixed in #3215, remnants will be cleaned up in #3228
