### ISSUE TITLE
Make reviewing frontend changes of PR's faster

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#3214]
In our team, we found the issue that it takes long to review and access frontend changes someone else made on his fork.
This overlaps a little with the problem to test ecamp on the mobile phone.
Here are some ways one can use to review frontend changes:

- Checkout the changes locally and run the frontend
- Create a feature branch deployment
- Create a Netlify deployment of the frontend (Tried with #3194 )
- Github Codespaces
- GitPod
- Use ngrok (or alternatives) to expose a local environment to others

For mobile phones additionally:
- Connect to the IP of the Laptop when Phone and Laptop are in the same network
- Use an Android Emulator (e.g. with Android Studio)

I opened this Issue that we can share if we tried something to address these issues.

**Comment by BacLuc** [comment]
## Connect to the IP of the Laptop when Phone and Laptop are in the same network
- you can reach the frontend, but localhost:3001 is hard coded as API_ROOT_URL
- Another problem will be the shared-cookie-domain
- The third problem will be the CORS domains
- And in the api trusted_hosts and trusted_proxies
- Nice to have: The domain for the mails we send gets inferred from the request used to generate the mail.

Possible Solutions:
- Add env example how to configure everything for a local IP Address
- Make the API_ROOT_URL and the SHARED_COOKIE domain dynamic, and
  - And loosen the restrictions on CORS, trusted_hosts and trusted_proxies
  - Add an example of how to configure the current ip address that it's usable.
- We hardcode the API_ROOT_URL now, because on the deployment and for local development, the relative path is different. And we may have more differences once we use ngrok.
We could also add a reverse proxy on the frontend, which would assure that the relative path from frontend to backend or print is always the same.

It seems that a reverse proxy for this way is necessary, because mobile browsers take security more seriously:
![grafik](https://user-images.githubusercontent.com/1506818/210018223-ddd60778-0113-45b2-9192-81263ef8dc7a.png)

**Comment by BacLuc** [comment]
## Checkout the changes locally and run the frontend

- You can only do this for one branch at a time, and building the components takes its time

Possible Improvements:
- Speed up time to interactive for the components
- Use reverse proxy to route the requests, that you only need 2 Ports per running instance (one for the applicaiton, one for postgres)

**Comment by BacLuc** [comment]
## Create a feature branch deployment
- We currently can only deploy one feature branch additionally to the dev deployment
- It takes some time to build and deploy the applications

Possible Improvements:
- Get the autoscaling to work on digitalocean
- Add more resources (bigger or more nodes)
- Reduce resource usage that we can have more feature branch deployments
  - Not use the puppeteer inside the cluster
  - Only start the puppeteer when needed.
  @BacLuc tried that. The scaling down worked, but could not get an api up running again. https://github.com/ecamp/ecamp3/pull/3216
  - Add upper resource limits, and restart containers automatically which have memory leaks
- Reduce build time for feature branch deployment

**Comment by BacLuc** [comment]
## Create a Netlify deployment of the frontend
- we can only afford one deployment, if we have this deployment additonally to the dev deployment, no feature branch deployments
- We need to loosen the security to allow the netlify deployments to access the backend
- It's another deployment we need to maintain

Possible Solutions:
- only run the backend container for the netlify deployment. (No frontend, no print, no browserless, no emails)
- Create a frontend build with a mock backend, so we don't have to deploy a real backend?

**Comment by BacLuc** [comment]
## Github Codespaces
- its cool that github now opened codespaces for everyone
- Limited free hours
- It takes 11 minutes to have something up and running
- Prebuilding CodeSpaces seems to be tricky
- You cannot share a codespace after you started it (maybe with plugins in VS Code)
- With the built in code forwarding into the workspace, the frontend does not work yet (Same problem as https://github.com/ecamp/ecamp3/issues/3214#issuecomment-1366923833)
- If you connect your local vscode to the workspace, your local ports are automagically forwarded to the codespace. The frontend may work then, but then you can only have one deployment running at the time
- The default machine (2 Cores, 4 GB of RAM) does not have enough power.

Possible Solutions:
- Reverse Proxy + dynamic API URL

**Comment by BacLuc** [comment]
## Gitpod
- Similar to Github Codespace
- works already well for another project from work (https://github.com/scs/jumpstart-docs), see it in action here: (https://gitpod.io/#https://github.com/scs/jumpstart-docs)
One click and you have a Java IDE (ok, not quite IDE, but ok) plus the setup for cmake and pandoc running.
- Getting the prebuild workspaces to work was not easy, but i know some parts now.
- You can connect with Jetbrains Gateway into it if you want to use PHPStorm, but it has quite a lag.
- It does not use devcontainers, but has its own system of configuring VS Code, so not 2 in one if we want to simplify debugging config etc for new VSCode people
- It does not use userid 1000 in the container, i tried it once for ecamp and it did not work at all (Did not get the containers to start properly)

**Comment by BacLuc** [comment]
@manuelmeister and @usu 
Is this resolved?

**Comment by manuelmeister** [comment]
I think. Further improvements could require much more work or resources.

**Comment by usu** [comment]
A low hanging fruit would be to try switching feature-branch deployments from cron-job to immediate deployment. That would avoid the need of manual triggers to see a recent change to a PR. Can volunteer for this.
