### ISSUE TITLE
(Wunsch) Doppeltes Material

### ISSUE THREAD

**Issue by ensolo** [ecamp/ecamp3#323]
Wenn man bei eCamp v.2 zB. bei 3 Blöcken die selbe Verkleidung braucht und diese bei jedem Block in die Material Liste schreibt, wird diese 3 mal angezeigt. Es bräuchte unbedingt eine Funktion, dass man Material wählen kann, welches sich schon auf der Material Liste befindet.

**Comment by carlobeltrame** [comment]
Das Thema Materiallisten wird hier weiter spezifiziert: #574
Ich schliesse daher dieses Issue.
