### ISSUE TITLE
Beta Deployment

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#3232]
- Same as Alpha
- Performance should be defined
- New kubernetes cluster
- app.ecamp3.ch (with Beta label)
  - We need to register the callback urls (and maybe separate clientId's and secrets for oauth)
     - [x] https://api.ecamp3.ch/auth/pbsmidata/callback,  https://app.ecamp3.ch/api/auth/pbsmidata/callback
     https://api-staging.ecamp3.ch/auth/pbsmidata/callback,  https://staging.ecamp3.ch/api/auth/pbsmidata/callback
     https://alpha.ecamp3.ch/api/auth/pbsmidata/callback
        - [x] At Google (@BacLuc ) can do that while deploying
        - [x] At db.scout.ch
        - [x] At db.jubla.ch
        - [x] At db.cevi.ch

> **Note**
> Alpha will become Prod

**Comment by BacLuc** [comment]
We could also reuse the cluster used for alpha (we don't need the alpha anymore)
And add a staging cluster.
(Or just deploy a staging environment to the dev cluster)

**Comment by pmattmann** [comment]
- [x] #3262 merged
- [x] #3265 merged
- [x] update databases to v15 (@pmattmann  und @usu)
- [x] update alpha (test new deploy-script)
  - [ ] Prod-Setup (Performance-Settings) #3306
- [x] Setup Infrastructure (Cluster mit je Kubernetes & DB: 1x Prod / 1x Stage / 1x Dev)
  - [x] Alpha -> Prod
  - [x] ( Stage neu )
- [x] Cloudeflare setup app.ecamp3.ch 
- [x] ReCaptcha Config nötig?
- [x] Setup Prometheus + Grafana (install digitalocean)
- [ ] Review Seed-Data
  - [x] support@ecamp3.ch change password
  - [x] register personal admin-accounts
- [x] write blog-post https://github.com/ecamp/ecamp-site/pull/13
- [ ] testing
- [x] write invite Mail

**Comment by pmattmann** [comment]
reCAPTCHA ist für ganze Domain gültig.  Wir haben also die Wahl, ob belassen, oder ein eigenes einrichten:
![image](https://user-images.githubusercontent.com/470237/221274627-1c024e1a-2b8b-4bbb-8c7d-e3add350f675.png)

**Comment by carlobeltrame** [comment]
Beta Deployment is complete, the first batch of coupon codes has been sent out.
