### ISSUE TITLE
Docker & xdebug auf MacOs

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#327]
Auf meinem Mac funktioniert das xdebugging nicht. Mit Änderungen an den Einstellungen kann ich es höchstens dazu bringen dass es auf der ersten Zeile hält. Wenn es danach resumed wird, hält es nicht am nächsten Breakpoint.

**Comment by carlobeltrame** [comment]
On hold, @manuelmeister verwendet momentan nicht mehr den Docker-Setup. Auf Ubuntu funktioniert XDebug in Docker.
