### ISSUE TITLE
Conflict between pinned caddy version and caddy plugins

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#3272]
Our builds are currently failing, because there is a conflict between the pinned caddy version (2.6.3) and the latest mercure plugin (0.14.5) which requires caddy 2.6.4.

Example:
https://github.com/ecamp/ecamp3/actions/runs/4215397599/jobs/7316509043

**Potential solution options:**
A. Pin caddy plugins
B. Unpin exact caddy version (this is the option [chosen by the api-platform template](https://github.com/api-platform/api-platform/compare/d059b22b4e3b4e2a6e30d7ca3c2921145a367e3f...7642f8639ff1d95cfa48832db0221973559f8d29#diff-21ee93e31c9cec7a5f33b680622da377c451b62b6c44eac6d9550eade41beb47R97))
C. Remove/disable caddy plugins from build (we don't use any mercure/vulcain functionality at the moment anyway)

**Comment by BacLuc** [comment]
Could this problem be solved again with https://github.com/ecamp/ecamp3/commit/985bf822249d2a3a65f90b2dd3193547dcef9d87 and we just need to rebase the PR's?

**Comment by usu** [comment]
Yes, https://github.com/ecamp/ecamp3/commit/985bf822249d2a3a65f90b2dd3193547dcef9d87 is the quickfix and once we rebase the other branches, they should work.

...until the next caddy version update 😄
So probably still makes sense to solve this a bit more sustainably.
