### ISSUE TITLE
(Wunsch) Vorhandenes Material als Liste

### ISSUE THREAD

**Issue by ensolo** [ecamp/ecamp3#328]
Um das Lagermaterial vor dem Lager aus dem Lokal zusammen zu suchen braucht man auch das vorhandene Material als Liste! Bei eCamp v2 kann jedoch nur das  zu organisierende Material als Liste angezeigt werden.

**Comment by carlobeltrame** [comment]
Das Thema Materiallisten wird hier weiter spezifiziert: https://github.com/ecamp/ecamp3/discussions/574
Ich schliesse daher dieses Issue.
