### ISSUE TITLE
Feature to secure stage against unauthorized access

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#3288]
Stage data should be regularly replicated from prod data, to be as close as possible on real data

We would need a possibility to safeguard the stage environment, such that unauthorized people cannot access the stage environment.

To be evaluated, if securing API is sufficient or whether we need to secure the frontend as well.

**Comment by usu** [comment]
### Option 1: Configure HTTP Basic Authentication in Ingress Controller
https://kubernetes.github.io/ingress-nginx/examples/auth/basic/
https://www.howtogeek.com/devops/how-to-add-http-basic-authentication-to-a-kubernetes-nginx-ingress/

### Option 2: Secure API on application level
E.g. code a feature, which requires an additional cookie (=api key) in order to use the API.
Other services would remain open.

**Comment by usu** [comment]
One drawback of option 1 is that OAuth will stop working.

**Comment by carlobeltrame** [comment]
Are you sure? The redirects should continue working, and the backchannel request is initiated by our backend, so http basic authentication should not apply there.

**Comment by BacLuc** [comment]
I will start with Option 1
