### ISSUE TITLE
API Proxy & Volle Entitäten Lazyload

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#329]

**Comment by pmattmann** [comment]
@usu: 
Habe für Proxy-Entity zwei Varianten geprüft. 

V1 - Proxy-Flag:
```json
{
  "proxy": true,
  "id": "21d77e2a",
  "_links": {
    "self": {
      "href": "http://localhost:8888/api/event-type/21d77e2a"
    }
  }
}
```

V2 - Ohne ID:
```json
{
  "_links": {
    "self": {
      "href": "http://localhost:8888/api/event-type/21d77e2a"
    }
  }
}
```

Beide funktionieren gut - sowohl für Entity-Referenzen als auch für Embedded Collections.
Bei Embedded Collections werden natürlich sämtliche Element als Entity-Referenzen übermittelt.

Collection als Referenz hab ich noch nicht.
