### ISSUE TITLE
Invitation not visible

### ISSUE THREAD

**Issue by loelismurf** [ecamp/ecamp3#3329]
The invitation to a camp is not visible after login or in any menu.

The camp could be joined via the email without any problem.

maybe it is also a feature and not an issue

**Comment by carlobeltrame** [comment]
"It's a feature, not a bug."
Invitations are not bound to a specific user account. If you open the invitation link, you are offered the option to accept the invitation with your currently logged in account, or switch to a different account and accept the invitation there. In the meantime, the invitation acts as a placeholder collaborator in the camp, and your fellow camp leaders can already assign responsibilities and material to the invited collaborator, even before the invitation is accepted.
For the same reason, you aren't offered a user search field when inviting your team. You can't invite specific user accounts, you can only invite email addresses.
