### ISSUE TITLE
Display error on the detailed plan

### ISSUE THREAD

**Issue by loelismurf** [ecamp/ecamp3#3330]
On a stock activity (Lageraktivität) the material button is not scaled correctly.

Windows 10 test system
Browser: Chrome version 111.0.5563.64
Screen: 5120x1440 (scaling 125%)
Browser window: 2560x1440
see picture in attachment
![issueDetailedPlan](https://user-images.githubusercontent.com/77551562/223769497-12dd6007-b622-4ed2-b8a4-67e9488d6696.png)

**Comment by carlobeltrame** [comment]
Thanks! PR #3303 already contains a fix for this issue. You can help us out by visiting https://pr3303.ecamp3.ch and testing whether it is really fixed there. (You will need to use the default account `test@example.com` / `test`, or register, ~~or use an account from the MiData test environment or similar~~. Login via MiData etc. doesn't work on these feature preview test versions. If you have to register, any emails sent out by this test version of ecamp are collected at https://pr3303.ecamp3.ch/mail)

EDIT: By now, the PR is merged, and the fix should be available on https://dev.ecamp3.ch. Cheers!
