### ISSUE TITLE
Leere URIs in Store ermöglichen

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#337]

**Comment by carlobeltrame** [comment]
Ich habe einen Bug in hal-json-normalizer [gefixt](https://github.com/carlobeltrame/hal-json-normalizer/blob/master/CHANGELOG.md) (ab jetzt ^1.0.3 verwenden), und die Änderungen vom Meeting gestern noch etwas verbessert und in meinen Branch aufgenommen.
Wir sind aber schon zu weit von devel entfernt, als dass ich den Fix isoliert in einen normalen PR umsetzen könnte. Um die Änderungen also auf andere Branches zu übernehmen, entweder
```
git merge carlobeltrame:update-hal-json-normalizer # branch mit dem dependency update
git cherry-pick cc5f8cdd7ae633c56dbe048830982c42470a30d5 # commit mit changes aus Meeting
```
oder einfach `git rebase carlobeltrame:vuex-hal-write-operations`.

Dieses Issue wird somit gefixt sein, sobald mein Branch `vuex-hal-write-operations` gemerged ist, also mit #309.
