### ISSUE TITLE
Copy Block Feature

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#3376]
Currently only for the same camp (but soon will be needed to copy blocks from one camp to another)

Occurrence counter: 3

**Comment by carlobeltrame** [comment]
Open questions which need to be resolved for this feature:

### Copying within the same camp
- Are material items also copied? (is easily doable)
- Are responsibilities also copied? (is easily doable)
- Could many of the use cases also be covered by making the category preset feature more easy to discover and understand?

### Copying across camps
- Which category does the copied block get? It's not possible to automatically choose the correct category in the target camp. On the other hand, categories have less influence on the block than in eCamp v2
- Are material items also copied? If so, into which material lists? Do material lists also have to be copied?
- Are responsibilities also copied? If so, what about responsibilities of people which are not part of the new camp?

In general, once we allow copying blocks, every single content node will have to define how it can be copied to a different camp.
Also, this feature might encourage the re-use of any deprecated content nodes (e.g. if we ever replace the recommended content node for security concepts with a new one).

**Comment by BacLuc** [comment]
Similar to #3536

**Comment by pmattmann** [comment]
Idea:

- Copy Frontend-ScheduleEntry URL to clipboard;
  - [x] ScheduleEntry upper right corner
  - [x] Activity-View Menu upper right corner

- Paste copied Activity on Picasso
  - [ ] Add Activity Dialog recognize URL in Clipboard
  - [ ] If URL is a readable ScheduleEntry; Allow Option 'Copy Content from Activity'
  - [ ] Add Option 'Clear Clipboard'

**Comment by carlobeltrame** [comment]
Implemented in #3993
