### ISSUE TITLE
Vue Filter für Default-Wert bevor Resultat aus der API verfügbar ist

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#339]
So lange Daten aus der API noch nicht geladen sind, müssen wir eine Alternative im UI anzeigen können.

Siehe https://vuejs.org/v2/guide/filters.html
Name ist noch zu diskutieren. `default` ist ein reserved word in JS. Vorschläge sind:
```
{{ user.username | loading('Profile')  }}
{{ user.username | fallback('Profile')  }}
{{ user.username | placeholder('Profile')  }}
{{ user.username | or('Profile')  }}
```

**Comment by manuelmeister** [comment]
Ich würde eher `fallback`,  `placeholder`  oder am Besten **`loading`** nehmen.
Weil `|` und `or` bedeuted das gleiche. Ich finde der Code soll sprechend sein und das was es effektiv macht, ist einen Wert während dem Laden anzeigen.

**Comment by carlobeltrame** [comment]
Das stimmt, aber das `|` ist in diesem Kontext eigentlich nicht als OR, sondern als pipe zu verstehen, wie das in Shells üblich ist. Ich habe mal die Description angepasst, bin noch von keinem Vorschlag zu 100% überzeugt.

**Comment by manuelmeister** [comment]
### Meeting Discuss
Wir lösen das mit Vuetify Skeleton loaders.
