### ISSUE TITLE
Possibility to reset data of dev.ecamp3.ch deployment

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#3397]
The camps on dev are not accessible anymore (maybe deleted), and the test user now has the scout name h4545
@ecamp/core vote here with :+1:  if we should truncate the dev database and let the script migrate the development test data again.

**Comment by manuelmeister** [comment]
Should we make this now as a routine? This way, we also take care to keep the fixtures up to date.

**Comment by BacLuc** [comment]
Database was reinitialized with the dev data migrations of #3436 and #3454.
Maybe we should still have a way to reset the data on the dev deployment.

**Comment by BacLuc** [comment]
Will be possible with #3640
