### ISSUE TITLE
ACL Berechtigungen

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#342]
## Backend
- Embedded Entities
  - Berechtigung zum Parent aber nicht zu den Children
     => jede Umsetzung ist erlaubt, wenn sie die Daten nicht freigibt (Optimalfall: weder als Link noch als Embedded hinzufügen)
- Embedded Collection
  - Berechtigung zum Parent aber nicht zu den Children 
   => leere Liste
- Nicht alle Entitäten sehen => Selektion
- Nicht alle Felder anzeigen => Projektion 
  Grundsätzlich erlaubt, beim Benutzer lösen wir dieses Problem mit zwei Endpunkten oder mit zwei Entitäten
   ### Öffentliche Infos
  - Profilfoto
  - Benutzername
  - => Referenz auf Vertrauliche Infos
  
  ### Vertrauliche Infos
  - Voller Name
  - E-Mail
  - …

## Frontend
- Wie weiss ich, welche Berechtigungen dass ich habe?
  - Authentifizierte Rolle im Kontext Gesamtsystem auf `/api`
    - Gast / Anonym
    - Benutzer
    - Admin
  - Rolle im Camp-Kontext auf `/api/camp/[id]`
    - Unbeteiligt
    - Gast (read-only)
    - Member
    - Manager
    - *(Reviewer)*
  - Rolle im Benutzerkontext auf `/api/user/[id]`
    - Unrelated
    - Known
    - Me
- ~~Wie ist die Projektion? (Promises, Leer, ****, …)~~

**Comment by usu** [comment]
lst-Zustand (bei #418 darüber gestolpert): Im Moment macht die ACL gar nix (alle dürfen alles).

https://github.com/ecamp/ecamp3/blob/c8beb1865007d5e1abc25d6b048dada51ce7f86b/backend/module/eCampCore/src/Acl/AclFactory.php#L107-L108
