### ISSUE TITLE
PR Deployment Failed because of Collation mismatch

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#3434]
```
WARNING:  database "postgres" has a collation version mismatch
DETAIL:  The database was created using collation version 2.34, but the operating system provides version 2.36.
HINT:  Rebuild all objects in this database that use the default collation and run ALTER DATABASE postgres REFRESH COLLATION VERSION, or build PostgreSQL with the right library version.
Could not create database "ecamp3pr3432" for connection named default
An exception occurred while executing a query: SQLSTATE[XX000]: Internal error: 7 ERROR:  template database "template1" has a collation version mismatch
DETAIL:  The template database was created using collation version 2.34, but the operating system provides version 2.36.
HINT:  Rebuild all objects in the template database that use the default collation and run ALTER DATABASE template1 REFRESH COLLATION VERSION, or build PostgreSQL with the right library version.
```

**Comment by usu** [comment]
Was reading through this:
https://dba.stackexchange.com/questions/324649/collation-version-mismatch
https://www.cybertec-postgresql.com/en/icu-collations-against-postgresql-data-corruption/
https://pgpedia.info/p/pg_database_collation_actual_version.html

Not sure I understand the concept of collations fully.

I was able to resolve the first part of the error by running the following queries on the dev database (not really sure the first part is needed):
```
REINDEX DATABASE postgres;
ALTER DATABASE postgres REFRESH COLLATION VERSION;
```

The second part of the error message I'm not able to resolve.
```
ALTER DATABASE template1 REFRESH COLLATION VERSION
```
results in `ERROR:  must be owner of database template1`. The owner is the postgres superuser, which I don't know how to get access to.

I'm inclined to remove the dev database and recreate it. Any objections?

**Comment by BacLuc** [comment]
Just a reminder: then you run into the problem that you don't have permission to create a new database with the doadmin user.
I don't remember how we fixed this on staging and prod.
I would first remove all pr deployments, then recreate the database, and then recreate the dev deployment.
(And you need to change the secrets in the dev environment)
The people who need PR deployments will readd them later.
But no problem for me

**Comment by usu** [comment]
I've opened a ticket with DigitalOcean. Chances are high, this will happen again with a future update of the DB server. Kind of want to avoid, the only solution is the completely reset the complete DB server.

**Comment by usu** [comment]
Feature deployments should work now again. I will document the learnings here, once the support ticket with DigitalOcean has fully concluded.

**Comment by BacLuc** [comment]
Did digitalocean get back to you @usu?

**Comment by usu** [comment]
In summary they responded, that they implemented and rolled out a patch that should prevent this. I'm not entirely sure, whether this was a patch on Posgres itself or a patch on their deployment setup. But eventually, the problem was gone.

I'd suggest we close this and can refer to this issue, in case something similar happens again.
