### ISSUE TITLE
Migration auf Vuetify

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#344]
Hey Jungs,

ich werde mit Bootstrap-Vue irgendwo nicht so richtig warm. Können wir die Diskussion bootstrap-vue vs. vuetify nochmals aufgreifen, oder ist für euch der Zug schon abgefahren?

Ich sehe einige Vorteile bei Vuetify:
- Viel grössere Anzahl Komponenten und Entwicklungsspeed: Date/Time-Picker, Avatar, vollständige vorprogrammierte Kalender/Picasso-Ansicht, etc.
- Form Inputs deutlich mächtiger mit Placeholder, Validations, Transitions, etc.
- Moderneres/modulareres Interface. Viele Komponenten arbeiten mit Slots, bei bootstrap-vue fast keine.
- Strukturiere/einheitliche Doku. Für jede Komponente gibt es eine einheitliche und suchbare API-Beschreibung mit props, slots, events und functions.
- Die meisten Komponenten sehen out of the box besser aus mit einem intuitiven UI.

Klar es ist halt Material Design und heavy opinionated. Aber ich denke, dass ist auch ein Vorteil da wir weniger Zeit verlieren uns abzugleichen wie etwas funktionieren/aussehen soll, da der Standard schon von Vuetify vorgegeben ist.

Ich weiss, es ist doof nach Start zu wechseln. Aber so viel Frontend-Code haben wir ja noch nicht, da müsste sich der Aufwand in Grenzen halten. Ich würde mich als Gegenleistung anbieten, die Migration zu übernehmen :smiley:

@pmattmann @manuelmeister @carlobeltrame Was meint ihr?

**Comment by carlobeltrame** [comment]
Ich finde persönlich Material Design einfach visuell viel weniger schön als Bootstrap (oder noch besser Bulma), mit Material assoziiere ich endlose unübersichtliche und verschachtelte UIs der Google-(Cloud-)Apps. Aber ich sehe ein dass Vuetify technisch gesehen die Nase vorn hat. Darum wäre eine Migration zu Vuetify schon eine Option für mich.

**Comment by manuelmeister** [comment]
Mir geht es gleich wie @carlobeltrame. Mir gefällt der Look von Material nicht, sehe aber den Vorteil dass wir schneller zu einem guten Resultat kommen.

**Comment by manuelmeister** [comment]
### Meeting Notes

Wir entscheiden uns für Vuetify, da es uns ermöglicht schnell und gut mit der Frontend-Entwicklung zu starten.
