### ISSUE TITLE
Store-URI in der Route

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#345]
Wir haben ja die Store-URIs als Teil der Route (Camp, Event, etc.).

Auf der einen Seite konsquent, da wir nur mit URIs hantieren. Auf der anderen Seite gibt es für den Benutzer halt keine schönen/cleanen URLs.

**Comment by manuelmeister** [comment]
### Meeting Notes 
/entität/**id**/_beliebigerName_[/view]
/camps/**f0r13**/_Sola2020_/picasso
#### URL Beispiele:

führt zum Camp:
```
/camps/81e953ac
/camps/81e953ac/Sola2020
/camps/81e953ac/blabalbalba
/camps/81e953ac/picasso
```
führt zum Picasso:
```
/camps/81e953ac/Sola2020/picasso
/camps/81e953ac/blblalsd/picasso
/camps/81e953ac/picasso/picasso
/camps/81e953ac/_/picasso
```
führt zur Eventinstanz:
```
/camps/81e953ac/Sola2020/event/d61fe752
/camps/81e953ac/Sola2020/event/d61fe752/la-seilbruecke
/camps/81e953ac/Sola2020/event/d61fe752/la-seilbruecke/edit
```

**Comment by manuelmeister** [comment]
Übersetzung von ID in URI des camps wird fix ins Frontend einprogrammiert für ein paar wenige Ausnahmen
