### ISSUE TITLE
Drag and drop bug on picasso

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#3463]
When dragging new schedule entries onto the picasso, under some yet unknown conditions, sometimes the release is not triggered, and the gray placeholder schedule entry gets stuck to the mouse pointer permanently:

[Bildschirmaufzeichnung vom 2023-05-15, 22-30-03 (getrimmt).webm](https://github.com/ecamp/ecamp3/assets/7566995/4b6bef4a-af7a-492a-867f-78067ddbedf9)

The bug has several, progressively worse stages. Timeline of the above video:
0:03 - 0:11 stage 1
0:12 - 0:32 stage 2
0:33 - 0:44 back in stage 1
0:44 user refreshes the page to get rid of the bug
(Stage 3 is never reached in this video, see below for a video of that)

### Stage 1: Canceling the dialog
I was able to reproduce this by double-clicking on the draggable picasso surface, while moving the mouse pointer enough in vertical direction between the two clicks. It has to be at least enough movement such that a minimal length schedule entry is created (i.e. **in very short succession: click, drag a little bit, click**):
[picasso-dragging-bug-1.webm](https://github.com/ecamp/ecamp3/assets/7566995/88c968b6-f131-4eaa-9171-8a223ac9f092)

### Stage 2: Getting the schedule entry end stuck to the cursor
Once a user is in stage 1, they might try to get rid of the gray placeholder and/or re-trigger the dialog, by dragging the length handle of the placeholder. This makes matters worse, because now, the end of the schedule entry is stuck to the mouse cursor, until the user clicks again, getting back to stage 1.
In some cases, we can also get directly to stage 2, when the second click of the reproduction above accidentally grabs and moves the length handle of the placeholder schedule entry.
[picasso-dragging-bug-2.webm](https://github.com/ecamp/ecamp3/assets/7566995/b669daa0-e703-4a5c-8553-8370d8b1e350)

### Stage 3: Getting the entire schedule entry stuck to the cursor
While in stage 1, if the user tries to move the placeholder schedule entry by dragging its body, the placeholder gets stuck permanently to the mouse cursor. I have found no way to get out of this situation, except for refreshing the page. In this stage, if the user tries to save the schedule entry, we get a console error `g._meta is undefined` or `Cannot read properties of undefined (reading 'self')` or `undefined is not an object (evaluating 'g._meta.self')` in the ScheduleEntries.vue component. These are collected in a [Sentry issue](https://ecamp.sentry.io/issues/4004671918/?project=5602507).
[picasso-dragging-bug-3.webm](https://github.com/ecamp/ecamp3/assets/7566995/59648ba8-4b8a-46ec-b019-b3b9eceabc06)

**Comment by usu** [comment]
Do you know if this is specific to one browser (Firefox?) or were you able to reproduce in other browsers as well?

**Comment by carlobeltrame** [comment]
The Sentry issue shows occurrences in Firefox, Safari, Edge, Chrome and Opera. It's definitely not browser-specific.
But there is one upside: It does not happen on mobile, because there we don't allow dragging new schedule entries into the picasso :P

**Comment by usu** [comment]
As far as I could debug, the issue is reproducible when creating a new entry with length 0. One method is as described above by @carlobeltrame (small move only). Another method is to drag a new entry and then moving the cursor back to it's origin (while keeping the drag & drop active).

Code line https://github.com/ecamp/ecamp3/blob/devel/frontend/src/components/program/picasso/useDragAndDropNew.js#L109 triggers opening of the event creation dialog only if endTimestamp > startTimestamp. If they are equal, the state in `useDragAndDrop.js` is cleared, but the placeholder in the upper layer is still active. Hence resulting in the observed behaviour.

Placeholders of length 0 should actually not even exist, but we messed up the math... 📐 

Working on a fix.
