### ISSUE TITLE
Additional Backup

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#3478]
## Idea

To have an additional safety layer, we want to store a backup of the production database at least in another datacenter.

## Design

- [x] Create a cronjob in kubernetes which backups the postgres db, encrypts it and stores it in a storage solution.
- [x] Retention for old backups
- [x] Add a github action to restore that backup to an environment (uninstall deployment, restore backup, install deployment again)
- [ ] Run this github action eventually regularly to restore the prod data in staging

## Storage Solutions

An s3 compatible storage seems feasible because many storage providers offer s3 compatible api.

Variants:

1. Amazon S3 
Cost for 100 GB Storage plus a little traffic: 62$ /year
https://calculator.aws/#/estimate?id=aaea3cc1b930c108ae589c4cde76d4a7110e6f4e
- :+1:  Allows to create multiple Access Keys with different permissions
- :+1: Allows to configure Lifecycle management

2. CloudFlare R2
20$ / year
(100 GB, 30 write, 30 reads, 36% egress)
https://r2-calculator.cloudflare.com/
- :question:  Allows to create multiple Access Keys with different permissions. Maybe there is no separate delete permission. Upload and delete may be coupled. https://developers.cloudflare.com/r2/api/s3/tokens/
- :+1: Allows to configure Lifecycle management https://developers.cloudflare.com/r2/buckets/object-lifecycles/

3. DigitalOcean Spaces
In another datacenter, e.g. Amsterdam
60$ / year
[DigitalOcean Pricing Calculator Estimate.csv](https://github.com/ecamp/ecamp3/files/11524588/DigitalOcean.Pricing.Calculator.Estimate.csv)
- :x:  Allows to create multiple Access Keys with different permissions (no)
- :+1:  Allows to configure Lifecycle management https://www.howtogeek.com/devops/how-to-set-an-expiration-policy-on-digitalocean-spaces-buckets/

Other options: https://www.qualeed.com/en/qbackup/cloud-storage-comparison/

**Comment by usu** [comment]
Generally agree to the design. A few additional comments we could consider curing the discussion.

<br />

> Create a cronjob in kubernetes which backups the postgres db, encrypts it and stores it in a storage solution.

The cron job should only have permission to put new objects into the S3 storage (`PutObject` permission).

<br />

> Retention for old backups

On Digitalocean we have 7 days of backup directly from the managed DB. I'd vote for a weekly backup, maybe for the last 3-4 months?
If we want to cleanup old backups automatically, I'd be very carful with this: This cronjob would need delete permission (`DeleteObject`) on S3 and this is not really a permission level I'd want to have have directly in the Kubernetes cluster. Just in worst case, if someone is able to hack in our Kubernetes cluster and gets access to the secrets, they should at least not be able to delete the backups as well.
Alternatively, I'd we also be fine with a shell script, that is run manually from a developer's machine from time to time.

<br />

> Run this github action eventually regularly to restore the prod data in staging

Ideally, we should allow this only, if the staging points to the same commit as prod.
- Otherwise, staging might fail to run, because the DB is on the different version than the source code
- And, more importantly, we might miss to test some migrations properly on staging before we deploy to prod

Does this make sense or is this overly careful?

**Comment by BacLuc** [comment]
> The cron job should only have permission to put new objects into the S3 storage (`PutObject` permission).

Then we should consider this when choosing the provider.
In digitalocean i did not see this option.

 
> On Digitalocean we have 7 days of backup directly from the managed DB. I'd vote for a weekly backup, maybe for the last 3-4 months? If we want to cleanup old backups automatically, I'd be very carful with this: This cronjob would need delete permission (`DeleteObject`) on S3 and this is not really a permission level I'd want to have have directly in the Kubernetes cluster. Just in worst case, if someone is able to hack in our Kubernetes cluster and gets access to the secrets, they should at least not be able to delete the backups as well. Alternatively, I'd we also be fine with a shell script, that is run manually from a developer's machine from time to time.

This is very careful but good.
We should consider this when choosing a provider.
I hoped that you can configure a retention policy (And not implement that ourselves), but did not see this on digitalocean. https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lifecycle-mgmt.html

> > Run this github action eventually regularly to restore the prod data in staging
> 
> Ideally, we should allow this only, if the staging points to the same commit as prod.
> 
>     * Otherwise, staging might fail to run, because the DB is on the different version than the source code
> 
>     * And, more importantly, we might miss to test some migrations properly on staging before we deploy to prod
> 
> 

This should be no problem, because then the newer version on stage would just apply the missing migrations.
It may be a problem when we have hotfixes applied on prod and switch back to normal deployment on stage.
But we should have merged the hotfixes on devel by then.
If all the migrations are applied in one go or incrementally should not change the outcome and in my opinion does not test so much more than we have to consider this.

**Comment by manuelmeister** [comment]
# Core Meeting Decision

We would love to have only two different providers. Besides digitalocean this is already cloudflare. If cloudflare has no possibilities for write-only access keys we prefer AWS.

**Comment by BacLuc** [comment]
# Test plan

To be executed on the https://github.com/BacLuc/ecamp3 repository
with commit https://github.com/BacLuc/ecamp3/commit/e8ccd4c174a01d68f431fd72f9a7278f7df5d8cf
dev cannot be tested, because it conflicts with the dev deployment of the ecamp3 repository.
And it is more or less anyway the same as the feature-branch deployment
:white_check_mark:
:x:
When no AWS Keys are configured
- Then the deployment does the same as previously
  - on feature-branch :white_check_mark:
  - on staging :white_check_mark:
  - on prod :white_check_mark:

When the AWS Keys for the backup and a backup_schedule are configured
 - Then a backup job is scheduled
   - on feature-branch :white_check_mark:
   - on staging :white_check_mark:
   - on prod :white_check_mark:

When no restore secrets are configured
  - then the restore action fails
    - on feature-branch :white_check_mark: https://github.com/BacLuc/ecamp3/actions/runs/6160064575/job/16716183028
    - on staging :white_check_mark: https://github.com/BacLuc/ecamp3/actions/runs/6160072417/job/16716219930
    - on prod :white_check_mark: https://github.com/BacLuc/ecamp3/actions/runs/6160069401

When restore secrets are configured
  - then the restore action succeeds with the parameter latest
    - on feature-branch :white_check_mark:
    - on staging :white_check_mark: https://github.com/BacLuc/ecamp3/actions/runs/6160486330/job/16717715298
    - on prod :white_check_mark: https://github.com/BacLuc/ecamp3/actions/runs/6160486330/job/16717715298

When restore secrets are configured
  - then the restore action succeeds with a specific backup
    - on feature-branch :white_check_mark: https://github.com/BacLuc/ecamp3/actions/runs/6160480647/job/16717752635
    - on staging :white_check_mark: https://github.com/BacLuc/ecamp3/actions/runs/6160357064/job/16717161443

When RESTORE_INVITE_TO_INTERESTING_CAMPS is set to false
  - then the support account is not invited into the camps
    - on feature-branch  :white_check_mark:
    - on prod :white_check_mark:

When RESTORE_INVITE_TO_INTERESTING_CAMPS is set to true
  - then the support account is invited into the camps
    - on staging :white_check_mark:
