### ISSUE TITLE
e2e tests not running on macOS

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#3511]
I tried to run the end to end tests on macOS (13.4). However, couldn't get the connection to X11 working. Anyone able to reproduce?

Followed the steps documented in https://github.com/ecamp/ecamp3/blob/devel/e2e/README.md (Option A)

1. install xquartz + restart
2. run `xhost local:root`
3. run `docker compose --profile e2e run --entrypoint "cypress open --project ." e2e`

Result:
```
Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

[17:0611/131157.912810:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY
[17:0611/131157.912948:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
The futex facility returned an unexpected error code.

----------

Platform: linux-arm64 (Debian - 11.6)
Cypress Version: 12.13.0

```

**Comment by carlobeltrame** [comment]
Do you havea `$DISPLAY` env variable on your host system? Can you post the output of `echo $DISPLAY` (in a terminal on your host) here? We pass this variable into the e2e container. On my Linux machine, this variable contains the value `:0`.
Do you start the docker-compose using a terminal or using a docker gui? If gui, how does docker for mac work, does it use a linux VM as the actual host? Is the variable set in that VM as well?

**Comment by usu** [comment]
> Do you havea `$DISPLAY` env variable on your host system? Can you post the output of `echo $DISPLAY` (in a terminal on your host) here?

```
$ echo $DISPLAY
/private/tmp/com.apple.launchd.LC9w4jAxXf/org.xquartz:0
$ xhost local:root
non-network local connections being added to access control list
$ xhost
access control enabled, only authorized clients can connect
LOCAL:
``` 

> Do you start the docker-compose using a terminal or using a docker gui?

Directly from terminal

> On my Linux machine, this variable contains the value `:0`.

I tried setting DISPLAY to :0. Same error message when starting e2e-tests.

**Comment by usu** [comment]
I found the following guide: https://www.cypress.io/blog/2019/05/02/run-cypress-with-a-single-docker-command/#Interactive-mode

This worked for me (at least somewhat) 😃
 
```
$ IP=$(ipconfig getifaddr en0)
$ /usr/X11/bin/xhost + $IP
192.168.30.218 being added to access control list
$ DISPLAY=$IP:0
$ docker compose --profile e2e run --entrypoint "cypress open --project ." e2e
```

After this, cypress GUI opens successfully.

Also tried 127.0.0.1 or localhost, both didn't work.

Confusingly, in the GUI, I see only Electron as on option, no Firefox and no Chrome.

Even when running headless, I get the following:

```
$ docker compose --profile e2e run --rm e2e --browser chrome

Can't run because you've entered an invalid browser name.

Browser: chrome was not found on your system or is not supported by Cypress.

Cypress supports the following browsers:
 - electron
 - chrome
 - chromium
 - chrome:canary
 - edge
 - firefox

You can also use a custom browser: https://on.cypress.io/customize-browsers

Available browsers found on your system are:
 - electron
Can't run because you've entered an invalid browser name.

Browser: chrome was not found on your system or is not supported by Cypress.

Cypress supports the following browsers:
 - electron
 - chrome
 - chromium
 - chrome:canary
 - edge
 - firefox

You can also use a custom browser: https://on.cypress.io/customize-browsers

Available browsers found on your system are:
 - electron
```
