### ISSUE TITLE
Improve checkbox saving success indicator

### ISSUE THREAD

**Issue by lstoffer** [ecamp/ecamp3#3513]
Wenn man im LA Themenbereich einen der Haken setzt kommt es zu einer unschönen Überlagerung des grünen Speichersymbols und dem Haken selbst.

<img width="260" alt="la_themenbereich" src="https://github.com/ecamp/ecamp3/assets/56252793/e630fada-cc07-4722-80cb-45739427499a">

**Comment by manuelmeister** [comment]
Danke! Das ist noch in der Designpipeline. Da wird bald noch ein genaueres Design-Konzept für die ganze Autosave Geschichte herausgearbeitet.

**Comment by manuelmeister** [comment]
Duplicate of #894
