### ISSUE TITLE
ecamp3-api-caddy - invalid transport: open /data/mercure.db: permission denied

### ISSUE THREAD

**Issue by pittfischer** [ecamp/ecamp3#3518]
Hello,

When I do "docker compose up ", I get the following error messages:

ecamp3-print                  | npm ERR! If you believe this might be a permissions issue, please double-check the
ecamp3-print                  | npm ERR! permissions of the file and its containing directories, or try running
ecamp3-print                  | npm ERR! the command again as root/Administrator.
ecamp3-print                  |
ecamp3-print                  | npm ERR! Log files were not written due to an error writing to the directory: /home/node/.npm/_logs
ecamp3-print                  | npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal
ecamp3-api-caddy              | {"level":"info","ts":1686832002.9203374,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
ecamp3-api-caddy              | {"level":"info","ts":1686832002.9523077,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
ecamp3-api-caddy              | {"level":"info","ts":1686832002.9537938,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc00065f1f0"}
ecamp3-api-caddy              | {"level":"info","ts":1686832002.9545877,"logger":"tls.cache.maintenance","msg":"stopped background certificate maintenance","cache":"0xc00065f1f0"}
ecamp3-api-caddy              | Error: loading initial config: loading new config: loading http app module: provision http: server srv1: setting up route handlers: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 1: loading module 'mercure': provision http.handlers.mercure: "bolt:///data/mercure.db": invalid transport: open /data/mercure.db: permission denied
ecamp3-frontend exited with code 1
ecamp3-api-caddy exited with code 0
ecamp3-api-php exited with code 0
ecamp3-print exited with code 243
ecamp3-api-php                | Generating public / private keys for JWT
ecamp3-api-php                | mkdir: can't create directory 'config/jwt': Permission denied
ecamp3-api-caddy              | {"level":"info","ts":1686832008.8385277,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
ecamp3-api-caddy              | {"level":"info","ts":1686832008.8463428,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//127.0.0.1:2019","//localhost:2019","//[::1]:2019"]}
ecamp3-api-caddy              | {"level":"info","ts":1686832008.848236,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc00057cc40"}
ecamp3-api-caddy              | {"level":"info","ts":1686832008.8612757,"logger":"tls.cache.maintenance","msg":"stopped background certificate maintenance","cache":"0xc00057cc40"}
ecamp3-api-caddy              | Error: loading initial config: loading new config: loading http app module: provision http: server srv1: setting up route handlers: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 1: loading module 'mercure': provision http.handlers.mercure: "bolt:///data/mercure.db": invalid transport: open /data/mercure.db: permission denied
ecamp3-api-caddy exited with code 0
ecamp3-api-php exited with code 1
ecamp3-api-caddy              | {"level":"info","ts":1686832015.2692122,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
ecamp3-api-caddy              | {"level":"info","ts":1686832015.2729373,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
ecamp3-api-caddy              | {"level":"info","ts":1686832015.2740514,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0003e77a0"}
ecamp3-api-caddy              | {"level":"info","ts":1686832015.2741003,"logger":"tls.cache.maintenance","msg":"stopped background certificate maintenance","cache":"0xc0003e77a0"}
ecamp3-api-caddy              | Error: loading initial config: loading new config: loading http app module: provision http: server srv1: setting up route handlers: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 1: loading module 'mercure': provision http.handlers.mercure: "bolt:///data/mercure.db": invalid transport: open /data/mercure.db: permission denied
ecamp3-api-php exited with code 0
ecamp3-api-caddy exited with code 1
ecamp3-api-caddy exited with code 1
ecamp3-api-php exited with code 1
ecamp3-api-caddy exited with code 1
ecamp3-api-php exited with code 1
ecamp3-api-php exited with code 1
ecamp3-api-caddy exited with code 1de 1
ecamp3-api-caddy exited with code 1

Thank you for a feedback.
Best regards,
Pitt

**Comment by carlobeltrame** [comment]
Looks like various of the ecamp services do not have permission to create files and directories inside the volumes which we give them.

In case you are on a linux machine, did you perform the [post-installation steps](https://docs.docker.com/engine/install/linux-postinstall/) which are required to use `docker compose` without `sudo`?

Does your user account have a user id other than 1000? If so, you have to copy the file .env.ci to .env, and set your user id in there. On linux (or mac I think) you can check your user id with the command `id -u` in a terminal.
