### ISSUE TITLE
Zend Framework renaming and move to Linux foundation

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#352]
Zend Framework wird neu unter das Dach der Linux Foundation gestellt und umbenannt.

Zend Framework heisst neu Laminas.
Apigility wird Laminas API Tools.
Expressive wird Mezzio.

Ein gewisser Migrations-Aufwand wird notwendig sein, sollte sich aber in Grenzen halten. Apigility in der heutigen Form wird nicht mehr umfangreich weiterentwickelt, aber es wird möglicherweise etwas ähnliches auf Basis Expressive/Mezzio geben. Aus Zend-Sicht gibt es ein starker Push, API Bedürfnisse mit Expressive/Mezzio abzudecken. Vielleicht sollten wir das in Betracht ziehen, wenn eine Migration sowieso ansteht.

Lass uns an der nächsten Sitzung mal andiskutieren.

Weitere Infos:
- https://www.zend.com/blog/laminas-transition-update
- https://getlaminas.org/
- https://gist.github.com/weierophinney/df937d870b0d8bded4d1185ef510aaed

**Comment by manuelmeister** [comment]
Wenn wir migrieren, könnte auch gerade in Betracht gezogen werden auf ein komplett anderes Framework umzusteigen (z.B. Laravel, express.js (Node.js), …). Was wäre der Grund auf Laminas zu bleiben?

**Comment by manuelmeister** [comment]
### Meeting Notes
Migration Zend => Laminas ist einfach und nicht dringend. 

Evtl Expressive/Mezzio anschauen. Sie planen in Zukunft etwas funktionell ähnliches wie Apigility in Mezzio zu machen.

Versionierung ist abhängig von diesem Issue
