### ISSUE TITLE
Find replacement for MailHog

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#3528]
Currently MailHog is not actively maintained and is not available on ARM.
https://github.com/mailhog/MailHog/issues/442#issuecomment-1493415258

**Comment by carlobeltrame** [comment]
How about mailcatcher? I'm using that insome other projects, and even in some cypress e2e tests checking taht the correct mails are sent out. Does that work on ARM?

**Comment by manuelmeister** [comment]
I assume, i could not find an official docker image. I've looked at this list: https://github.com/mailhog/MailHog/issues/392

**Comment by carlobeltrame** [comment]
I'm using this Docker image: https://hub.docker.com/r/schickling/mailcatcher/
But it's also very easy to create our own image if needed: https://github.com/hitobito/development/blob/master/docker/mailcatcher.dockerfile

## [MailCatcher](https://mailcatcher.me/)
Data retrieved 2023-09-25
<https://github.com/sj26/mailcatcher> 6k Stars
Code search on github for docker image: 1.4k results https://github.com/search?q=schickling%2Fmailcatcher&type=code
Latest commit: Sep 18, 2023
Latest release: Jul 29, 2023
- [x] Docker Image AMD
- [x] Docker Image ARM
- [x] Web UI
- [x] HTTP API

**Comment by usu** [comment]
On the linked issue on MailHog, they also mention [Mailpit](https://github.com/axllent/mailpit). Could be another option. And seems to have [ARM-builds on docker hub](https://hub.docker.com/r/axllent/mailpit/tags).

## [MailPit](https://github.com/axllent/mailpit)
Data retrieved 2023-09-25
<https://github.com/axllent/mailpit> 3.1k Stars
Code search on github for docker image: 908 results  https://github.com/search?q=axllent%2Fmailpit&type=code
Latest commit: Sep 25, 2023
Latest release: Sep 24, 2023
- [x] Docker Image AMD
- [x] Docker Image ARM
- [x] Web UI
- [x] HTTP API

**Comment by simfeld** [comment]
Another contender: https://github.com/tweedegolf/mailcrab (discovered through https://news.ycombinator.com/item?id=35010794)

> Accept-all SMTP server
> Web interface to view and inspect all incoming email
> View formatted mail, download attachments, view headers or the complete raw mail contents
> Runs on all amd64 and arm64 platforms using docker
>  Just a 7.77 MB docker image

## [MailCrab](https://github.com/tweedegolf/mailcrab)
Data retrieved 2023-09-25
<https://github.com/tweedegolf/mailcrab> 561 Stars
Code search on github for docker image: 28 results https://github.com/search?q=marlonb%2Fmailcrab&type=code
Latest commit: Sep 11, 2023
Latest release: ca Sep 11, 2023
- [x] Docker Image AMD
- [x] Docker Image ARM
- [x] Web UI
- [x] HTTP API

**Comment by BacLuc** [comment]
[supabase](https://supabase.com/) uses [Inbucket](https://inbucket.org/) for the local development environment.

## [Inbucket](https://inbucket.org/)
Data retrieved 2023-09-25
<https://github.com/inbucket/inbuckett> 1.3k Stars
Code search on github for docker image: 650 <https://github.com/search?q=inbucket%2Finbucket&type=Repositories&ref=advsearch&l=&l=>
Latest commit: Sep 18, 2023
Latest release: Feb 28, 2023
- [x] Docker Image AMD
- [x] Docker Image ARM
- [x] Web UI
- [x] HTTP API

**Comment by BacLuc** [comment]
## [MailDev](https://github.com/maildev/maildev)
Data retrieved 2023-09-25
<https://github.com/maildev/maildev> 4.4k Stars
Code search on github for docker image: 1.7k resulsts <https://github.com/search?q=maildev%2Fmaildev&type=code&ref=advsearch>
Latest commit: Jul 20, 2023
Latest release: Jul 20, 2023
- [x] Docker Image AMD
- [x] Docker Image ARM
- [x] Web UI
- [x] HTTP API

**Comment by BacLuc** [comment]
I will try MailDev because its here for a long time, seems to have support and usage, and is written in javascript, if really needed we could also change things more easily.
