### ISSUE TITLE
Copy existing Activity

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#3536]
Idee:
Bestehende Aktivitäten soll man kopieren können - sowohl im Lager, als auch von einem Lager zu einem anderen Lager.

Innerhalb von einem Lager
Varianten:
1. Erstellen-Dialog merkt sich die letzten Eingaben (Name, Ort, Kategorie). So müssen diese nicht immer wieder eingegeben werden. Dadurch kann das erstellen aller TABS-Blöcke vereinfacht wreden.
2. Picasso - im Edit-Modus - der Stift in der Ecke von einem Block zeigt ein Menu. Dieses Enthält folgende Funktionen: 
  a) Bearbeiten -> Detail-Ansicht
  b) Kopieren
  c) evtl. Löschen
Beim wählen von Kopieren kann der kopierte Block im angezeigten Picasso (Periode) beliebig oft wieder eingefügt werden (Stamp-Like).

Von Lager zu Lager
Mögliche Ausbaustufen:
1. Beim erstellen von neuen Aktivitäten Inhalte von bestehenden Blöcken laden. Der Erstellen-Dialog wird um den Button

![Image](https://user-images.githubusercontent.com/470237/248410071-a9e77f53-379f-421f-9b8a-94497ea5119b.png)

2. Bei bereits bestehenden Blöcken Inhalte von anderen Blöcken übernehmen.

![Image](https://user-images.githubusercontent.com/470237/248410606-95c2819a-92af-447d-956d-7ed1a940f00c.png)

3. Beim Bearbeiten von einem Aktivität-Layout zusätzlich vom hinzufügen von neuen ContentNodes anbieten, bestehende ContentNodes zu kopieren.

4. Im Grobprogramm-Edit-Mode zusätzlich zum Stift-Button noch einen Copy-Button anbieten. Wird dieser gedrückt, kann man den Block an einen oder mehrere Orte auf dem Grobprogramm "stempeln".

Vermutlich würde Variante 1 bereits weit helfen. Diese wird daher nachfolgend genauer beschrieben.
Beim Erstellen von einem neuen Block erscheint der bekannte Dialog (Titel, Kategorie, Datum/Zeit). Wird die Funktion 'Erstellen und Inhalte übernehmen' gewählt, öffnet sich ein Folge-Dialog zur Auswahl von einem bestehenden Block, dessen Inhalte dann in den neuen Block kopiert werden.
Die Auswahl von einem bestehene Block soll zudem Lager-Übergreifend funktionieren - und daher zweistufig sein.
1. Lager (alle, welche der User mindestens lesen kann)
2. Block im Lager

Titel, Kategorie, Ort, Zeit/Datem werden von der Benutzer-Eingabe übernommen.
ContentNodes-Vorschlag von der Kategorie wird ignoriert
ContentNodes von der gewählten Aktivität werden kopiert und übernommen.

**Comment by DeNic0la** [comment]
Duplicate of #3376
