### ISSUE TITLE
Performance optimization

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#3539]
Zu prüfen:

- /dashboard
  - http://localhost:3000/api/activities?camp=%2Fapi%2Fcamps%2Fe22915629d96 lädt alle contentnodes mit rootid, die werden nicht ausgegeben, und diese Query wird pro activity 1 mal ausgeführt
  - [Profiler-fetch-activities.txt](https://github.com/ecamp/ecamp3/files/11856321/Symfony.Profiler.txt) (rename back to html)

  - get camp wird 2 mal ausgeführt, dauert beide mal 500ms, 500 queries
  [dashboard-get-camp-doctrine.txt](https://github.com/ecamp/ecamp3/files/11856327/dashboard-get-camp-doctrine.txt)

- /picasso
  schaut gut aus
  /camp/{id} dauert wieder 500ms und macht 500 queries
  [profiler-picasso-activites-of-camp.txt](https://github.com/ecamp/ecamp3/files/11857016/profiler-picasso-activites-of-cam
[profiler-picasso-schedule_entries_of_period.txt](https://github.com/ecamp/ecamp3/files/11857017/profiler-picasso-schedule_entries_of_period.txt)
p.txt)
  

- /story
muss man anschauen
lädt zuerst alle scheduleentries der tage einzeln, dann alle stories der schedule_entries

- /team
sieht gut aus

  - Könnte mit https://github.com/ecamp/ecamp3/pull/4943 verbessert werden

- /material
muss man anschauen
[profiler-material-activities-of-camp.txt](https://github.com/ecamp/ecamp3/files/11857018/profiler-material-activities-of-camp.txt)
[profiler-material-material-items-of-perod.txt](https://github.com/ecamp/ecamp3/files/11857019/profiler-material-material-items-of-perod.txt)

lädt alle materiallisten einzeln

- /print
sieht gut aus

- /admin
sieht gut aus

- /activtiy
Für die sidebar laden wir alle aktivitäten des camps (das geht 2 sekunden)
+ alle scheduleEntries für die periode (das geht auch 2 sekunden9

**Comment by carlobeltrame** [comment]
> http://localhost:3000/api/activities?camp=%2Fapi%2Fcamps%2Fe22915629d96 lädt alle contentnodes mit rootid, die werden nicht ausgegeben, und diese Query wird pro activity 1 mal ausgeführt

This is the problem which we noticed in #2829. Last year we said "We will drop JSON+LD "support" when we have performance problems".

Also note: "We see how good the support for GraphQL is in version 2.7"

**Comment by BacLuc** [comment]
I will close this too.
A lot will be improved with
- #4536 
- #5000
