### ISSUE TITLE
Category create ideas

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#3544]
Followup to #3540

Two ideas:
- [x] New / Empty category, show hint, `here you can design the default look of new activities of this category`  
  solved by #4362
- [x] New / Empty category, show copy-option: copy content from other categories of this camp. e.g. someone creates a dedicated hiking-category, one could copy the contentnodes form 'LS' and adjust these.   
  OR be able to duplicate an existing category #4190

**Comment by carlobeltrame** [comment]
The rest will be tracked in #4190
