### ISSUE TITLE
Sort in Activities Overview for no State / no Responsible

### ISSUE THREAD

**Issue by tillboehringer** [ecamp/ecamp3#3606]
In der Übersicht aller Blöcke ist es aktuell nur möglich, nach Blöcken zu filtern, denen ein Status zugeordnet ist. Es ist nicht möglich, nach Blöcken zu ordnen, denen noch kein Status zugewiesen worden ist.

**Comment by carlobeltrame** [comment]
Related: #3486
If we decide to allow (or even enforce) a default progress label per camp or per category, this issue here would be obsolete.

**Comment by tillboehringer** [comment]
A default label would be great and would also solve the problem. But at the moment there is not an intuitive, easy way to find forgotten Blocks that don’t have a label jet.

I have just seen, there is the same problem with Blocks where there is no responsibility assigned yet.
