### ISSUE TITLE
Schriftart, Look & Feel

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#363]

**Comment by carlobeltrame** [comment]
Der aktuelle font stack:
* `ui-system`: Finde dazu nichts im Internet, bewirkt nichts..? Sollte vielleicht `system-ui` sein für moderne Safari-Versionen? https://css-tricks.com/snippets/css/system-font-stack/#article-header-id-0 
* `-apple-system, BlinkMacSystemFont`: Für Mac OS damit die Systemschriftart San Francisco verwendet wird
* `Segoe UI`: Für Windows
* `Roboto`: Für Android-Geräte
* `Noto Sans`: Wirklich nötig / nützlich? Varianten von Noto sind vor allem in Ländern mit nicht-römischen Schriften (anderes Alphabet als a-z) installiert
* `"Helvetica Neue"`: Auf Mac OS vorinstalliert
* `Fira Sans, Oxygen-Sans, Cantarell`: Wirklich nötig / nützlich?
* `sans-serif`: Fallback für Systeme die oben noch nicht abgedeckt sind
* `emoji, Segoe UI Emoji`: Gibt es realistisch Geräte die keine sans-serif-Schriftart installiert haben? Oder fällt der Browser bei Emoji automatisch auf andere Schriftarten zurück wenn diese z.B. in Segoe UI nicht enthalten sind? Gibt es einen Grund für uns, die Emoji-Schriftart zu spezifizieren? Ich denke Emoji kommen immer von user input, nie von unserem Design.
