### ISSUE TITLE
Frontend Codestyle: .items in computed?

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#364]
In der Codebase gefunden:
```
computed: {
    periods () {
      return this.camp().periods().items
    },
    events () {
      return this.camp().events()
    }
}
```
Wollen wir aus Konsistenzgründen vorschreiben, dass man (normalerweise) nie `.items` in den computed properties zurückgibt? Oder ist es uns egal dass es manchmal so und manchmal so ist (je nach dem ob auch noch `_meta` benötigt wird)?

**Comment by manuelmeister** [comment]
## Meeting Notes
```
computed: {
    periods () {
      return this.camp().periods().items
    },
}
```
Dies ist verboten

**Comment by carlobeltrame** [comment]
Ausnahme: Wenn die Items direkt im computed noch weiterverarbeitet werden, z.B.:
```js
computed: {
    collaborators () {
        return this.camp().camp_collaborations().items.filter(c => !c._meta.deleting)
    },
}
```
