### ISSUE TITLE
Vue Filter for LoadingProxy 

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#366]
Anhand der Seite http://localhost:8080/camps/6c1216f9/Camp1Title/periods habe ich folgendes festgestellt.

Es gibt Vue-Componenten mit Properties, welche gewisse Randbedingungen erfüllen müssen.
Das Beispiel ist: 
```
<v-chip :color=" *** ">..</v-chip>
```

Hier wird erwartet, dass das Property mit einem String befüllt wird.
Das ist mit unseren Store-Proxies natürlich nicht der Fall.

Hier müssen wir diskutieren, wie wir das lösen können.

Erster Vorschlag, welcher mir in den Sinn kommt, ist folgender:
Evtl. brauchen wir die 'isLoadingFilter' dennoch.

So könnte man mit 
```
<v-chip :color="event_category().color | loading('#888888')"> .. </v-chip> 
```
arbeiten.

**Comment by carlobeltrame** [comment]
Ich nehme an du meinst die Fehler die bezüglich Color in der Browser-Konsole auftauchen. Das Beispiel sieht dann in etwa so aus:
```
<v-chip :color="eventInstance.event().event_category().color">{{...}}</v-chip>
```
Der loadingProxy der anfangs bei `.color` zurückkommt ist kein String, was zum Problem führt das du beschreibst. Das lässt sich entweder mit `v-if="!eventInstance.event().event_category()._meta.loading"`, oder aber folgendermassen pragmatisch lösen:
```
<v-chip :color="eventInstance.event().event_category().color.toString()">{{...}}</v-chip>
```
Der loadingProxy ist darauf ausgelegt, mit toString() in einen String konvertiert zu werden, und wenn später alles aus der API geladen ist und `.color` `"ff0000"` zurückgibt, funktioniert `"ff0000".toString()` immer noch wunderbar.

Weitere mögliche [Prop Types](https://vuejs.org/v2/guide/components-props.html#Type-Checks), statt `String`:
* Verlangt eine Komponente ein `Object`, so müssten loadingProxies bereits problemlos akzeptiert werden.
* `Array`s sind ebenfalls schon abgehandelt, da dann bei unserer API-Abstraktion immer zuletzt `.items` stehen muss (z.B. `camp.event_instances().items`). So weiss der Store, dass da ein provisorisches Array (oder ein `loadingArrayProxy` wenn #365 gemerged ist) raus muss.
* `Function` und `Promise` sollten wohl eher selten auftreten im Zusammenhang mit unserer API-Anbindung. Falls doch, dann wäre die Form `:my-getter="camp.owner"` (ohne Klammern zum Funktionsaufruf) bzw. `:my-promise="camp._meta.loaded.then(c => /* something with c */)"`passend.
* Für `Date`, `Number`, `Boolean` und `Symbol` gibt es momentan keine einfache, pragmatische Lösung wie bei `String`. Diese müssten wir manuell abhandeln, mit `.loading` oder Konstrukten wie `new Date(Date.parse(period.start_date) || 0)`, `parseInt(day.day_number)`, `!!camp_collaboration.is_creator` oder `Symbol(event_type.name.toString())`. Wenn nötig könnte man das in [Vue Filter](https://vuejs.org/v2/guide/filters.html) packen, würde ich aber erst machen wenn wir bemerken dass das oft der Fall ist.

**Comment by manuelmeister** [comment]
## Meeting Notes
Vue Filter `| loading('#888888')` implementieren. Es soll nur in Edge Cases verwendet werden. Für die meisten Fälle sollte EINEN Skeleton Loader angezeigt werden.
