### ISSUE TITLE
Templated relations statt hardcoded routes

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#369]
Angesprochen in https://github.com/ecamp/ecamp3/pull/365#discussion_r374265094

In HAL existiert ein Konzept namens "templated relations" [[1]](https://tools.ietf.org/html/draft-kelly-json-hal-06#section-5.2) [[2]](http://stateless.co/hal_specification.html), mit dem es möglich ist, dem API-Client dynamische URLs mitzuteilen (z.B. /camp/{id}). Support dafür müsste man aber in Backend und Frontend selber implementieren. So könnte man die hardcodeten routen aus dem Frontend (in `campFromRoute` und `eventFromRoute` in router.js) entfernen.

Der Vorschlag von Forte sieht wie folgt aus.

Root '/api':
```
{
  "title": "eCamp V3 - API",
  "_links": {
    "camps": {
      "href": "http://localhost:8888/api/camp{/id}",
      "templated": true
    }
  }  
},
```

Aufruf:
```
this.api.get().camps({id: 1234})
```

Abzuklären: Wäre die abgefragte URI dann `/camp/1234` oder `/camp?id=1234`?

**Comment by manuelmeister** [comment]
## Meeting Notes
Machen wir so. Aber es wäre
```
{
  "title": "eCamp V3 - API",
  "_links": {
    "camps": {
      "href": "http://localhost:8888/api/camps{/id}{?owner,archived}",
      "templated": true
    }
  }  
},
```

Folgende URI Template Operatoren werden fast gemäss [RFC6570](https://tools.ietf.org/html/rfc6570) umgesetzt: ` ? / . & `

**Comment by carlobeltrame** [comment]
JavaScript Implementation von templated links: https://github.com/bramstein/url-template
Zwar vor 3 Jahren das letzte Mal geändert, aber ohne weitere Dependencies, darum vermutlich safe to use. Wenn niemand etwas dagegen hat werde ich es mal damit versuchen.
