### ISSUE TITLE
Review Feedback from Closed Beta

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#3690]
Discuss the feedback and see what needs to be done for an initial MVP Release.

**Comment by manuelmeister** [comment]
## Core Meeting Decision

We want to gather feedback from our closed beta tester.

- Nice that you were one of the first and help us make eCamp better.
- Has there been a moment where eCamp did not work technically? You were blocked and could not work.
- How was the Usability?
- Missing Features ( essential, wish )
- Which print layout did you use? Did you use printing?
- Did you use eCamp on mobile/tablet/desktop? For what purposes on which device?

Please send this form to your friends that planed the camp with you. 

Reply to our email or send us a message via https://www.ecamp3.ch/en/contact/

**Comment by manuelmeister** [comment]
## Core Meeting Decision

Publish findings in a anonymized way somewhere public on the internet. Gather main topics and some relevant additional feedback. The target is to be transparent what people wish for and in what occurrence. Set the deadline for next hackathon (2023-09-29).

**Comment by BacLuc** [comment]
We gathered the feedback and already startet implementing it.
https://github.com/ecamp/ecamp3/issues?q=is%3Aopen+is%3Aissue+label%3A%22External+feedback%22
