### ISSUE TITLE
Cant Hover on newly Created Activity

### ISSUE THREAD

**Issue by DeNic0la** [ecamp/ecamp3#3699]
I found some strange behaviour while interacting with newly created Activities in the Picasso;
The Hover is not working the same way for the newly created activity. I made this Graphic to help me explain:
![Explained](https://github.com/ecamp/ecamp3/assets/57986114/de411ef4-b963-41b3-a759-c77459cc9ba4)
If you move your Mouse from the direction of the Green Arrow the Hover-Selection works normally, If you move your Mouse from any of the Directions the Red Arrow point from the Hover Selection will fail. Afaik this happens because there is a Longer Activity 'Over' it.

I Made a Recording of this happening:

https://github.com/ecamp/ecamp3/assets/57986114/f139b42d-d17f-45d2-a319-01b4bff13ec9

I also had a case where the newly created activity was completely Blocked:

https://github.com/ecamp/ecamp3/assets/57986114/b9309340-45a1-4a55-9e1b-eb9d1c4d5dc3

As far as I can tell this doesn't happen on Activities created longer ago, so I don't think it's such a big deal.

**Comment by pmattmann** [comment]
Technically, each block is highlighted when you move the mouse over it (Z-index), so in "3.1 John's casual run" you can't see all the other blocks. I would expect this to be independent of whether a block is new or old. It isn't?

**Comment by DeNic0la** [comment]
> Technically, each block is highlighted when you move the mouse over it (Z-index), so in "3.1 John's casual run" you can't see all the other blocks. I would expect this to be independent of whether a block is new or old. It isn't?

I believe you are correct. I just found it very hard to hover on those blocks and documented that in an issue since I believe the UX could be improved, I am not sure how but it felt flawed to me at the time of recording.

**Comment by pmattmann** [comment]
> > Technically, each block is highlighted when you move the mouse over it (Z-index), so in "3.1 John's casual run" you can't see all the other blocks. I would expect this to be independent of whether a block is new or old. It isn't?
> 
> I believe you are correct. I just found it very hard to hover on those blocks and documented that in an issue since I believe the UX could be improved, I am not sure how but it felt flawed to me at the time of recording.

Can you rename the issue - or even better - create a new one.
Then we can discuss possible solutions.

**Comment by DeNic0la** [comment]
I thought about it and while it feels a bit flawed, it's just a usability issue for Desktop users on a specific constellation. 
Additionally, I can't think of a way to fix this that would not cause other issues since the behaviour is not a bug but a feature.

It's hard to fix and brings very little value - therefore it's not worth pursuing.
If you disagree feel free to reopen this issue.
