### ISSUE TITLE
Performance optimization big plan

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#3717]
## Overall Plan

1. Start with a dedicated Print endpoint that we don't have to improve the performance off all other endpoints #3612 
2. Maybe optimize the endpoints we still need to optimize (with tests that the same properties are returned) (#3539,  #3622, #3602 , #3555 )
3. In the meantime start with the cache with e.g. ContentType, then Category in Camp (Goal, cache is running for most endpoints in ca 2 years) #3610

**Comment by BacLuc** [comment]
For point 2:
I tested the new uriTemplate feature of api-platform 3.2, and it has a big potential.
https://github.com/BacLuc/ecamp3/pull/208
@usu Did i use the feature correctly?

I propose we suspend our optimization effort without that feature, and use the uriTemplate feature as soon as we upgraded to api-platform 3.2

**Comment by carlobeltrame** [comment]
We are now on api platform 3.2. So we can continue with trying to use the native api platform uriTemplate feature now, correct?

**Comment by BacLuc** [comment]
> We are now on api platform 3.2. So we can continue with trying to use the native api platform uriTemplate feature now, correct?

@usu proposed that we do that together with the migration to sub resources that we only need to touch the endpoints once.
But for that we need https://github.com/api-platform/core/pull/5758 that the sub resources can also help with the caching.
So I paused my efforts for now.

**Comment by BacLuc** [comment]
i close this as all proposed steps either failed or are ready as WIP PR, and can be merged as soon as api-platform is ready
