### ISSUE TITLE
Fix "Nesting transactions without enabling savepoints is deprecated."

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#3741]
In our api tests we use a transaction to roll back the changes of a test.
This is deprecated without enabling savepoints.

https://www.doctrine-project.org/projects/doctrine-dbal/en/current/reference/transactions.html

In production we don't use (to @BacLuc knowledge) nested transactions and currently have no usecase for it.

The possible fixes are described as answers, vote with a :+1: for the variant you prefer.

Edit: Alice has the same problem: https://github.com/theofidry/AliceBundle/issues/41

**Comment by BacLuc** [comment]
### Variant 1:
Enable savepoints in the tests.

Then we may test a different behaviour than in production.

**Comment by BacLuc** [comment]
### Variant 2:

Enable savepoints in tests and production:

Like this we activate a feature we currently don't need, but we have the same behavior in test and in production.

**Comment by BacLuc** [comment]
### Variant 3:

Instead of using transactions to roll back the changes to the db of test, alicebundle also allows to:
RecreateDatabaseTrait: Erase and recreate database schema before each tests. (All existing data will be lost!).
ReloadDatabaseTrait: Purges and loads the fixtures before every tests.

We currently use: RefreshDatabaseTrait: Purges and loads the fixtures before the first test and wraps all test in a transaction that will be roll backed when it has finished.

-> This increases the run time of the tests, and makes it difficult to parallelize the tests. (Except when we would use a separate database or separate database server for each test.

**Comment by manuelmeister** [comment]
## Core Meeting Decision

Go for variant 2
