### ISSUE TITLE
Components async loading

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#377]
Ich glaube wir müssen noch definieren, wann etwas async geladen wird und wann als normaler Import (so als Guidelines).

_Originally posted by @manuelmeister in https://github.com/ecamp/ecamp3/pull/372_

**Comment by manuelmeister** [comment]
## Meeting Notes
- async loading nur im Router
- höchstens bei versteckten Komponenten (zB Dialog)

**Comment by carlobeltrame** [comment]
Aktuell finde ich nur noch im Router dynamische Imports. Können wir dieses Issue also schliessen?
