### ISSUE TITLE
loading=true anstatt Spinner + Checkmark

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#380]
Anstatt dem Spinner und dem Checkmark könnte man auch loading setzten:
https://vuetifyjs.com/en/components/inputs#loading
Sonst haben die User von ecamp2 evtl. das Gefühl, man muss jetzt noch das Gutzeichen drücken. Ausserdem ist es bei breiten Feldern viel besser ersichtlich.

**Comment by manuelmeister** [comment]
## Meeting Notes
- Wir verwenden das :loading prop und ein grünes Checkmark bei Erfolg und bei einem Fehler ein retry button anzeigen #275 
(append-icon+clickevent anschauen)
- Alle ApiKomponenten eine Basiskomponente unterstellen (wie TimePicker)
