### ISSUE TITLE
Add richtext placeholder ability

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#3823]
Integrate https://tiptap.dev/api/extensions/placeholder to be able to set a placeholder on empty richtext fields.

**Comment by kendallhtucker** [comment]
hi @manuelmeister! I'm trying to get started in the open source community. can i try this ticket?

**Comment by kendallhtucker** [comment]
@manuelmeister tiptap/extension-placeholder is already in the project and is being used in TiptapEditor.vue. Is there something else that was needed?

**Comment by manuelmeister** [comment]
@kendallhtucker ah I see. Then it must be an integration bug, because on the `/controls` page, the placeholder is not visible in `v-tiptap-editor`, `e-richtext`, `api-richtext` . Would be cool, to be able to use a placeholder for the richtext components as well.

**Comment by BacLuc** [comment]
@manuelmeister 
This seems to be fixed, at least since https://github.com/ecamp/ecamp3/commit/00ce3eff9f39d64e8139b23ed047d972bed95440
