### ISSUE TITLE
[Bug] Uncaught (in promise) TypeError: property is not a function

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#383]
Auf folgenden Error gestossen:
```
storeValueProxy.js:78 Uncaught (in promise) TypeError: property is not a function
    at storeValueProxy.js:78
```

https://github.com/ecamp/ecamp3/blob/e07cea4303c5899ac97bc81116a53906a4529297/frontend/src/store/storeValueProxy.js#L78

Erscheint bei mir jeweils 2x in der Konsole, wenn ich z.B. die Teams oder die Admin-Seite neu lade. Scheint was mit dem Router zu sein. Beim Seitenwechsel erscheinen die Fehlermeldungen nicht. Gefunden beim Testen von Pull Request https://github.com/ecamp/ecamp3/pull/376

@carlobeltrame Kannst du das reproduzieren? Magst du dir den mal anschauen?

**Comment by carlobeltrame** [comment]
Ja ich schaus mir mal an. Taucht auch immer noch auf wenn man devel in den Branch von Linux merget.

**Comment by carlobeltrame** [comment]
Kommt im aktuellen Stand von devel nicht mehr vor. Ich schliesse dieses Issue bis es wieder auftritt.

Fehler dieser Art habe ich schon einige Male gefixt, liegt jeweils an Bugs die mit komplizierten Verhältnissen von geladenen und ungeladenen Entities zu tun haben. Wenns wieder vorkommt fixe ich es und schreibe tests, wie bisher.
