### ISSUE TITLE
Fix duplicated CI checks in merge queue

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#3854]
![image](https://github.com/ecamp/ecamp3/assets/3001985/56f5fdf5-7a34-4f01-9d4e-037335d6f30e)

As you can see in "CI (mandatory checks) / Lint: API" is run two times in the merge queue. This is probably due the CI is run on push and GitHub creates temporary `gh-readonly-queue/devel/**` branches that are not excluded in the workflow:

https://github.com/ecamp/ecamp3/blob/devel/.github/workflows/continuous-integration.yml#L5-L11

**Comment by BacLuc** [comment]
Is this fixed with #3901 ?

**Comment by BacLuc** [comment]
fixed with #3901
