### ISSUE TITLE
ApiForm

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#387]
Idea: Implement `ApiForm` component with similarities to `<v-form>` component or `<form>` tag. Goal is to avoid reentering `uri` and `value` for every field if a buch of data from the same object should be editable.

Today:
```
<api-text-field
        :value="camp().title"
        :uri="camp()._meta.self"
        fieldname="title"
        label="Titel" />
<api-textarea
        :value="camp().motto"
        :uri="camp()._meta.self"
        fieldname="motto"
        label="Motto" />
```

Future:
```
<api-form :value="camp()">
  <api-text-field
        fieldname="title"
        label="Titel" />
  <api-textarea
        fieldname="motto"
        label="Motto" />
</api-form>
```

**Comment by carlobeltrame** [comment]
Ist das überhaupt möglich in Vue? Das ApiForm müsste ja in allen ApiInput-Komponenten in seinem Slot die uri-prop injizieren

**Comment by usu** [comment]
> Ist das überhaupt möglich in Vue? Das ApiForm müsste ja in allen ApiInput-Komponenten in seinem Slot die uri-prop injizieren

Es gibt sowas wie `$parent` aber am Besten wär wohl so:
https://vuejs.org/v2/guide/components-edge-cases.html#Dependency-Injection

Gibt auf der Seite ein schönes Code-Beispiel mit Google Maps:
https://codesandbox.io/s/github/vuejs/vuejs.org/tree/master/src/v2/examples/vue-20-dependency-injection

Klar, die Komponten sind dann natürlich stark gecoupled, aber das ist ja auch die Idee dahinter. Ich denke, das könnt funktionieren.
