### ISSUE TITLE
in French text file 

### ISSUE THREAD

**Issue by fabiancseigenmann** [ecamp/ecamp3#3881]
replace. "picasso" with "programme generale"
checke wether it's hardcoded or not

**Comment by fabiancseigenmann** [comment]
i check wether it's hardcorded

**Comment by fabiancseigenmann** [comment]
fix in it and fr jsons

**Comment by carlobeltrame** [comment]
@fabiancseigenmann can you update the issue title and description, so it describes the problem, and not what to change?

**Comment by carlobeltrame** [comment]
@fabiancseigenmann could you please update this issue's description? Otherwise I would close it because of too little information.
