### ISSUE TITLE
ApiDatePicker & ApiTimePicker are broken

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#3897]
From https://github.com/ecamp/ecamp3/pull/3873

Not mission critical at the moment, because we don't use them anywhere (we only use EDatePicker & ETimePicker).

**Comment by BacLuc** [comment]
Isn't this fixed with https://github.com/ecamp/ecamp3/pull/3873 @usu

**Comment by usu** [comment]
Not fixed with #3873 (the issue came from there). However, I tested on dev and autosave now seems to work also for ApiDatePicker and ApiTimePicker.

So I guess this was fixed by one of the PRs from @manuelmeister. Closing here.
