### ISSUE TITLE
ETimePicker does not allow to type values >= 01:00 and <= 09:59

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#3920]
[datepicker_de.webm](https://github.com/ecamp/ecamp3/assets/1506818/f6bc2edd-86f2-408b-bc54-42e34389c891)

TODO:
- [ ] Make sure that it is possible to type [01:00, 09:59] in the ETimePicker
- [ ] Make sure the ApiTimePicker still works (It should at least be on /controls)
- [ ] Make sure other times still work
- [ ] Make sure other time formats still work
- [ ] Add test in EDatePicker.spec.js which fails without your change (@BacLuc could reproduce it in the test by changing time1 and time2, but both should be tested in the future)

**Comment by Jenis07** [comment]
can i contribute on this?

**Comment by BacLuc** [comment]
> can i contribute on this?

Already implemented in #3921, sry
