### ISSUE TITLE
Auto-Deploy via Travis CI on Pull Request

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#398]
Travis, Docker, Github Actions, DigitalOcean
=> Subdomain: dev.ecamp3.ch

**Comment by manuelmeister** [comment]
https://github.com/carlobeltrame/ecamp3/commit/d42962dba3b3b6c7dfe53e21ce5edff7a7497725#diff-e1dbd7a1b03cb9fbada350027f181b6a

**Comment by carlobeltrame** [comment]
Noch offen:
* [x] php.ini error logging ausschalten
* [ ] ~~allenfalls Datenbank auf Deployments abreissen, da nach grossen Änderungen möglicherweise kaputt~~
* [x] Dokumentation schreiben
* [x] Deployment-Branch von carlobeltrame/ecamp3 nach ecamp/ecamp3 verschieben
