### ISSUE TITLE
PDF content is always english (Layout #1)

### ISSUE THREAD

**Issue by janisint** [ecamp/ecamp3#4072]
Hi,

We're currently organizing our first camp with eCamp3. Looks great overall, thank you very much <3
There is one kinda annoying issue though:

When exporting the camp as a PDF (via Admin->PDF/Drucken), a lot of the content is in english, even though the camp's and my language is german. This only occurs for Layout #1, not for Layout #2.

This is how the file looks:
[Pfi-La-2024.pdf](https://github.com/ecamp/ecamp3/files/13325197/Pfi-La-2024.pdf)

Some examples of english content:
- "Program overview"
- "Day X"
- "No story content found on this day..."
- "Location"
- "Responsible"
- ...

We'd be very glad to have a 100% language-consistent version as a PDF. Let me know if I can provide more information or if you want me to investigate the issue myself (I have experience with Symfony & JS).

Thanks

**Comment by janisint** [comment]
Addition: Same thing goes for the PDF-export of the story (Geschichte), also only for layout #1

**Comment by carlobeltrame** [comment]
Thanks for reporting this! I have seen this problem before, but it's good to finally have an issue for tracking it.

Print layout #1 is currentli getting a big update of the underlying technologies in #4003, so I would suggest we wait until that upgrade is done and see whether we need to more after that.

**Comment by janisint** [comment]
Hey, thank you very much for the quick response! Appreciate it, PR looks great
