### ISSUE TITLE
Bug: Nach Logout und erneutem Login wird das User-Menü nicht mehr angezeigt

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#408]
Während Login und Logout sollte wohl /auth neu aus der API geladen werden.

**Comment by usu** [comment]
`/auth` müsse sicher neu geladen werden, das Problem liegt aber auch im API-key `profile`. Im nicht eingeloggten Status gibt es diesen key nicht. Das User-Menu will aber von `profile` lesen und fällt auf die Nase.

`vue.runtime.esm.js:619 [Vue warn]: Error in render: "TypeError: this.api.get(...).profile is not a function`

**Comment by manuelmeister** [comment]
- [x] Profile Endpoint verwenden
- [x] Profile Endpoint nach Login/Logout neu laden
- [x] Nach Login/Logout den Store purgen

**Comment by manuelmeister** [comment]
Der Store muss so umgebaut werden, dass der State API gepurged werden kann.
