### ISSUE TITLE
Login auch mit E-Mail erlauben

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#411]
* [x] Im Backend auch E-Mail-Login als Username erlauben
* [ ] im Frontend auf der Login-Maske das Benutzername-Feld umbenennen und das Icon auf `mdi-email-outline` ändern

**Comment by BacLuc** [comment]
>     * [ ]  im Frontend auf der Login-Maske das Benutzername-Feld umbenennen und das Icon auf `mdi-email-outline` ändern
Nach Diskussion @BacLuc  und @carlobeltrame :
Wir lassen es bei username, bis es jemanden stört.

**Comment by BacLuc** [comment]
* [x] Im Backend auch E-Mail-Login als Username erlauben

**Comment by carlobeltrame** [comment]
Fixed in #513
