### ISSUE TITLE
Style Build Process

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#414]
- [ ] @usu 
- [x] @carlobeltrame 
- [ ] @pmattmann

**Comment by carlobeltrame** [comment]
Auf die schnelle gefunden. Keines davon 100% optimal
![IMG_0785](https://user-images.githubusercontent.com/7566995/78718367-74951e00-7922-11ea-93a3-8329c21152cf.JPG)
![IMG_0051](https://user-images.githubusercontent.com/7566995/78718372-76f77800-7922-11ea-9699-3b47180d0e5e.JPG)
![23](https://user-images.githubusercontent.com/7566995/78718379-78c13b80-7922-11ea-9cc3-8a1d9fcba4c8.jpg)

**Comment by carlobeltrame** [comment]
Übrigens ist aktuell noch der Bild-Credit hinter dem Footer versteckt auf der Desktop-Ansicht.

**Comment by manuelmeister** [comment]
Kann ich bei mir nicht reproduzieren.

**Comment by carlobeltrame** [comment]
![Screenshot from 2020-04-08 11-53-51](https://user-images.githubusercontent.com/7566995/78770952-a85a5d00-798f-11ea-997c-bbf3ff12cb90.png)
Kann mir nicht vorstellen wie es bei dir funktionieren kann..? `.photo_credits` hat die CSS-Regeln `position: absolute; bottom: 0; right: 0` und `.v-footer--fixed` hat `position: fixed; z-index: 3` sowie `style="left: 0px; right: 0px; bottom: 0px"`

**Comment by manuelmeister** [comment]
Ja das stimmt. `.photo_credits` ist aber innerhalb von `.v-content__wrap` und der ist `relative`, das ist bei dir auch so oder?

**Comment by carlobeltrame** [comment]
Auf dev.ecamp3.ch ist `.photo_credits` zwar innerhalb von `.v-content__wrap`, aber der ist nicht `relative`. Wird ja soweit ich sehe auch nicht gesetzt? https://github.com/ecamp/ecamp3/blob/4819bab8232e0592a9a61b76f1afb28acfa10429/frontend/src/App.vue#L45

Interessanterweise funktioniert das auf e-camp.ch aber so wie du es beschreibst. Ich sehe gerade nicht, was der Unterschied zwischen den builds / deployments der beiden ist... es würde aber beim debuggen helfen wenn du mir sagen kannst wo diese Styles auf `.v-content__wrap` gesetzt werden.

**Comment by carlobeltrame** [comment]
Der Unterschied ist auch, dass auf e-camp.ch die Styles alle im `<head>` als einzelne inline `<style>` Blöcke gerendert wird, aber auf dev.ecamp3.ch wird stattdessen ein app.0e7c1291.css geladen... Auch ein Re-Deployment ändert nichts.

**Comment by manuelmeister** [comment]
In diesem Fall ist e-camp.ch nicht ein production build und es hat mit der Reihenfolge der Stylesheets einen Zusammenhang.

Ich habe übrigens von Lotos die offizielle Genehmigung für die Verwendung des Bildes. Das Bild dass ich aus dem Foto von @carlobeltrame (von Pixel / Fabian Eigenmann) und dem Foto von Johan Mouchet kombiniert habe:
![ecamp_bg_large](https://user-images.githubusercontent.com/3001985/79338093-f25eb800-7f26-11ea-86bf-c4cf01976999.jpg)
können wir sonst an einem anderen Ort verwenden.
(Mir gefällt mein Bild sehr, aber das Foto von Lotos fühlt sich irgendwie passender an)

**Comment by carlobeltrame** [comment]
Merci für den Tipp, du hast recht, der NPM build war ein Development-Build, nicht Production. Ich habe das jetzt angepasst, und jetzt tritt das Problem wenigstens mal konsistent auf allen Deployments auf.

**Comment by manuelmeister** [comment]
Schade 😞 
Dann muss ich das mit dem Produktivbuild mal noch genauer anschauen.
