### ISSUE TITLE
Visual bug in API input components on small screens

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#420]
Tritt auf bei Fensterbreite < 413px für ApiTextField bzw. für Fensterbreite < 446px für die Picker Felder. Umbrechen ab gewissen kleinen Breiten finde ich okay, aber die Borders sollten dann stimmen oder noch besser die Buttons gleich erscheinen wie bei der ApiTextarea.
![Screenshot from 2020-04-13 14-09-20](https://user-images.githubusercontent.com/7566995/79119401-8ea28680-7d90-11ea-9be4-35824f638cc7.png)

**Comment by usu** [comment]
Dürfte im Pull Request #418 nicht mehr auftreten. Ich habe alle Felder auf `separateButtons=true` umgestellt wie bereits beim Textarea und Checkbox. Die attached Buttons haben zu verschiedenen Darstellungsproblemen geführt. Dieser Bug hier + Darstelungsprobleme beim Anzeigen von Error-Messages.

Da wir gesagt haben, dass wir diese manuelle Funktion sowieso wenig gebrauchen werden hatte ich nicht die Gedul, das zu Fixen und alles auf spearate Buttons umgestellt. Von mir aus können wir das so lassen und ich entferne den Code für attached Buttons komplett.

@manuelmeister Ok für dich?
