### ISSUE TITLE
Falsche IDs in URLs handeln

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#421]
Die Frontend-Views versuchen aktuell in Endlosschleife, Daten aus der API zu laden wenn eine ID in der URL falsch ist.

Beispiel: `/camps/00000000`

Besser wäre wohl, bei 404 in `campFromRoute`, `eventInstanceFromRoute` etc. zurück zu navigieren oder eine Fehlerseite anzuzeigen.

Achtung Edge Case: Das müsste aber auch geschehen, wenn ich z.B. die EventInstance-View einer existierenden EventInstance bereits offen habe, jemand anderes die EventInstance bzw. den Event bzw. das Camp löscht, und ich ein Feld auf der EventInstance PATCHen will.

**Comment by usu** [comment]
Das mit der Entlosschleife ist mir auch aufgefallen, allerdings nicht in der Route sondern allgemein beim Laden von Daten.

Im ApiWrapper habe ich das nun gelöst, aber überall sonst fragen wir gelöschte Daten in einer Endlosschleife ab. Etwas weniger tragisch als im Router aber auch nicht schön.

**Comment by manuelmeister** [comment]
## Meeting Notes

### Auftretende Fälle
1. Router (beim Initialen laden der Route)
2. Nicht direkt in der Route 
3. Zwischenzeitliche Änderungen zB kein zweites Mal laden können
4. Verwendung einer nicht mehr existierenden URI innerhalb einer Komponente (zB Dialog)

### Lösungen
- **Fall 1: Route geht nich**
  Generische Errorpage
  öppe so: https://github.com/ecamp/ecamp4
- **Fall 2: GET funktioniert nicht**
  Generischer EventHandler auf Global Scope mit Floating Message
- **Fall 3: Schreib operationen**
  Wer in der Komponente einen GET/POST/PATCH/DELETE Operation macht, muss die Fehler behandeln.
- **Fall 4: Nicht mehr existierende URI innerhalb Komponente**
  ApiForm-Lösung analog von ApiField

**Comment by feigenmann** [comment]
öppe so: https://github.com/ecamp/ecamp4
wohin soll dieser Links zeigen?

**Comment by carlobeltrame** [comment]
https://github.com/ecamp/ecamp4 ist nur ein Beispiel für einen beliebigen Link der ins Leere zeigt. Mit "öppe so" ist der Inhalt gemeint der dann angezeigt wird. Also wenn der User auf einen nicht existierenden Link geht, soll ihm einfach eine Meldung angezeigt werden, dass da etwas nicht stimmt.
