### ISSUE TITLE
Error messages on content node contents are sometimes hidden

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#4267]
![grafik](https://github.com/ecamp/ecamp3/assets/1506818/04dab1c6-cdcb-4aeb-8ed2-7e2406cdd72f)

But also not on dev:
![grafik](https://github.com/ecamp/ecamp3/assets/1506818/ca389d78-b104-42a8-a03d-a68858b090ba)

but this is broken on staging (and i assume on prod) too
![grafik](https://github.com/ecamp/ecamp3/assets/1506818/56bc686a-b0f3-4f01-be0f-11556deb6def)

_Originally posted by @BacLuc in https://github.com/ecamp/ecamp3/issues/4264#issuecomment-1862977537_

**Comment by manuelmeister** [comment]
On my radar
