### ISSUE TITLE
Aus dem Hydrator steuern ob link oder embedded

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#431]
http://localhost/api/periods/6c36a27e liefert heute
```
{
    "id": "6c36a27e",
    "description": "Period of Camp2",
    "start": "2020-04-26",
    "end": "2020-05-01",
    "_embedded": {
        "camp": {
            "_links": {
                "self": {
                    "href": "http://localhost/api/camps/12917773"
                }
            }
        }
    },
    "_links": {
        "self": {
            "href": "http://localhost/api/periods/6c36a27e"
        }
    }
}
```

Wär nicht schöner so?
```
{
    "id": "6c36a27e",
    "description": "Period of Camp2",
    "start": "2020-04-26",
    "end": "2020-05-01",
    "_links": {
        "self": {
            "href": "http://localhost/api/periods/6c36a27e"
        },
        "camp": {
             "href": "http://localhost/api/camps/12917773"
         }
    }
}
```

@pmattmann Ist das möglich? Oder scheitern wir da an den Möglichkeiten von `zf-hal`?

**Comment by carlobeltrame** [comment]
Ich glaube das ist wegen der Tiefen-Limite in `_embedded` die wir setzen müssen. Dadurch kommt das Camp nur noch als "Referenz", was im Frontend gleich behandelt wird wie wenn es ein `_link` wäre.
Die zweite Art sollte aber auf jeden Fall möglich sein im aktuellen Backend, fände ich jetzt auch schöner.

**Comment by usu** [comment]
Schön wäre, wenn ich das Verhalten aus dem Hydrator steuern kann.

`EntityLink`:
1. als link unter _links
2. als "leere" Entity nur mit self Link unter _embedded (falls wir das noch brauchen?)
3. als vollständige Entity

`EntityLinkCollection`:
1. als link unter _links
2. als Array mit leeren Entities (nur Referenzen)
3. als Array mit vollständigen Entities

2 und 3 geht heute schon. 1 bisher noch nicht.

**Comment by carlobeltrame** [comment]
Obsolete with the move to API Platform
