### ISSUE TITLE
eCampApi\module.config.php aufsplitten

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#432]
Related to #426, würde ich aber unabhängig davon ob wir zu Mezzio gehen oder nicht implementieren.

Ich würde dafür plädieren das File aufzuteilen in ein separates config File pro Endpoint (analog wie bei den Plugins). Den Wert dass wir das Apigility als Web-Frontend nicht mehr verwenden können ist aus meiner Sicht verkraftbar.

Ausserdem könnte man wohl einen grossen Teil der config wohl aus einem Template ableiten (DRY), da sich die einzelnen Endpoints teilweise nur minimal unterscheiden.

@pmattmann Es-tu d'accord?

**Comment by carlobeltrame** [comment]
Kann das weg? #570

**Comment by usu** [comment]
Fixed by #570
