### ISSUE TITLE
Store-Logik in Klassen aufteilen

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#436]
@carlobeltrame 
Hab mich gefragt, ob sich der Store-Code etwas stärker modularisieren bzw. robuster gestalten lässt mit Verwendung von Klassen, z.B. eine separate Klasse für `storeValueProxy` anstatt einfach als return value von `createStoreValueProxy`.

Vielleicht sogar Experimenthalber mit Typescript? Vielleicht ist Vue inzwischen soweit, dass das einfacher funktioniert als ich das letzte Mal mit Typescript + Vue gespielt habe.

**Comment by carlobeltrame** [comment]
Ja ich denke man kann das sicher besser schreiben, da stimme ich dir zu. Von TypeScript verstehe ich zwar noch nicht viel, bzw. bin ich nicht sicher ob das wirklich Vorteile bringt, denn ein `storeValueProxy` muss ja Platzhalter sein für ganz verschiedene Datentypen. Aber probieren könnten wirs mal.
Ich frage mich, ob die aktuelle Testabdeckung dafür reicht. Ich glaube da könnte man zuerst noch etwas aufbessern um danach zuversichtlich zu sein dass nach dem Refactoring immer noch alles funktioniert.

**Comment by usu** [comment]
Du, pressiert überhaupt nicht. Ich war bei den letzten Berührungspunkten mit Typescript ja eher frustriert, aber anscheinend hat Vue in das Tooling dazu in der Zwischenzeit einige Fortschritte gemacht.

Konkret zum storeValueProxy: klar da stecken irgendwelche Daten drin. Aber nach aussen ist es dann halt eine Proxy-Klasse und die dies verwenden wissen das wiederum, usw.

Ich könnt mir vorstellen, dass z.B. Fehler wie dieser teilweise bereits durch den Typescript-Compiler aufgedeckt werden:
https://github.com/ecamp/ecamp3/pull/430/files#diff-a94d0150418cc0afbe80139634abd14aR367

Ist aber jetzt nur ne Vermutung. Gut möglich, dass wir noch viele solche Fälle im Code haben.

**Comment by carlobeltrame** [comment]
This is now tracked in https://github.com/ecamp/hal-json-vuex/pull/9
