### ISSUE TITLE
API Laminas/Mezzio

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#439]
Ich habe mit dem aktuellen Stand von Laminas und Mezzio einen Versuch gestartet.
Aktueller stand findet ihr hier:

https://github.com/pmattmann/ecamp3/tree/mezzio/draft

Ich habe nur folgende Entitäten skizziert:
- Organization
- CampTypes
- EventTypes

**Comment by BacLuc** [comment]
Close with #1463  ?
