### ISSUE TITLE
Wrong dirty handling for ApiColorPicker

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#4404]
@usu I couldn't easily fix the picker problem. I did manage to prevent an api request if the value changes from the outside. I think we could fix the dirty problem in a separate PR.

_Originally posted by @manuelmeister in https://github.com/ecamp/ecamp3/issues/4328#issuecomment-1872218067_
            

Problem not a problem with ApiColorPicker but either with BasePicker or with ApiWrapper in general.

The dirty handling has also been raised in the following issues, so it probably makes sense to look at it more holistically:
- https://github.com/ecamp/ecamp3/issues/3875
- https://github.com/ecamp/ecamp3/issues/2578

**Comment by carlobeltrame** [comment]
Fixed in #4761 (unless someone manages to reproduce still)
