### ISSUE TITLE
Synchronize changes from api-platform template (aka switch to FrankenPHP)

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#4453]
The last PRs for synchronizing changes form the official api-platform were approx. 1 year ago:
https://github.com/ecamp/ecamp3/pull/3304
https://github.com/ecamp/ecamp3/pull/3255

In the meantime, the following changes were added:
https://github.com/api-platform/api-platform/compare/7642f8639ff1d95cfa48832db0221973559f8d29...main

The biggest change is the move from php-fpm to frankenphp, which came out beta last month (https://laravel-news.com/frankenphp).

Do we plan to switch to FrankenPHP as well? Or do we judge this as too early?

The biggest benefits I'd see:
- PHP and Caddy in 1 container instead of 2 separate ones
- Potential performance benefits by running Symfony in [worker mode](https://frankenphp.dev/docs/worker/) (similar like node; boot once and then serve all incoming requests). Of course, performance improvements would need to be tested and verified first.

Remaining:
- upgrade to Postgres 16
- FrankenPHP runtime mode

**Comment by manuelmeister** [comment]
## Core Meeting Discuss

- Cool idea. Local dev would probably work with one container as well.
- If someone want to tackle this, we are not against it.
