### ISSUE TITLE
404 Requests (4 per second) for same ScheduleEntry on prod

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#4491]
Single request:
[lots_of_requests_single.json](https://github.com/ecamp/ecamp3/files/13974807/lots_of_requests_single.json)

Sample of the requests:
[lots_of_get_requests.log](https://github.com/ecamp/ecamp3/files/13974808/lots_of_get_requests.log)

Command how i got the sample of the requests:
`kubectl logs -f -l app.kubernetes.io/name=ecamp3-api -c caddy | jq 'select(.status == 404) | {uri: .request.uri, status: .status, time: (.ts | strftime("%Y-%m-%dT%H:%M:%S %Z"))}' > Downloads/lots_of_get_requests.log`

Stopped at 2024-01-18 10:47

Possible reasons:
- An infinite loop in the frontend

**Comment by BacLuc** [comment]
> Sentry issue: [ECAMP3-FRONTEND-169](https://ecamp.sentry.io/issues/4564035547/?referrer=github_integration)

did someone attach this sentry issue?

**Comment by manuelmeister** [comment]
@BacLuc yes me.
