### ISSUE TITLE
Beim Löschen eines Content Nodes in der Ansicht "Layout ändern" wird der Name des Content Nodes nicht richtig angezeigt

### ISSUE THREAD

**Issue by aszakacs** [ecamp/ecamp3#4545]
Schritte zum Reproduzieren:
1. In einem beliebigen Lager auf Programm gehen.
2. einen Block auswählen.
3. oben rechts im Menu "Layout ändern" klicken.
4. einen Content Node hinzufügen, z.B. "Material".
5. Den neu hinzugefügten Content Node wieder entfernen.

Nun kann beobachtet werden, dass steht: "Möchtest du "" wirklich löschen?", wobei der Name fehlt und ein leerer Ausdruck mit Gänsefüsschen zu sehen ist.

**Comment by carlobeltrame** [comment]
Merci für die Meldung! Ich habe in #4546 einen Fix implementiert. Wenn du helfen möchtest, kannst du hier testen ob es funktioniert: https://dev.ecamp3.ch/
