### ISSUE TITLE
Colorpicker improvement

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#467]
Default show swatches and hexfield. On click on textfield show normal colorpicker

Something like this:
![Bildschirmfoto 2023-10-27 um 15 48 05](https://github.com/ecamp/ecamp3/assets/3001985/552dca7c-f734-4477-a165-4be36fb24151)

**Comment by feigenmann** [comment]
stop using static stuff, Will fix this 
<v-btn text color="primary" @click="picker.on.close">Cancel</v-btn>
        <v-btn text color="primary" @click="picker.on.save">OK</v-btn>

**Comment by carlobeltrame** [comment]
Not sure what "swatches" are, but I think this  is now the way it should be

**Comment by manuelmeister** [comment]
Swatches are predefined colors, that we recommend. I think this should be still implemented, but maybe post launch

**Comment by carlobeltrame** [comment]
Implemented in #4213
