### ISSUE TITLE
Recovery when activation E-Mail is lost

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#4670]
# Problem

When the activation email cannot be delivered to a user, he cannot activate his account, even with a reset password email.

# Simple Solution 1

Performing the reset password workflow also activates the account, the email is verified in this case

**Comment by carlobeltrame** [comment]
I think we just need a feature to trigger a new activation email, in case it is lost.

And maybe activate the user when they log in using OAuth. I just debugged a case where the user created an account with password, never activated it, and then tried to log in using MiData. We already set user.state to active when registering a completely new account via OAuth, but we don't when logging in to an existing account via OAuth. Will have to think about the implications though.

**Comment by manuelmeister** [comment]
## Core Meeting Decision

- Add resend link on login page
  - Link to default account activation page in frontend notification
- Account is activated on password reset
- Account is activated upon oauth login
