### ISSUE TITLE
Einstellungen "Aktivitäten" werden nicht immer übernommen

### ISSUE THREAD

**Issue by Dextro00** [ecamp/ecamp3#4726]
Teilweise werden die Einstellungen für die Aktivitäten nicht übernommen.
Teilweise fehlen alle Themeninhalte, wenn man den Block bearbeiten will, manchmal fehlen alle. Die Voreinstellungen im Adminbereich wurden vorgenommen und werden auch teilweise korrekt übernommen.

**Comment by carlobeltrame** [comment]
Merci für die Meldung! Ich bin nicht ganz sicher ob ich dich richtig verstehe. Möglicherweise verwechselst du etwas, weil dieses Feature anders funktioniert als in eCamp v2.

Die Kategorie-Einstellungen wie Kürzel, Kategoriename, Farbe und Nummerierungssystem kannst jederzeit ändern, und alle bestehenden Blöcke werden automatisch angepasst. Diese Einstellungen kannst du aber auch nicht pro Block anpassen (du kannst z.B. nicht nur einen einzigen LS-Block rot statt orange machen).
![Screenshot 2024-03-04 at 09-46-21 eCamp3](https://github.com/ecamp/ecamp3/assets/7566995/524ab541-7bbd-430c-8366-2073b236eb17)


Das Layout und die Inhalte die du in der Kategorie (z.B. LS) definieren kannst, ist hingegen eher als einmalige Kopiervorlage beim Erstellen von neuen Blöcken zu verstehen. Es ist NICHT eine vorgegebene Struktur welche immer allen LS-Blöcken aufgezwungen wird. Jeder LS-Block kann im Layout einzeln angepasst werden. Braucht ein Morgenturnen-Block kein SiKo? Kein Problem, entferne das SiKo aus dem Morgenturnen, und du verschwendest im PDF keinen Platz mehr dafür. Die restlichen LS-Blöcke behalten trotzdem ihr SiKo-Feld.
Die natürliche Konsequenz davon ist, dass die Block-Layouts unabhängig vom Kategorie-Layout sind. Das heisst wenn du bereits LS-Blöcke im Lager erfasst hast, und dann später noch das LS-Kategorie-Layout anpasst, dann hat das keine Auswirkung auf die bestehenden LS-Blöcke. Nur neue LS-Blöcke, welche du ab dann ganz neu ins Lager hinzufügst, bekommen als "Vorlage" für den Anfang mal dein geändertes LS-Kategorie-Layout.

Wir haben versucht, diesen Umstand im Text zu beschreiben. Hast du diesen Text gesehen? Hast du ihn anders oder gar nicht verstanden? Wie könnten wir das verständlicher machen?
![Screenshot 2024-03-04 at 09-53-20 eCamp3](https://github.com/ecamp/ecamp3/assets/7566995/3c5cd7da-732a-4a7b-85db-0721606e2205)

Würde es dir helfen, wenn wir z.B. einen Button einführen würden, mit dem das Kategorie-Layout allen bestehenden LS-Blöcken noch einmal "aufgezwungen" werden könnte? Was sollte deiner Meinung nach dann mit bereits gemachten Änderungen und bereits erfassten LS-Inhalten passieren?

Oder habe ich dich ganz falsch verstanden?
