### ISSUE TITLE
Material: Fehlermeldung beim Feld «Menge»

### ISSUE THREAD

**Issue by chraebsli** [ecamp/ecamp3#4729]
Wenn man beim Material zuerst die Felder `Menge`, `Artikel` & `Materialliste` ausfüllt und anschliessend den Inhalt des Feld `Menge` leert, wird nach dem Hinzufügen folgende Fehlermeldung angezeigt:
> The type of the "quantity" attribute must be "float", "string" given.

![ecamp-error-1](https://github.com/ecamp/ecamp3/assets/73113302/4c6e0dc1-1888-4507-8361-8acc04a396d3)

Wenn man jedoch das Feld `Menge` gar nicht ausfüllt, tritt die Fehlermeldung nicht auf.

---
Build: eCamp [e11a0c3 ](https://github.com/ecamp/ecamp3/commit/e11a0c3)Di 23.01.2024 15:38
Browser: Brave v1.63.162

**Comment by BacLuc** [comment]
Das liegt daran dass wir den leeren String mitschicken.
Danke fürs melden.

![image](https://github.com/ecamp/ecamp3/assets/1506818/344260c5-cf8a-40f6-8ac4-ce85ad47bde0)

Könnte man eventuell mit einem Input Filter im Backend lösen, der empty String zu null macht.
Dann muss das nicht überall im frontend (und in allen künftigen frontends) gelöst werden.

**Comment by carlobeltrame** [comment]
This was also mentioned as Problem 2 in #3998. There we were previously waiting on @DeNic0la because he said he was working on #3912. @DeNic0la any update on that PR, now that it affects real users? Would you prefer to keep working on #3912, or should we take over?
