### ISSUE TITLE
Add Persistent logs and request statistics with e.g. EFK Stack

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#4775]
We would like to have persistent logs and analyze the performance and failure rate of the requests.

# Features

- We can now store and search the logs of our services for a self chosen time. (Index Life Cycle Management in Elasticsearch).
On dev i chose 3 months. This allows to analyse events which happen less often and allows to analyze them far after it occurred.
![grafik](https://github.com/ecamp/ecamp3/assets/1506818/40892f95-ab39-42f3-86f7-d69f202816d8)
With the full support of the KQL

- Browse through interleaved logs of different services:
Choose the services you want to see the logs for:
![grafik](https://github.com/ecamp/ecamp3/assets/1506818/eaa40950-2ae1-429b-a857-edcf0f7ffabb)

And see the logs
![grafik](https://github.com/ecamp/ecamp3/assets/1506818/e3572b65-25f8-44be-8beb-09a8d5599ec5)

- You can quickly see if we had a time interval with a high percentage of 500er errors.
(On dev it is not so enlightening, but with more data on prod this is hopefully better).
![grafik](https://github.com/ecamp/ecamp3/assets/1506818/f046674a-d957-4869-8155-a4d8583a8add)

- We can quickly see on which endpoints we must improve the performance.
![grafik](https://github.com/ecamp/ecamp3/assets/1506818/9a1df7c4-0c0c-486e-a6fc-d87b5a9e628f)
@manuelmeister: is it possible that you worked on the categories on 2023-12-29?
Was the experience really as bad as the data suggests?

- We can see if a certain query parameter kills the performance of an endpoint:
![grafik](https://github.com/ecamp/ecamp3/assets/1506818/28de1e87-bbbb-4e22-90ce-48c818bb1986)

- We can see which endpoints cause most of the trouble:
![grafik](https://github.com/ecamp/ecamp3/assets/1506818/08a81691-dd92-4dad-a195-6e9d3f649a45)

See for yourself with `kubectl -n ecamp3-logging port-forward services/kibana 5601:5601` on http://localhost:5601

To that i had to modify how the ingress-nginx logs requests, this can be seen here: https://github.com/ecamp/ecamp3/wiki/Deployment-installation-Kubernetes#ingress

### Memory
Kibana and elasticsearch are quite heavy, they each require 1Gi to start, but then seem happy with less
-> maybe an additional node is needed for that.
Filebeat needs around 100Mi per node.

### Storage:
Now that we only collect the logs from our services, it seems it is not so much.
Current estimate:
- dev: 10Gi , 1$/month
- staging: 10Gi, 1$/month
- prod: 100Gi, 10$/month

## What is EFK?

(From https://github.com/ecamp/ecamp3/pull/4688#issuecomment-1981168103)
EFK (Elasticsearch-Filebeat-Kibana) is a more modern variant of the ELK (Elasticsearch-Logstash-Kibana) stack. Filebeat, along with Elasticsearch and Kibana, is an official product of Elastic (the company).

Elasticsearch can be seen as a "backend" and always needs some kind of frontend (e.g. Kibana) to display and search the stored data to humans. [Since 2021](https://opensourceconnections.com/blog/2021/01/15/is-elasticsearch-no-longer-open-source-software/), Elasticsearch is not available under a "true" acknowledged Open Source license (I think they switched away after Amazon made tons of money with their product?)

Logstash, the tool responsible for collecting the logs, aggregating and transforming them and sending them to Elasticsearch, was very resource-intensive. That is why it has been replaced with more lightweight alternatives such as Filebeat or Fluentd in modern deployments.

Kibana is a graphing tool which is very specifically developed as a frontend for Elasticsearch. It does not support data sources other than Elasticsearch.

"Beats" is a term for data entries which are collected in the pods and stored in Elasticsearch. There are a number of different official Beat collecting tools by Elastic for different types of Beats, such as Filebeat for log files, Metricsbeat for metrics, Heartbeat for uptime, and [more](https://www.elastic.co/beats).

Questions which occurred to me while reading about all this, some of which I can answer myself already:
- Do we really need a full elastic stack, or would a simpler stack such as Grafana Loki suffice for us, for which digitalocean offers a [1-click deployment](https://marketplace.digitalocean.com/apps/grafana-loki) and which we wouldn't have to maintain ourselves?
  Partial answer: The Grafana Loki stack seems to focus on [course-grained indexes](https://signoz.io/blog/loki-vs-elasticsearch/) and does not support full-text indexing and searching in the logs. See also question below.
- Could we use our existing Grafana instead of Kibana?
  Answer: We could, but Grafana is missing text search features. So we could build the same dashboards, but Grafana would be less valuable for in-depth debugging of logs. On the other hand, we can't replace our Grafana with Kibana either, because Kibana does not support any data sources other than Elasticsearch.
- Given that Elasticsearch is in a [grey area](https://opensourceconnections.com/blog/2021/01/15/is-elasticsearch-no-longer-open-source-software/) when it comes to its Open Source status, would it be better to use an OpenSearch stack?
- Is Filebeat the correct choice, or should we use Fluentd which is more [optimized for cloud-based applications](https://logz.io/blog/filebeat-vs-logstash/)? Digitalocean has a specific [setup guide from 2020](https://www.digitalocean.com/community/tutorials/how-to-set-up-an-elasticsearch-fluentd-and-kibana-efk-logging-stack-on-kubernetes) for EFK with Fluentd. Also, there are independently maintained helm charts for exactly this, e.g. https://github.com/kokuwaio/helm-charts/tree/main/charts/fluentd-elasticsearch
  Partial answer: Filebeat is not an arbitrary choice, it is the official default log forwarding tool by Elastic.
- Why does Elastic not just provide one single helm chart to install the EFK stack into a cluster?
  Answer: They previously did, but discontinued it when they switched to a custom Kubernetes operator (kind of like a Kubernetes plugin). Now, there are two charts. You first have to install the operator via a [helm chart](https://github.com/elastic/cloud-on-k8s/tree/main/deploy/eck-operator). Then, there is an [official chart](https://github.com/elastic/cloud-on-k8s/tree/main/deploy/eck-stack) for installing Elasticsearch and Kibana and additional components such as Beats.

## Discussion on 2024-03-09 between @BacLuc and @carlobeltrame 

Personally, I think if installing Elasticsearch and Kibana on our cluster, we should do it using the currently best supported way, which is via the [ECK Operator](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-install-helm.html) (think of it like a Kubernetes plugin). So this would be the way attempted in #4688. The operator is probably best installed via Elastic's helm chart in our case.

As for how to get the actual Elasticsearch, Kibana and Filebeat instances up and running, there are two options:

## Option 1
We handle all YAMLs ourselves, preferrably with a Helm chart, like it is done in #4688. This seems to be a prominent way of doing things with Elasticsearch, judging by the focus of Elastic's documentation on this approach. Apparently, in practice, companies who are big enough to use an Elastic stack most of the time have some people who can spend their time writing and maintaining Kubernetes YAMLs.

## Option 2
We use the [helm chart](https://github.com/elastic/cloud-on-k8s/tree/main/deploy/eck-stack) which Elastic provides for simple cases. This helm chart is not published on Elastic's helm repository for some reason, but it is definitely maintained and [documented](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-stack-helm-chart.html) and could be used by downloading it from GitHub and applying this local copy to the cluster.

## Option 3
We rent a managed Elasticsearch and Kibana, and only install the Filebeat (which collects the log data from all containers, slightly transforms it and sends it to Elasticsearch) in our Kubernetes cluster, by whatever means seems simplest to us (as a Helm chart or as plain Kubernetes YAML files (either [1 file](https://github.com/ecamp/ecamp3/blob/7c3134066da0ebb5d85af2c05569f4c8be884850/.helm/ecamp3-logging/templates/beats.yaml) if we have the Elastic operator, or [7 files](https://github.com/ecamp/ecamp3/tree/71093a435a5593e81e778344527fa56a3af932fa/.helm/ecamp3-logging/templates/filebeat) without it).
This approach would maybe also allow us to access the Kibana instance without a kubectl port forwarding tunnel.
The Elasticsearch provider which we use should keep the data within Europe, and preferably not be too expensive (digitalocean managed ELK is 144$/month, which is way too expensive in our opinion).

Edit:
## Option 4
Use an Opensearch cluster, they still offer one chart with opensearch and a dashboard.
Opensearch did not yet migrate the ingestion tools over (like filebeat).
But we can combine this with filebeat, we anyway need an ingestion tool, and there we anyway want to configure
the ingestion,
This would be: 
https://github.com/opensearch-project/opensearch-k8s-operator
+ https://github.com/opensearch-project/opensearch-k8s-operator/blob/main/docs/userguide/cluster-chart.md#install-opensearchcluster-using-helm
+ the elastic operator
+ https://github.com/ecamp/ecamp3/blob/7c3134066da0ebb5d85af2c05569f4c8be884850/.helm/ecamp3-logging/templates/beats.yaml

## Additional considerations
We primarily want an EFK stack for getting more statistics on which requests are performed how often and take how long, and maybe in which sequence across all our services. For this purpose, we don't need any identifying information about the user, and we could set up our Filebeat to remove any personal information (as described in https://www.ecamp3.ch/en/tos/#deployment-of-the-application-and-creation-of-log-files) from the logs before persisting them in Elasticsearch.

## Conclusion
We prefer option 3 for now and will go for this (unless someone has objections @manuelmeister @usu @pmattmann @simfeld), because it seems to yield the lowest maintenance effort on our side. @BacLuc has found some options of providers and will list them below.

# Possible Elastic/Opensearch as a Service Providers:

## [elastic](https://www.elastic.co/pricing)

From the creators themselves.
Starting at 95$/month

## [Logz.io](Logz.io)

Pay per use on Amazon or Azure.
Can be hosted in frankfurt
2 GB Logs per day would be 85$/mo

## [Bonsai.io](Bonsai.io)

They do Apache Lucene since 2005, Elasticsearch since 2010.
40 GB SSD would be 50$/mo

## [Aiven](aiven.io)

aiven for opensarch, ca 90$/month

## Digital Ocean Droplet

<https://marketplace.digitalocean.com/apps/elasticsearch>
One or 2 additional droplets: ca 60$/month

# Related PR
- Try with a self made Helm chart: #4351 
- Try with elastic operator: #4688

**Comment by BacLuc** [comment]
I looked a little at the options and come to the following conclusion:

## Elastic/Opensearch as a Service Providers

They offer a generous low tier, but as soon as you really use it and have around 100GB of logs, it gets really expensive.
I also tried logz.io, and it did not work out of the box, and debugging it was also not easy.

## A droplet on e.g. DigitalOcean

The recommended configuration is not cheaper, plus it would be good to document the setup at least in the docs, better with Infrastructure as Code (terraform or pulumi). Plus we would need to make the droplet accessible from the cluster, but don't want to open the log collection port to the internet....there are some parts which have to be done additionally.
I would rather stay with one infrastructure as code/deployment language (kubernetes).

One way to have less Kubernetes as Option 1 and 2 would be Option 4.
@carlobeltrame: would you be ok with Option 4?

**Comment by carlobeltrame** [comment]
Yes, Option 4 is also fine with me

**Comment by BacLuc** [comment]
All the options i tried to get this running:

| daemonset to collect logs        | log processor                  | log storage and indexer               | visualization tool                  | comment                                                                                                       |
|----------------------------------|--------------------------------|---------------------------------------|-------------------------------------|---------------------------------------------------------------------------------------------------------------|
| filebeat                         | x                              | elasticsearch                         | grafana                             | I could not quickly set up a log stream view in grafana                                                       |
| filebeat                         | x                              | elasticsearch                         | kibana                              | All was written by myself, too much yaml. But did work                                                        |
| filebeat (with elastic operator) | x                              | elasticsearch (with elastic operator) | kibana (with elastic operator)      | Still had to write too much yaml. Did not get elasticsearch to start reliably                                 |
| filebeat (with elastic operator) | x                              | opensearch (with opensearch operator) | dashboard (with opensarch operator) | Could not get filebeat to send logs to opensearch                                                             |
| fluentbit (with fluent operator) | x                              | opensearch (with opensearch operator) | dashboard (with opensarch operator) | Could parse the json. (either collect the logs or parse the json, but not both)                               |
| fluentbit (with fluent operator) | fluentd (with fluent operator) | opensearch (with opensearch operator) | dashboard (with opensarch operator) | fluentd output for opensearch required ssl. <br> fluentd output for elasticsearch does not support opensearch |
| fluentd                          | x (already had fluentd)        | elasticsearch                         | kibana                              | did not collect the logs of the ingress-nginx-controller                                                      |
| fluentbit (with fluent operator) | fluentd (with fluent operator) | elasticsearch                         | kibana                              | works (https://github.com/ecamp/ecamp3/pull/5039)                                                                                                         |

**Comment by manuelmeister** [comment]
# Core Meeting Discuss

We think 30 days is enough.

**Comment by BacLuc** [comment]
Is running, yippie
