### ISSUE TITLE
Print

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#479]
Ein paar Notizen und Recherchen zum Drucken.

### TL;DR
Mein 2 Favoriten wären:
- Queue worker (NodeJS) --> puppeteer --> Nuxt + PagedJS
- Queue worker (Python) --> WeasyPrint --> Nuxt

### Nuxt
Brauchen wir für Server-Side-Rendering, falls wir den Inhalt von Vue generieren lassen. 
Vorteil: Reuse von Übersetzung. Entweder ist `print` eine eigene Nuxt-App und greift auf gemeinsame Ressourcen zu. Oder wir packen das ganze Frontend in Nuxt.
https://nuxtjs.org/

### HTML to PDF
Der Maintainer von wkhtmltopdf hat erst gerade vor ein paar Tagen einen umfangreichen Statusbericht erfasst. Spannend zu lesen. Zeigt einige Probleme auf mit wkhtmltopdf bzw. dem darunterliegenden QtWebKit.
https://wkhtmltopdf.org/status.html#recommendations

Am Ende des Artikels werden folgende Optionen empfohlen/erwähnt:
- **wkhtmltopdf**
Hat diverse Issues (siehe Link oben)
- **WeasyPrint**
Python. Basiert nicht auf einer bestehenden browser engine sondern implementiert CSS selbst.
- **Prince**
Commercial tool. Kommt für uns wohl kaum in Frage.
- **puppeteer**
I like 😄 . NodeJS. Basiert auf Chromium. Wird in der NodeJS community sehr verbreitet eingesetzt (e2e tests z.B.). Damit sehr future-proof. 

### WeasyPrint
https://weasyprint.org/
Pro: 
- Implementiert (fast) alle CSS Properties für Printing out-of-the box. Z.B. [target-counter()](https://weasyprint.readthedocs.io/en/stable/features.html#css-generated-content-module-level-3) für Referenzen auf Seitenzahlen um ein Inhaltsverzeichnis zu erstellen

Cons: 
- eigene Implementation bedeutet unter Umständen weniger Future-Proof
- keine Javascript Engine

### Puppeteer / headless chromium
Pro:
- Chromium, very future proof
- volle JS engine

Cons:
- Chromium unterstützt in der Zwischenzeit viele CSS properties für Print, aber eben nicht alle und wird nie Hauptfokus von Chromium sein. target-counter() wird z.B. nicht unterstützt. 

Haupseite: https://github.com/puppeteer/puppeteer
API für PDF: https://pptr.dev/#?product=Puppeteer&version=v4.0.0&show=api-pagepdfoptions
Wrapper-package (nicht zwingend notwendig): https://www.npmjs.com/package/pdf-puppeteer

### PagedJs
Eine Möglichkeit für den fehlendes CSS-Support bei Chromium ist paged.js als polyfill für die fehlenden Properties. Keine Ahnung ob das stabil funktioniert und how well maintained das ist (anzahl downloads ist eher tief). Die hätten auch direkt eine CLI mit headless Chromium.
https://www.pagedjs.org/
https://gitlab.pagedmedia.org/tools/pagedjs

### PHP wrappers für puppeteer
Falls wir aus irgendeinem Grund unsere Queue-Worker zwingend auf PHP laufen lassen wollen, können wir einen PHP wrapper für Puppeter verwenden:

- https://github.com/chrome-php/headless-chromium-php (not very active)
- https://github.com/nesk/PuPHPeteer (searching for maintainer)
- https://github.com/spatie/browsershot (most active)

### Weitere Infos & Ressourcen
https://www.smashingmagazine.com/2018/05/print-stylesheets-in-2018/
https://www.paperplane.app/blog/modern-html-to-pdf-conversion-2019/

**Comment by usu** [comment]
Was muss es können?
- Aus Liste von eingeschränkten Bausteinen auswählen
- Seitenzahlen verlinkt (Table of content)
- Verlinkungen
- Picasso muss vernünftig aussehen (Page orientation change?)
- Gridsystem

**Comment by carlobeltrame** [comment]
Meeting notes:
* Aktuell behalten wir noch beide Workers (weasyprint und puppeteer), die Entscheidung wird später gefällt
* /print Endpoint in der API generiert einen zufälligen Filenamen und schreibt diesen und die PHPSESSID in die Queue. So muss sich der User nicht im Nuxt-Print-Frontend erneut einloggen
* Fertige PDFs werden an einem statischen Ort abgelegt, im Moment pollt das Frontend das statische Resultat-File bis es erstellt ist.
* Wenn wir später mal Fortschritts-Feedback an den User geben wollen oder das Polling authorisieren wollen oder irgendwas derartiges, müsste das Frontend stattdessen bei der API pollen kommen, und der Print Worker müsste Messages in die Queue schreiben die wiederum in PHP verarbeitet werden.
* RabbitMQ im Container aufzusetzen war sehr einfach, und der Code der mit Rabbit zu tun hat beschränkt sich auf ein Minimum. Es wäre also aus aktueller Sicht später einfach, auf eine andere Queue umzusteigen.

[Diagram auf Draw.io](https://viewer.diagrams.net/?highlight=0000ff&edit=_blank&layers=1&nav=1&title=PrintJobArchitecture#R7Vtdl5o4GP41Xo6HEIJ6OZ2vdk%2B3nV13z3b2Zk%2BEqNlBwkIctb9%2BAyQKJKPMCKg9tRclL0mA5%2F143rzJ9ODNYv0Q42j%2BK%2FNJ0LMtf92Dtz3bBkNnIP5LJRspsYZWLpnF1JeynWBMvxPVUUqX1CdJqSNnLOA0Kgs9FobE4yUZjmO2KnebsqD81AjPiCYYezjQpX9Rn89z6dAe7OQfCZ3N1ZOBO8rvLLDqLL8kmWOfrQoieNeDNzFjPL9arG9IkKKncMnH3b9yd%2FtiMQl5nQEPaw89%2FfKb9%2Ffvyyu0%2Bsez0OrlCshpXnCwlF8s35ZvFATEF4jIJov5nM1YiIO7nfRDzJahT9LnWKK16%2FOZsUgIgRD%2BSzjfSPXiJWdCNOeLQN7Vv0W%2BV8KWsUf2fYC0CRzPCN%2FTT2ol%2FZbCAyRSD4QtCI83okNMAszpS1n7WBrRbNtPDr2OY7wpdIgYDXlSmPkxFYgO0iGgJY1BuoMy8%2Fv39RcX%2BRuoVuFTdqLMDt5gE3BosAkHrylLjLbxGU%2BE15f0iQM6C8W1J%2FRJYiF4ITGnwquu5Y0F9f3cdEhCv%2BNJNl9qPBJBMTn60EO3RtvYb8niSWTdM8QG%2BZSS%2B5V0L0ddWX0LALsMfN56m3Xs1Km6sOk0EWZaVmEjSqvhx2UvXc0pJ%2BMIZ961EtG7rMEpDYIbFrA4Gwt9RIa%2BI%2BQJj9kzKdwZ2hPouvt8WNPIq8gPUQl0MJLWv9pFXuDKPvNC1FWcYtJECei3omprqF4%2FftKAFV%2FH27P%2FNFomeeDcGyrfD%2FNAhxlaOsp2Wyi7F85BsCYHoaY56DjbHp4CZQFuvPkmx2eNp7TRR6p5uy7evN3IVvvaUSndiVME4JS9E8EOKN8eaS4YLbNhc4L9M2Z9ZcSNsD6wyqQP3eNYf12eRs06KE%2FQXk4AG84Jmqce6BoY3jZwj9sW9zgaRjcBTb%2FvByN56OhIoy5JHhmM8T6KaYbdScGupLpTlP4zpbpu9ktHsJAX5PmvGbVtrV8tPAwe0qne9MXglz%2B%2F%2FXHx7uEM7P7hNLhTpNWSs%2BOEbE35Nh8T13k6NkCyuUvH0obKxrZZ3DalKw5rJY0b1UzjQNNZ3FE6hfCkOu2jglZBPZUWcvGnkg5PpVHFXGeiUj1VPi6rqtCPa%2BERGJjox74duJal0880%2B7UWFk9ehAFN57FVwp8S1%2FNMiPuD0cTaa%2BT1kd3ioxIyaMB1aOCb9nDVc98YTyaUL%2F67eHrX0AY62m6X5L6NimYiCFnYaOQHvSKb1yTzzkoyANUl88a3bY7zGNMipqrVIKBRQg5HIZxE%2BYbllK5TlTdh9tX9ItP62rS8bi%2Bn1YuMF1hCrG2u51XhVZWmgrl6eBH1bDdIg%2FlErLvdGc8JkYR4QfQ7jx8fx3fj8aevX4zha08RMCBT3kkJEDRZArRdtfspPUgV0Y6sAV5Bq6%2FyGDUz6qNReZ72SoE2%2Bkk%2FGqsc3hKAZ%2BXPoMbSI5njKL2MYuaRJDlMQxPsPc8yxX9d8oCGKgmT%2BZhwCdQQNzkVbjJUJE35b3sp2f56S9M%2BYZ3SJw6beuOL7Fc2Qyr1TTioqDf3XjmqhUDo%2FgyEmtIPW4dzVoFQvfcPEgiHJw6EcP%2FatOUi5btcBHTmIqc7PnCcTveTW%2BuFZ3tU0mvd0jN0hkXNggN6zVqPJKYCtLQItZ27Knu%2FATh1Y2Q7J0w1AkWV6KHVB%2FMXbY1AoWHHnLFnSoz2dh6nRJQzNHNKxAWDkgaOXSJ2sPrTK%2BgrgpNNtv2u6W0XBcBh1myAD5FVOapgGyrjloEQndZWBrqNR8tIhBPDUYWTo2XIHjpGSy8z7UGpm3NG1fo%2FsgwomZKs1g4aQb12POYiXngaVpe%2B1%2BIYLLLTgxRQP1CsKpz9yJ9ePuCjinEbNrc6XUA4NdZjb4qTlSJyccNWrtB9nMy3szWAqTOqhFUDpsaTieAdqIrm7u%2B%2BcpLf%2FfkcvPsf)

**Comment by carlobeltrame** [comment]
Page orientation change ist unterwegs bei Chromium und sollte somit in Zukunft auch bei puppeteer untertützt werden: https://bugs.chromium.org/p/chromium/issues/detail?id=835358
