### ISSUE TITLE
Background Jobs

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#481]
### TL;DR
Ich tendiere zu PHP-enqueue --> AMQP --> RabbitMQ
But not 100% sure

### PHP-enqueue
[`PHP-enqueue`](https://github.com/php-enqueue/enqueue-dev) schaut vielversprechend aus.
- Aktive entwicklung, 1.7k github stars
- [Commercial company ](https://enqueue.forma-pro.com/)im Hintergrund
- Viele unterstützte Backends (Redis, Beanstalk, AMQP, Doctrine, Files)
- Implementiert [`queue-interop`](https://github.com/queue-interop/queue-interop)

**Pros:**
- Backend ist easy austauschbar, z.B. Files oder Doctrine für Development, Redis für Production
- Dadurch tiefe Einstiegshürde für Entwicklung
- Standardisierung für PHP durch `queue-interop`...

**Cons:**
- ... aber eben nur für PHP. Während das Backend dadurch easy austauschbar ist, kann nicht ohne weiteres ein nicht-PHP-consumer aufgesetzt werden, da dieser das Protokoll nicht versteht.

### Fixes Message/Queue-Backend
Die Alternative ist, dass wir uns auf ein Backend fixieren. Für die grösseren Backends gibt es dann Clients in allen gängigen Sprachen (PHP, NodeJS, Python, etc.). Der Nachteil ist, dass man dann natürlich an dieses Backend gebunden ist, sprich nicht mal eben durch Files, MySQL oder so ersetzen kann für die Entwicklung.

Mögliche Optionen:
- Beanstalk
- Amazon SQS
- Google PubSub
- Kafka
- RabbitMQ

--> [Full list](https://taskqueues.com/)

### Fixes Message-Protocol (austauschbares Backend)
Der letzte ([RabbitMQ](https://www.rabbitmq.com/)) hat einen entscheidenden Vorteil. Rabbit unterstützt [AMQP ](https://en.wikipedia.org/wiki/Advanced_Message_Queuing_Protocol) als standardisiertes Message-Protokoll. D.h. damit wird da Backend (Broker) theoretisch auch austauschbar, wobei RabbitMQ im Opensource-Bereich wohl der beliebteste ist.

[Clients ](https://www.rabbitmq.com/devtools.html)dazu gibt es dann in Hülle und Fülle, als Beispiel:
- php-amqplib a pure PHP, fully featured RabbitMQ client
- amqp.node: RabbitMQ (AMQP 0-9-1) client for Node.js
- pika, a pure-Python AMQP 0-9-1 client 
...

oder
- [PHP-enqueue via AMQP](https://php-enqueue.github.io/transport/amqp/), dann hätte man den Benefit von beiden Welten `queue-interop` und AMQP

oder
- [Slm/Queue](https://github.com/JouwWeb/SlmQueue) welcher mit Integration in Laminas/Mezzio mitkommt

### Weitere Ressourcen
Zu Pros/Cons zwischen den einzelnen Brokers gibt es viele Meinungen:
- https://dzone.com/articles/exploring-message-brokers
- https://www.reddit.com/r/PHP/comments/2t48uu/thoughts_on_job_queues_that_work_well_with_php/
- https://ahmetkun.com/post/implementing-queue-system-for-php/
- https://hackernoon.com/introduction-to-message-brokers-part-1-apache-kafka-vs-rabbitmq-8fd67bf68566

Was meint ihr dazu? Ist ein message broker ein Overkill? Oder limitieren wir uns im Gegenzug zu stark wenn wir einfach auf eine PHP-spezifische Lösung setzen?
Konsequenz wäre auch, dass dann Docker fast ein "Muss" wird.

**Comment by manuelmeister** [comment]
Fixed by #506
