### ISSUE TITLE
Hackathon Planning: 12.-14. April 2024

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#4834]
## Main topics
- Courses
  - What do we want? Requirements => create an Epic
  - Goals
  - "Statusdoc Kurs-Admin-Tool" in Google Drive
- Performance improvements for summer camps
  - Queries
  - PostgresDB optimization 
  - #4738 
- Administrative discussion ⚖️

## Further ideas
- Vue 3 (#4456)
- Successor/Future of HalJsonVuex (https://github.com/ecamp/hal-json-vuex/issues/277)
- Change notifications (@pmattmann)

**Comment by BacLuc** [comment]
hackaton is over
