### ISSUE TITLE
Vue build performance

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#484]
Hab mal versucht zu untersuchen, wieso unser Frontend so extrem lang hat zum Builden. Bin dabei über das hier gestolpert:
https://github.com/vuetifyjs/vuetify/issues/9612

Habe daraufhin mal testweise die Datei `scss/variables.scss` entfernt. Siehe da, die Build-Zeiten haben sich dabei bei mir gut halbiert, sowohl mit als auch ohne Cache (die Applikation läuft dann aber natürlich nicht mehr, weil einige Komponenten auf die Variablen angewiesen sind).

Könnt ihr das bei euch auch mal testen? Hat jemand eine Idee was wir tun könnten, damit wir SCSS-Variablen verwenden können ohne dass die Build-Zeiten explodieren?

Hier mal meine Buildzeiten in Sekunden mit `npm run serve`, jeweils mit und ohne Cache:

  | no cache | cache
-- | -- | --
devel | 144 | 97
no variables.scss | 88 | 54

**Comment by manuelmeister** [comment]
Das wird in Vue 3 viel schneller gehen. Darum würde ich das FIle `variables.scss` nicht entfernen, da das Frontend während dem Entwickeln nicht so häufig komplett gebuilded werden muss.

Wahrscheinlich werden wir ja dann auch https://github.com/vitejs/vite verwenden.

**Comment by manuelmeister** [comment]
Urbans Compi ist schneller, jetzt kein Problem mehr ;)
