### ISSUE TITLE
"Only my activities" / "All my activities" Button in ScheduleEntryFilters

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#4956]
Suggestion: conditional label "Nur meine Aktivitäten/Only my activities" (if no other filters set) or "Alle meine Aktivitäten/All my activities" (if other filters are applied) to make it clear that all other filters will be reset.

_Originally posted by @simfeld in https://github.com/ecamp/ecamp3/pull/4573#discussion_r1564298295_

**Comment by carlobeltrame** [comment]
Duplicate of #4952
