### ISSUE TITLE
Textarea Umgang mit Zeichen wie < & >

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#497]
Da HTML-Purifier angewendet wird, werden diese encoded...

**Comment by pmattmann** [comment]
**Varianten:**
- ~~HTML-Purifier ausschalten~~
- ~~HTML-Purifier anders konfigurieren~~
- ~~Encode/Decode von Singletext Inhalt durch Vue-Komponente (so dass HTML-Purifier kompatibel)~~
- Textarea ersetzen durch TipTap-Editor (div contenteditable) ohne Plugins (ohne H1, H2, H3, bold, italic, usw...)

Bei Einzeiler erwarten wir in näherer Zukunft keinen Richtext, String rein, String out
Bei Mehrzeiler erwarten wir Richtext mit Purifier. Es gibt zwei Varianten: einmal mit Richtext und einmal ohne.

**Comment by manuelmeister** [comment]
Wie lösen das andere APIs?
