### ISSUE TITLE
Mail prüfen

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#503]
- Inhalt (selber vs dienstleister)
- Transport (smtp vs dienstleister)
- Development (file output)

**Comment by carlobeltrame** [comment]
Fürs Development ist eine Möglichkeit auch noch [Mailhog](https://github.com/mailhog/MailHog) (oder ein paar ähnliche Alternativen). Das könnte man in einem eigenen [Container](https://hub.docker.com/r/mailhog/mailhog/) laufen lassen und alle Mails da hin schicken, und schon hat man ein simples "Webmail"-Interface wo man alle Mails auch grafisch ansehen kann.

**Comment by manuelmeister** [comment]
https://get.foundation/emails/email-templates.html

**Comment by pmattmann** [comment]
Idee:
- MailService mit vielen Methoden
  - Methode bestimmt Empfänger, Template, KeyValueStore
- Mehrere Implementationen von (Empfänger, Template, KeyValueStore) -> MailVersand (SLM-Mail)
