### ISSUE TITLE
Lagerbezeichnungen anpassen

### ISSUE THREAD

**Issue by nstni** [ecamp/ecamp3#5102]
Hallo zusammen

Da das neue eCamp auf grossen Anklang stösst und bereits grossflächig eingesetzt wird ergab sich für mich ein neues Problem:
Die Lagerbezeichnung ist auf dieser Version nicht wirklich klar. Es gibt Lagername, Lagertitel und Motto, was meiner Meinung nach alles ein wenig ähnlich ist. Sobald man verschiedenen  Orten aktiv ist und mehrere z.B. ein PfiLa 24 eröffnen ist unklar, welches Lager nun welches ist.

Könnte hier ein Feld implementiert werden, dass z.B. die Abteilung/Organisation aufnimmt, die das Lager durchführt?

**Comment by carlobeltrame** [comment]
Merci für die Meldung! Dass die Bezeichnungs-Felder auf dem Lager nicht klar sind, tracken wir bereits in #2992.
Für die Abteilung / Organisation gibt es bereits in den Lagereinstellungen das Feld "Organisator". Dieses haben wir aufgenommen, weil diese Information gemäss J+S auf dem Grobprogramm obligatorisch ist (Broschüre LS/T Lager, Seite 18, diese Broschüre ist leider nicht frei auf dem Internet verfügbar, aber im Downloadbereich von J+S mit dem Login aus den Kursen einsehbar).
Wir können gerne in #2992 diskutieren, die Organisation noch an mehr Orten anzuzeigen, falls sie ausgefüllt wird.

Dieses Issue hier schliesse ich erst mal als Duplikat. Falls ich etwas falsch verstanden habe, bitte melden.

**Comment by manuelmeister** [comment]
Zusätzlich gibt es noch #4978 das dieses Problem reduzieren sollte.
