### ISSUE TITLE
On POST Create, return entity? 

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#519]
Beim erstellen des Picassos hat @pmattmann und ich gemerkt, dass es evtl. Sinn geben könnte, das die erstellte Entity in
 der POST Response zurückzugeben.

**Comment by manuelmeister** [comment]
### Meeting Notes
@pmattmann probiert es aus. In laminas-api-tools-rest RestController.php:400

**Comment by carlobeltrame** [comment]
Es gibt keine formale "REST-Spezifikation", und HAL JSON kümmert sich nur um das Format der Payloads. Aber z.B. in Rails APIs wird standardmässig bei create auch das ganze erstellte Objekt zurückgegeben (https://stackoverflow.com/a/19201805). Bei update hingegen vielleicht nicht.

**Comment by pmattmann** [comment]
Post-Requests geben die erstellte Entität zurück. Dies ist bereits so. Es kann passieren, dass diese nicht vollständig ist. 
Wenn dies nicht so ist, sind vermutlich die Entity-Services falsch programmiert.

Wichtig: 
Sub-Entitäten sollten mittels add...() Methoden an die Vater-Entität angehängt werden - nicht durch das setzen des Vater-Zeigers. Die add...() Methoden sorgen dafür, dass die Beziehung korrekt in beide Richtungen aufgesetzt wird.
Dann erscheinen Sub-Entitäten auch in der POST-Response.
