### ISSUE TITLE
Wiki Docs Naming aktuallisieren

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#520]
Im https://github.com/ecamp/ecamp3/wiki/4-domain-object-model sollte das neue Naming verwendet werden `Event => Activity`

**Comment by manuelmeister** [comment]
See https://github.com/ecamp/ecamp3/pull/430

**Comment by usu** [comment]
Naming im Text und Diagrammen aktualisiert. Gerne kritisch prüfen.

**Comment by pmattmann** [comment]
Sieht gut aus.

**Comment by manuelmeister** [comment]
Stimmt [User & Groups](https://github.com/ecamp/ecamp3/wiki/4-domain-object-model#user--groups) noch?

**Comment by usu** [comment]
> Stimmt [User & Groups](https://github.com/ecamp/ecamp3/wiki/4-domain-object-model#user--groups) noch?

Ja, das ist im Moment nach wie vor so in der DB/Doctrine implementiert. Im Moment bieten wir lediglich (bewusst) keinen Endpoint an für Gruppen/Membership und man kann Lager nur an einen User anknüpfen. Datenbankseitig wär aber alles da um später auch auf Gruppen zu wechseln.
