### ISSUE TITLE
[feature-request]  Aktivitätseinstellungen wie Block-Kategorien und Block-Statusse speichern

### ISSUE THREAD

**Issue by aszakacs** [ecamp/ecamp3#5214]
Es gibt bei den Aktivitätseinstellungen Block-Kategorien und Block-Statusse, die man bearbeiten kann. Z.B. kann das Layout von LA-Blöcken geändert werden, oder es könnte eine neue Blockkategorie namens "RF" hinzugefügt werden. Bei der Lagererstellung kann man aus ein paar vorprogrammierten Vorlagen dieser Aktivitätseinstellungen auswählen, welche man als Grundlage benützen möchte. Diese Vorlagen lassen sich dann im aktuellen Lager bearbeiten.

Feature-Request:
Die bearbeiteten Aktivitätseinstellungen auf den Nutzer speichern können und auf neue Lager anwenden können. So könnte man die Vorlagen auf seine Abteilung/Anwendung anpassen und bei neuen Lagern wiederverwerten. 

Entschuldigt, wenn das ein Duplikat ist, ich habe aber kein entsprechendes "Issue" gefunden.

**Comment by pmattmann** [comment]
Hoi aszakacs

Danke für deinen Input. 

So etwas ähnliches ist bereits möglich - wenn auch etwas versteckt.
Du kannst die Kategorien von einem Lager in ein anders Lager kopieren.

Als Abteilung könnt ihr gerne ein Beispiel-Lager erstellen, aus welchem die Leiter ihre Kategorien jeweils kopieren können/sollen.

Du findest das Feature hier:
- Menu "Admin" > "Aktivitäten"
- Kategorie "Bearbeiten"
- Oben rechts das 3-Punkte-Menu öffnen
- => Kategorie kopieren

Sobald du eine Kategorie kopiert hast, kannst du diese beim Kategorie-Erstellen als Vorlage anwenden.

Falls das deine Bedürfnisse deckt, werde ich das Issue schlissen.
Andernfalls bitte ich dich um Konkretisierung. Danke.

**Comment by aszakacs** [comment]
Lieber Pirmin

Danke für deine Antwort. Ich habe diese Option tatsächlich übersehen. Das ist genau das, was ich gemeint habe, obschon die Kategorien so einzeln kopiert werden müssen.

Danke für euren Einsatz bei der Entwicklung von eCamp und freundliche Grüsse
