### ISSUE TITLE
i18n merge problems

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#528]
If we keep merging i18n files like this, we will have "conflicts". The order of the keys can be different. (I noticed this myself in ebf9a29 because I added `activity` in `entity` at the beginning and not after `activityCategory`). What is the best way to solve this?

I also noticed that `activityContent` is not under our defined language roots (global, entity, components, views). This should probably be moved to `entity`. It might also be better to document in a `frontend/src/locales/readme.md` how the structure, sorting and merging process is defined.

**Comment by carlobeltrame** [comment]
The order of keys is set to be alphabetic in Lokalise (we could also change that if we wanted). So I would just add translations anywhere, and after the PR from Lokalise comes, translations are guaranteed to be sorted again. As long as we don't wait a long time between Lokalise PRs, the merge conflicts shouldn't get too dramatic. If you really want to avoid them on your PRs, you can still add your new translations in correct alphabetical order.

`activityContent` is a collection of translations from plugins, so each entry in `activityContent` can theoretically have its own `entity` and `views` and `components`.

So the only piece missing is documentation. I'm not sure I would look for documentation in `src`, maybe on the wiki or in `docs` or `docu`? Or maybe we should make a plan how to do document all kinds of things (also e.g. our form components).

**Comment by carlobeltrame** [comment]
The documentation part of this issue will be continued in #665
