### ISSUE TITLE
eslint: switch to flat configuration

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#5282]
Eslint 9 uses a new configuration format by default (called "flat configuration"). So this PR would need some config changes before we can upgrade to eslint9.

For Nuxt, some further details are described here:
https://eslint.nuxt.com/guide/faq#package-disambiguation
https://eslint.nuxt.com/packages/module

And here is a eslint migration guide for the new config format:
https://eslint.org/docs/latest/use/configure/migration-guide

_Originally posted by @usu in https://github.com/ecamp/ecamp3/issues/5155#issuecomment-2143788406_

Also, we shouldn't need to add [@typescript-eslint/eslint-plugin](https://github.com/ecamp/ecamp3/pull/4885/commits/2001a803dd091c5a78a5e78d5c67ab8e9a399fde) to the dev dependencies anymore.

**Comment by BacLuc** [comment]
Proposal to resolve this:

1. switch to new format for all modules
I would do this first, because i did not get the nuxt eslint helper modules to support both
2. Update to eslint 9

**Comment by manuelmeister** [comment]
## Core Meeting Decision

1. We individually switch the format for each module
2. Update to eslint 9
