### ISSUE TITLE
EndpointPerformanceTest is flaky

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#5290]
See for example this job run:
https://github.com/ecamp/ecamp3/actions/runs/9344471342/job/25715691538

+ multiple similar ones (always on the /camps endpoint, as far as I have observed so far)

To be checked if we introduced something, that made this endpoint perform worse. Or whether the test was already at the edge before.

**Comment by BacLuc** [comment]
Seems to be since
![image](https://github.com/ecamp/ecamp3/assets/1506818/765b0c73-0a29-44a5-b105-ac2e03e3d413)


(Since then the test go 7 min instead of 2)

https://github.com/ecamp/ecamp3/commits/3fe23435b2410f34d472337abc94539e0e99acb2/?after=3fe23435b2410f34d472337abc94539e0e99acb2+34


commit: https://github.com/BacLuc/ecamp3/commit/30e9479d0066b79b638388e6a06f8428e88ec58b
```
array(43) {
  ["/activities"]=>
  float(0.15)
  ["/activities/item"]=>
  float(0.08)
  ["/activity_progress_labels"]=>
  float(0.03)
  ["/activity_progress_labels/item"]=>
  float(0.03)
  ["/activity_responsibles"]=>
  float(0.03)
  ["/activity_responsibles/item"]=>
  float(0.03)
  ["/camps"]=>
  float(0.03)
  ["/camps/item"]=>
  float(0.03)
  ["/camp_collaborations"]=>
  float(0.03)
  ["/camp_collaborations/item"]=>
  float(0.03)
  ["/categories"]=>
  float(0.03)
  ["/categories/item"]=>
  float(0.03)
  ["/content_types"]=>
  float(0.03)
  ["/content_types/item"]=>
  float(0.03)
  ["/days"]=>
  float(0.03)
  ["/days/item"]=>
  float(0.03)
  ["/day_responsibles"]=>
  float(0.03)
  ["/day_responsibles/item"]=>
  float(0.03)
  ["/material_items"]=>
  float(0.08)
  ["/material_items/item"]=>
  float(0.03)
  ["/material_lists"]=>
  float(0.03)
  ["/material_lists/item"]=>
  float(0.03)
  ["/periods"]=>
  float(0.03)
  ["/periods/item"]=>
  float(0.03)
  ["/profiles"]=>
  float(0.03)
  ["/profiles/item"]=>
  float(0.03)
  ["/schedule_entries"]=>
  float(0.03)
  ["/schedule_entries/item"]=>
  float(0.08)
  ["/users/item"]=>
  float(0.03)
  ["/activities?camp="]=>
  float(0.12)
  ["/activity_progress_labels?camp="]=>
  float(0.03)
  ["/activity_responsibles?activity.camp="]=>
  float(0.03)
  ["/camp_collaborations?camp="]=>
  float(0.03)
  ["/camp_collaborations?activityResponsibles.activity="]=>
  float(0.03)
  ["/categories?camp="]=>
  float(0.03)
  ["/content_types?categories="]=>
  float(0.03)
  ["/day_responsibles?day.period="]=>
  float(0.03)
  ["/material_items?materialList="]=>
  float(0.03)
  ["/material_items?materialNode="]=>
  float(0.03)
  ["/material_items?period="]=>
  float(0.08)
  ["/material_lists?camp="]=>
  float(0.03)
  ["/profiles?user.collaboration.camp="]=>
  float(0.03)
  ["/schedule_entries?period="]=>
  float(0.03)
}
```

Other builds running on my fork:
https://github.com/BacLuc/ecamp3/tree/check-api-performance-test-after-varnish

https://github.com/BacLuc/ecamp3/tree/try-api-without-cache

**Comment by usu** [comment]
I'm very confused. Locally, the performance tests seem absolutely fine.

On CI, we consistently have problems lately. At the moment, it seems always the /camps endpoint. But I tried to check for failures on the devel branch, and earlier it seemed to be a different endpoint sometimes.

**Comment by BacLuc** [comment]
Resolved with
- #5293 
(The test also don't fail anymore if they take too long)
