### ISSUE TITLE
Dev data fixtures for activity data failing (location cannot be null)

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#533]
DONE  Compiled successfully in 347ms   

Allthough 

ecamp3-backend            |    Dev-Data-Loading:     FAIL
ecamp3-backend            | 
ecamp3-backend            | An exception occurred while executing 'INSERT INTO activity (title, location, id, createTime, updateTime, campId, activityCategoryId) VALUES (?, ?, ?, ?, ?, ?, ?)' with params ["Activity LS", null, "ed1c313", "2020-10-17 17:03:40", "2020-10-17 17:03:40", "ee6ecc82", "f6370769"]:
ecamp3-backend            | 
ecamp3-backend            | SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'location' cannot be null
ecamp3-backend            |

_Originally posted by @feigenmann in https://github.com/ecamp/ecamp3/discussions/532_

**Comment by pmattmann** [comment]
fixed by #556
