### ISSUE TITLE
Period edit date validation error

### ISSUE THREAD

**Issue by feigenmann** [ecamp/ecamp3#537]
When Creating a new period 
e.g. 
Start 02.12.2020
End 06.12.2020

the output is : End can not be before Start....

**Comment by feigenmann** [comment]
meeting discuss 20.10.2020 @pmattmann

**Comment by feigenmann** [comment]
Is only working in english language and not in others

**Comment by manuelmeister** [comment]
Das Problem ist, dass der ValidationProvider das Textfeld validiert (das ja in Moment Locale formatiert ist) und nicht das DatePicker Value selber.

**Comment by manuelmeister** [comment]
Duplicate of #525
