### ISSUE TITLE
change: warn to delete camp on camp overview

### ISSUE THREAD

**Issue by feigenmann** [ecamp/ecamp3#541]
see title

**Comment by feigenmann** [comment]
create prompt or disable delete function

**Comment by feigenmann** [comment]
danger zone und prompt in admin verschieben

**Comment by feigenmann** [comment]
ah ja wieso?

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by carlobeltrame** [comment]
Isch nonig erlediget bevor #547 gmerged isch
