### ISSUE TITLE
Broken UI with long links in Storyboard

### ISSUE THREAD

**Issue by TeamBattino** [ecamp/ecamp3#5446]
When I try to paste a link to an SBB connection into a Story board, the UI becomes unusable.
It becomes usable again by saving exiting and entering the Activity.
Even after reopening the activity, the time slots still stay unusable.
![BrokenUi](https://github.com/ecamp/ecamp3/assets/60046498/73eecb00-6169-41d8-987d-e62906219f11)

**Comment by carlobeltrame** [comment]
@TeamBattino thanks for reporting this! I created a quick fix to resolve this for now in #5448. Could you test whether this works for you? https://pr5448.ecamp3.ch

**Comment by TeamBattino** [comment]
Everything seems to be working as expected now. Very cool!
![ImageWorkingRichtext](https://github.com/ecamp/ecamp3/assets/60046498/656db880-3b37-4b4f-9676-7a77efcbe728)

**Comment by carlobeltrame** [comment]
The fix ~~#5448~~ #5455 is not yet merged. The link I sent you was only for a temporary feature preview. I'll keep this open until we merge the fix.
