### ISSUE TITLE
Authentifizierung und SSR

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#549]
Beim Deployment (#398) der Print-Services ([#479](https://github.com/ecamp/ecamp3/issues/479#issuecomment-680226182)) sind mir folgende Gotchas aufgefallen:
1. Um das PHPSESSID Cookie vom Worker via print nuxt server ans Backend weiterzugeben, brauchen wir im nuxt server die Einstellung [`proxyHeaders`](https://axios.nuxtjs.org/options/#proxyheaders). In der Dokumentation dazu steht aber eine Warnung:
    > If you are directing requests to an url that is protected by CloudFlare's CDN you should set this to false in order to prevent CloudFlare from mistakenly detecting a reverse proxy loop and returning a 403 error.

    Ich umgehe dieses Problem indem ich dem nuxt server nicht die öffentliche URL (https://api-dev.ecamp3.ch/api) des backends, sondern die interne URL (http://backend/api) gebe. Bin aber unsicher ob das Problem nicht bei externen Print-Applikationen auch auftauchen würde.

2. Wenn der User die Print Preview unter https://print-dev.ecamp3.ch aufruft, sendet der Browser das Session Cookie von https://api-dev.ecamp3.ch nicht mit, und der nuxt server hat dann keine Möglichkeit sich beim Backend zu authentifizieren. Das ist ein Drawback von SSR. Wir können auch dieses Problem umgehen indem wir das Session-Cookie stattdessen auf die Domain ecamp3.ch statt die Subdomain api-dev.ecamp3.ch laufen lassen, aber das ginge bei einem externen Print-Service definitiv nicht. Ausserdem wird dann dasselbe Cookie ausgeliefert wenn wir entscheiden, unter ecamp3.ch auch eine produktive Instanz oder eine weitere Test-Instanz laufen zu lassen. Theoretisch könnte man das mit Sub-Sub-Domains lösen, aber die werden von unserem CloudFlare-Abo nicht unterstützt.

Brauchen wir vielleicht eine andere Möglichkeit sich beim Backend zu authentifizieren? Möglichkeiten:
- One-time use tokens die beim Backend abgeholt werden können und dann bei Print Preview und beim Erstellen von Print Jobs (und anderen Jobs) mitgegeben werden können. Dann könnte man aber vielleicht die Print Preview nicht mehr einfach mit F5 neu laden
- JWT-Token-basierte Authentifizierung statt PHPSESSID, dann wären wir nicht mehr an die Cookie-Einschränkungen gebunden, müssten dafür selber mehr auf Security achten
- andere Ideen?

**Comment by BacLuc** [comment]
1. Falls beide mit CloudFlare geschützt werden und dann immer noch denkt, dass das ein loop ist, gibt es ein Problem.
Das würde ich dann lösen, wenn wir wirklich einen externen Print Service nutzen.

2.
Variante a)
https://stackoverflow.com/questions/8406719/cookies-set-across-multiple-domains

Nach dem Login holt das Frontend sich beim Backend alle domains, bei denen diese PHPSESSID als identifier für redirects verwendet werden soll.

Dann setzt es für jede dieser Domains die PHPSESSID, die wird dann mitgeschickt und kann weitergeleitet werden.
Falls wir dann einen Print Service für mehrere Instanzen verwenden, können wir die PHPSESSID pro Instanz benennen.
https://www.php.net/manual/en/function.session-name.php

Variante b)
Man verwendet nicht subdomains für die unterscheidung der Services, sondern paths.
Das geht dann aber nur für interne services.
Wir haben im Geschäft das Problem, dass die Kunden kein Wildcard Zertifikat hohlen, sondern für jede subdomain ein eigenes Zertifikat. Dann haben wir frisch fröhlich neue Services gebaut, und das wurde immer teurer.
(Je nach dem einer der Gründe, warum sub sub domains nicht unterstützt werden. Mit Wildcard zertifikaten deckt man nur eine Stufe subdomains ab)

Je nach third Party Applikation oder Framework, das man einbindet, gibt das Kopfschmerzen,
Da sie teilweise eine (oder mehrere) hart kodierte URL's für weitere Requests (oder CSS, Bilder, whatever) verwenden
und diese nicht relativ zum ersten request sind, muss man manchmal bisschen basteln.

Aber meistens klappt das mit einem nginx Reverse Proxy, v.a. da wir bis jetzt alle Services selber schreiben.
(Und nginx reverse Proxy haben wir ja schon)

Bsp nginx config. Unter dem path / ist unser eigener Service, unter /filebrowser/ (der letzte slash ist wichtig) die externe Applikation, die den nötigen Teil des Filesystem einfach zugänglich macht (https://github.com/filebrowser/filebrowser):

```
# Pass HTTP/1.1 Connection/Upgrade hop-by-hop headers to proxy for WebSocket protocol
map $http_upgrade $connection_upgrade {
    default upgrade; # If Upgrade is non-empty, set Connection: upgrade
    '' close;        # If Upgrade is empty, set Connection: close
}

server {
    listen 443 ssl;
    server_name censored.*;
    ssl_certificate /etc/ssl/nginx/ssl.crt;
    ssl_certificate_key /etc/ssl/nginx/ssl.key;

    client_max_body_size 0;
    proxy_buffering off;
    proxy_http_version 1.1;
    proxy_pass_header Authorization;
    proxy_read_timeout 36000s;
    proxy_redirect off;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header Host $host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    resolver 127.0.0.11;

    location / {
        proxy_pass https://censored:8080;
    }

    location /filebrowser/ {
        proxy_pass http://filebrowser:80/;
    }
}
```
Oder selbst geschrieben, react Frontend mit einem Java Backend:
```
server {
    listen 443 ssl;
    server_name myservice.*;
    ssl_certificate /etc/ssl/nginx/ssl.crt;
    ssl_certificate_key /etc/ssl/nginx/ssl.key;

    client_max_body_size 0;
    proxy_buffering off;
    proxy_http_version 1.1;
    proxy_pass_header Authorization;
    proxy_read_timeout 36000s;
    proxy_redirect off;
    proxy_set_header Connection "";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    resolver 127.0.0.11;

    location / {
        proxy_pass http://myservice-frontend:80;
    }

    location /api/ {
        proxy_pass http://myservice-backend:8080/;
    }
}`

```

**Comment by carlobeltrame** [comment]
https://api-tools.getlaminas.org/documentation/auth/authentication-oauth2

**Comment by manuelmeister** [comment]
## Meeting Notes
![IMG_371D9A47DC75-1](https://user-images.githubusercontent.com/3001985/115129051-a97e8b00-9fe2-11eb-8e8c-8c2765a22fc4.jpeg)

**Comment by BacLuc** [comment]
This issue is not relevant anymore.
We don't have a print queue anymore. We still need to maybe implement #3033, but we can track that there.
