### ISSUE TITLE
Service-Proxy funktioniert nicht

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#572]
Service-Proxy funktionieren nicht.

Beispeil:
CampService mit ActivityCategorieService als Proxy funktioniert nicht.
Proxy wurde beim Zugriff nicht aufgelöst. Grund noch unbekannt.

**Comment by usu** [comment]
Konnte reproduzieren.

Problem: Die aufgerufte Methode `create` vom ActivitityCategoryService ist im AbstractEntityService als `final` deklariert. Der Proxy kann logischerweise finale Methoden nicht überschreiben und damit den Aufruf nicht abfangen, ergo der Proxy wird komplett übergangen und nicht aufgelöst.

Siehe hier: https://github.com/Ocramius/ProxyManager/issues/472

Die Lazy-Service-Config mit dem ActivitityCategoryService war ja nur ein Code-Beispiel. Ich würd sagen wir lassen das auskommentiert (oder entfernen den ProxyManager sogar) und kümmern uns wieder darum wenns ein Problem wird.

Ok?

**Comment by pmattmann** [comment]
Erklärung macht sinn.

Aktuell auskommentiert lassen ist für mich ok.
Falls wir die Proxies brauchen, werden wird das 'final' wohl entfernen müssen.
