### ISSUE TITLE
CampCollaboration Status  !==  established

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#579]
Was soll erlaubt sein bei
- requested
- invited
- left

Bezüglich
- ActivityResponsible
- ...

Kann vorzeitig Verantwortzung zugetielt werden oder nicht?

Wie muss der Benutzer markiert sein?
- (Lager verlassen)
- ...?

**Comment by carlobeltrame** [comment]
Das wird neu in #631 verfolgt.
