### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#581]
Siehe #545 

Zu diskutieren, wie API dokumentiert werden soll. Es gibt eine Shortcomings mit Apigility+Swagger, unter anderem

> Response-Beispiel: Reicht ein Beispiel bei GET oder brauchts dies auch bei POST, PATCH, GET collection, etc.?
> Bei PATCH/PUT wird der Body von POST angezeigt und nicht der von PATCH/PUT. Wieso?
> Braucht es PUT überhaupt auf den Endpoints?
> Woher nimmt Swagger die Daten für body Model?
> Wollen wir Details dokumentieren zu Validation / akzeptable Werte?

**Comment by carlobeltrame** [comment]
Obsoleted by the move to API platform
