### ISSUE TITLE
PUT entfernen?

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#582]
PUT als HTTP option entfernen
+
Update von Service entfernen?

**Comment by manuelmeister** [comment]
Approved

**Comment by carlobeltrame** [comment]
This is partially done by now, but we still need to:
- [ ] Disallow PUT in the CORS config
- [ ] Disallow PUT in various API endpoints (might be solved by #827)

**Comment by carlobeltrame** [comment]
Obsoleted by the move to API platform
