### ISSUE TITLE
Remember last camp

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#588]
## Meeting Notes
Mit `localStorage` umsetzten und nicht in DB. Key-Value Store ist noch kein Thema

_Originally posted by @manuelmeister in https://github.com/ecamp/ecamp3/pull/565#issuecomment-721357911_

**Comment by manuelmeister** [comment]
I'm not sure if this should still be done. @pmattmann what do you think?

**Comment by carlobeltrame** [comment]
Not relevant anymore, since the camp selection works differently from eCamp v2.
