### ISSUE TITLE
ScheduleEntry change back from periodOffset to startTime

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#594]
Because it is more user-friendly, we want to go back to the `startTime`.
`periodOffset` was originally the solution to better show the user the data structure of the database and to avoid unexpected shifts (when saving a `ScheduleEntry` but not knowing that the beginning of the `Period` has changed). With the `periodOffset` solution we have now moved the problem to another location.

**Comment by usu** [comment]
**Variante 1:**
- startTime und endTime

**Variante 2:**
- periodOffset und length

**Variante 3:**
Beide retournieren (redundant) aber nur eine erlaube zum Schreiben

**Variante 4:**
Bede retournieren und schreiben via beide erlaubt

To be discussed

**Comment by usu** [comment]
Gleiche Diskussion für Day

**Comment by manuelmeister** [comment]
## Meeting

Dies gilt nur für API nicht für DB:

### Variante 1 für scheduleEntry
starttime read/write, endtime read/write

### Variante 3 für day 
date read, daynumber read (begint bei 1)

**Comment by manuelmeister** [comment]
## Core Meeting Decision

- PHP Entities sollten Getter & Setter für offset, length, start und end haben.
- Rest wie https://github.com/ecamp/ecamp3/issues/594#issuecomment-740851858

**Comment by usu** [comment]
Ich habe versucht, dies umzusetzen. Bin aber ziemlich früh auf konzeptionelle Probleme gestossen.

Am Meeting haben wir gesagt, wir möchten das API-Interface als `start` und `end` haben. In der DB speichern wir idealerweise aber `periodOffset` und `length`. Das verträgt sich nicht gut.

## Beispiel
Angenommen es gibt eine bestehende scheduleEntry, welches wir patchen wollen (Achtung Pseudocode 😄):
```php
ScheduleEntry {
  periodOffset = 480;
  length = 60;

  getStart(); // 2021-01-22T08:00+00:00
  setStart();

  getEnd(); //2021-01-22T09:00+00:00
  setEnd();
}
```
### patch 1 (start first)
Jetzt patchen wir die scheduleEntry wie folgt:
```javascript
{
  start: '2021-01-22T09:00+00:00',
  end: '2021-01-22T11:00+00:00'
}
```
Die Entity wird über setters gepatched:
```php
$scheduleEntry->setStart('2021-01-22T09:00+00:00'); // new periodOffset = 540;  length = 60 (preserving length)
$scheduleEntry->setEnd('2021-01-22T11:00+00:00'); // new length = 120; periodOffset = 540 (preserving periodOffset)
```
### patch 2 (end first)
Wenn das gleiche Patch-Beispiel am ursprünglichen Objekt durchgeführt wird, aber die Reihenfolge von setStart und setEnd vertauscht wird, kommen wir nicht zum gleichen Resultat:
```php
$scheduleEntry->setEnd('2021-01-22T11:00+00:00'); // new length = 180; periodOffset = 480 (preserving periodOffset)
$scheduleEntry->setStart('2021-01-22T09:00+00:00'); // new periodOffset = 540;  length = 180 (preserving length)
```
Das heisst nach dem Patch glaubt die Datenbank/API, der ScheduleEntry ist 3h lang von 9 bis 12. Der Aufruf der Setters ist damit nicht abhängig von der Sequenz, in der Properties verarbeitet werden. AFAIK, gibt es aber in API Platform kein Konzept, welches die genaue Serialisierungs-Reihenfolge spezifiziert (+auch wenn es dazu was gäbe, macht es den Code nicht zwingend leserlicher).

Wenn mach daran festhalten wollte, müsste man wahrscheinlich `start` und `end` auf der Entity als properties zwischenspeichern & dann kurz vor dem persisten mittels Dotrine Lifecyclce Hooks in `periodOffset` & `length` übersetzen (und analog einen Hook nach dem Laden, um `periodOffset` & `length` in `start` & `end` zu übersetzten).

### Varianten
Ich sehe damit folgende Varianten.

1. Alles so lassen wie heute.
**Doctrine**: int periodOffset, int length
**API**: int periodOffset, int length (DateTime start, DateTime end read-only als convencience)

2. Anforderungen aus dem Meeting versuchen umzusetzen mittels Doctrine Lifecycle Hooks
**Doctrine**: int periodOffset, int length
**API**: DateTime start, DateTime end

3. Wechsel auf `start` und `end`, sowohl in der API als auch in der DB
**Doctrine**: DateTime start, DateTime end
**API**: DateTime start, DateTime end (length/duration read-only als convenience kann man diskutieren)

4. Am Konzept 1 festhalten mit Offset und Länge, aber nicht als Datentyp int (Minuten) sondern als saubere DateInterval Typen
**Doctrine**: DateInterval periodOffset, DateInterval duration
**API**: DateInterval periodOffset, DateInterval duration

### persönliche Meinung
Bei Variante 2 sehe ich den Mehrwert nicht, selbst wenn es technisch irgendwie möglich ist.

Variante 1 gibt natürlich am wenigsten/keinen Aufwand.

Variante 3 und 4 sind sicherlich sauberer als Variante 1, da wir nicht implizit mit int/Minuten arbeiten sondern mit sauberen DateTime-Datentypen.

Unterschied Variante 3 oder 4 ist wieder die alte Diskussion von oben. Wenn wir diese Diskussion/Entscheid konsequent weiterführen, dann wäre es Variante 3.

@manuelmeister @pmattmann  @carlobeltrame @BacLuc
Shall we do a vote?

**Comment by carlobeltrame** [comment]
Würden wir diese Entscheidung konsequenterweise auch gleich bei Day mitziehen? Oder siehst du da noch andere Gründe dagegen?

**Comment by BacLuc** [comment]
> 1. Anforderungen aus dem Meeting versuchen umzusetzen mittels Doctrine Lifecycle Hooks
> Doctrine: int periodOffset, int length
> API: DateTime start, DateTime end

Es gäbe noch zwei varianten, wie man das implementieren könnte:
1. Im DataPersister: Dabei kommt das embedded update nicht mit, + die Validierung springt vorher an.
2. Mehr Logik in den Settern.
Du kannst zwar die Reihenfolge, in der die Setter aufgerufen werden, nicht bestimmen.
Aber du kannst bestimmen, ob du gerade im ersten oder im zweiten Setter bist, der aufgerufen wird.

```php
public void setStart(DateTimeInterface start) {
  //$this->start und $this->end sind nur api properties, und werden nur bei POST/PATCH auf die API geschrieben.
  $this->start = start;
  if (null === $this->end) {
    //set only periodOffset in case it was a patch with only the start
    return;
  }
  $this->updateStartAndEnd()
}

public void setEnd(DateTimeInterface start) {
  $this->end = end;
  if (null === $this->start) {
    //set only length in case it was a patch with only the end
    return;
  }
  $this->updateStartAndEnd()
}

private void updateStartAndEnd() {
//here you have both new values and can set periodOffset and length
}
```

**Comment by manuelmeister** [comment]
## Core Meeting Decision 

Wir gehen mit einer neuen Variante:
Wir verändern Konzept 1 zu offset start & offset end, aber nicht als Datentyp int (Minuten) sondern als saubere DateInterval Typen.
**Doctrine**: DateInterval startPeriodOffset, DateInterval endPeriodOffset
**API**: DateTime start, DateTime end

ScheduleEntry DateTime Filter beachten, falls nicht gut möglich, lieber Minuten.

**Comment by BacLuc** [comment]
https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/known-vendor-issues.html
