### ISSUE TITLE
Polling nach gedruckten PDFs abbrechen, wenn der User von der Print-Ansicht wegnavigiert

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#602]
Falls beim PDF generieren etwas fehlschlägt pollt das Frontend aktuell endlos weiter bis der User mit F5 die Seite neu lädt oder sonstwie die SPA beendet.

**Comment by usu** [comment]
Entweder Polling abbrechen.

**Alternative**: Polling weiterführen und Print-Job in den Vuex-Store reinhauen, so dass ich wegnavigieren kann und wenn ich wieder zurück komme ist der Print-Job immer noch da.

**Comment by carlobeltrame** [comment]
Ja also durch die bestehende `setTimeout` Logik wird der Download auch jetzt schon noch ausgeführt, auch wenn der User wegnavigiert hat. Aber dann ists halt nur noch ein einmaliger Download, ist dann kein Link auf dem Bildschirm den ich noch einmal anklicken kann. Könnte man sicher schöner lösen.
Aber im Moment bin ich sowieso noch nicht überzeugt von der Zeit die es braucht bis ein PDF generiert ist, das kann gut mal 3 Minuten dauern. Um das zu verschnellern müsste man wohl auf dem Hosting noch viel mehr Ressourcen geben. Bei 3 Minuten ist es wohl doch fast einfacher für den User, einfach die Print Preview selber in ein PDF zu drucken.

**Comment by usu** [comment]
> Aber im Moment bin ich sowieso noch nicht überzeugt von der Zeit die es braucht bis ein PDF generiert ist, das kann gut mal 3 Minuten dauern.

Ah echt? Lokal sinds bei mir etwa 8 Sekunden beim Test-Camp. Müsste man sicher mal analysieren, wo der bottleneck ist...
Edit: Für den Puppeteer. Der Weasy braucht ewigs.

**Comment by BacLuc** [comment]
Printing was changed and simplified, this was resolved by generating the pdf ad hoc and synchronous.
