### ISSUE TITLE
Idee: Versions-Anzeige

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#604]
Falls möglich, Commit-ID oder ähnliches auf Seite anzeigen können.
Erlaubt es einfacher zu prüfen, welcher Stand auf dev.ecamp3.ch läuft.

**Comment by usu** [comment]
Genaue dieselbe Idee hatte ich heute auch. +1 von meiner Seite

**Comment by manuelmeister** [comment]
Ich habe eine Diskussion dafür erstellt: #606

**Comment by manuelmeister** [comment]
Ich habe eine Diskussion dafür erstellt: #606
