### ISSUE TITLE
Frontend date & time handling

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#605]
- UnitTests und in-code documentation für Date & time picker
- Klare Richtline, welcher Layer arbeitet mit welchen Datumsformaten (wer mit strings? wer mit timestamps? wer in UTC und wer mit Timezones?)
- Braucht es für Date & time picker einen UTC-mode und einen non-utc mode?

Auch related zu #597

**Comment by usu** [comment]
Es braucht aktuell keinen Non-UTC mode:
Date & Timepicker sollen entweder String zurück geben 
oder
falls DateTime-Object dann in UTC-Mode

**Comment by manuelmeister** [comment]
## Meeting Discuss

Hier geht es vor allem noch um die Tests schreiben. #637
Zeitzone simulieren bei Frontend Tests.
