### ISSUE TITLE
Version-Anzeige funktioniert nicht

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#608]
PR #607 ist angenommen.
Commit wird auf dev.ecamp3.ch jedoch nicht angezeigt.

**Comment by carlobeltrame** [comment]
Im Deployment stimmt alles. CloudFlare hat aber noch das alte environment.js gecached. Sobald CloudFlare das aktuelle ausliefert, sollte es funktionieren ;) Ich lasse das Issue mal noch offen bis wir bestätigen können dass es funktioniert.

**Comment by pmattmann** [comment]
Alles klar.
Das Problem wird sich somit wiederholen - mal schauen, ob ich auf CloudFlare was einstellen kann.

**Comment by pmattmann** [comment]
Update: Der Cache ist auf 4h eingestellt. Damit sollten wir leben können.

**Comment by carlobeltrame** [comment]
Hm ich könnte auch cache busting für diese Datei einrichten, dann wäre das kein Problem mehr... Mal überlegen wie das am besten ginge.
