### ISSUE TITLE
Frontend 404 für fehlerhafte Routen

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#622]
Wenn der User eine URL öffnet, welche entweder
- vom Router nicht aufgelöst werden kann
- eine Entity-ID (camp, etc.) enthält welche nicht existiert

--> Anzeigen einer seitenfüllenden Fehlermeldung
--> ohne dabei die URL umzuleiten (Browser-URL zeigt immer noch die fehlerhafte URL an)

Weiterführung der Diskussion von #612

**Comment by BacLuc** [comment]
Duplicate of #3140
