### ISSUE TITLE
CampCollaboration können Aktivitäten, Verantwortlichkeiten, etc. zugeordnet werden, selbst wenn sie die Einladung noch nicht angenommen haben

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#624]
CampCollaboration im Status invited/requested können bereits im Camp verwendet werden für Zuordnung von Aktivitäten, Material, etc.

Voraussetzung dafür ist, dass auf CampCollaboration im Nachhinein die Mail-Adresse oder der User geändert werden kann, falls man sich vertippt hat.

**Comment by carlobeltrame** [comment]
This was implemented I think.
