### ISSUE TITLE
Change durations to ISO8601 format

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#633]
Momentan haben wir unterschiedliche implizite Felder mit Länge in Minuten, usw.
Damit die Kommunikation in der API immer gleich ist, sollte auch die Durations nur als ISO8601 dargestellt werden.

**Comment by carlobeltrame** [comment]
Ist das noch aktuell? Soweit ich weiss haben wir nur ISO Dates sowie Felder in Minuten. Alle API-Felder sind in Swagger dokumentiert.
