### ISSUE TITLE
Circumvent popup blocker when opening a scheduleEntry in a new tab

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#679]
https://github.com/ecamp/ecamp3/pull/656#discussion_r526367331

There is a way to open popups without popup blocker warning in Firefox, I've seen it on WeKan's OAuth popup.

**Comment by manuelmeister** [comment]
I think, it is just important, that the open in new tab is a direct descendent of a user event.

**Comment by manuelmeister** [comment]
This has been solved as we use anchor tags instead of js navigation.
