### ISSUE TITLE
Travis Caching

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#681]
We should cache the dependencies in travis.
https://docs.travis-ci.com/user/caching/

**Comment by usu** [comment]
More precisely (also from discusison in #676):
- Cache "npm cache" and "composer cache" between builds
- Cache cypress --> takes long time to download
- Cache "node_modules" and "vendor" between jobs of the same build

**Comment by manuelmeister** [comment]
Resolved by #682
