### ISSUE TITLE
Stay on Travis or not?

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#682]
Options to discuss:

- Stay on Travis and regulary ask for OSS credits
- Migrate to Github Actions
- other options?

**Comment by carlobeltrame** [comment]
Context:
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works

**Comment by manuelmeister** [comment]
I think it would be cool to have a tighter Github integration. It would allow us to see on PR level instantly which checks fail.

**Comment by carlobeltrame** [comment]
The first build is starting to run into the limit: https://travis-ci.com/github/ecamp/ecamp3/builds/206886958

**Comment by manuelmeister** [comment]
## Meeting Discussion

- In the long run we may switch to github actions #702, if travis is too much work.
- @BacLuc messages travis support
