### ISSUE TITLE
RPC endpoint improvements

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#684]
The Auth RPC endpoint is not very clean today (noticed this while writing the API tests). Main issues:
- GET actions with side effects (bad practice)
- Redirects

I think it's worth to redesign the Auth endpoint more cleanly.

One idea could be to convert it to a more RESTful or at least RESTlike /session or /token endpoint. Some inspiration:
- https://stackoverflow.com/a/7244941
- https://softwareengineering.stackexchange.com/a/308765
- https://medium.com/@kennch/example-of-restful-apis-81fb344f9d04 (end of the article)

As we're at it:
- Do we need the /register endpoint. Or could we just POST on /user?
- Do we want to allow login via password on the API? Honestly, I don't really want other frontends/Apps to ask the user for the ecamp3-password...

**Comment by carlobeltrame** [comment]
About the `/register` endpoint, I'd rather keep that as an RPC if it allows us to have generalized authentication logic across all REST endpoints (see https://github.com/ecamp/ecamp3/pull/568#issuecomment-719745763)

**Comment by manuelmeister** [comment]
## Meeting Discussion

- GET can't have side-effects
- Remaining discussion postponed

**Comment by carlobeltrame** [comment]
Obsoleted by the move to API Platform
