### ISSUE TITLE
RPC /profile endpoint needed?

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#685]
Folgendes Problem mit dem /profile endpoint:
- Der RPC Controller turnt eifrig direkt auf der User Entity herum. Wäre es nicht cleaner, der würde via UserService gehen? Der UserService kann dann entsprechend die ACL ankicken (was darf ein beliebiger User? Was darf ich selber? Was darf der Admin? etc.).

- Falls ja: Brauchen wir dann den /profile Endpoint überhaupt separat? Wir haben ja bereits den /user endpoint, welcher Daten des Users anzeigen + schreiben kann.

In zweiterem Fall könnte der profile-Link ja einfach auf den entsprechenden User zeigen.

Only caveat: Der /profile Endpunkt gibt heute ja mehr Daten zurück als /user
**Option 1:** Wir relaxen die Anforderung, dass ein Endpunkt immer alle Keys zurück geben muss
**Option 2:** Wir behalten /profile, implementieren aber als REST einfach mit einem anderen Hydrator (und nur mit GET/PATCH Oprationen)

(Implizit Teil von diesem Ticket: isAdmin kann nur von Admins verändert werden, please)
https://github.com/ecamp/ecamp3/pull/673/files#r525987849

**Comment by carlobeltrame** [comment]
Ich finde jetzt gerade keine markierten Meeting Notes dazu, aber hatten wir nicht schon mal genau das diskutiert? Vielleicht ist daraus dieses Issue entstanden? https://github.com/ecamp/ecamp3/issues/396

Wir können gerne nochmals drüber reden. Ich hatte im Kopf dass noch der Login-Status via Profile Endpoint abgerufen wird, aber das machen wir ja jetzt mit dem `authenticated` Flag auf dem Root Endpoint.

**Comment by usu** [comment]
Ah ja stimmt, dass war glaubs aus dem hier entstanden:
https://github.com/ecamp/ecamp3/issues/408#issuecomment-630440667

Ok, will nicht zwingend Diskussionen anstossen, die wir schon mal geführt haben.

Mir ists halt aufgefallen, weil @pmattmann  mal eben im RPC Controller den User zum Admin macht. Als nächstes wechselt er noch kurz die E-Mail, ändert die ID und verkauft dem User seine Seele ;-)

Ergo müsste Schreiben über den UserService gehen, wo eine saubere ACL Abfrage statt findet. Und dann ist für mich fraglich ob es zwingend noch einen separaten Endpunkt dazu braucht.

Plus was ich oben vergessen hab: Der Tag wird kommen, an dem wir als Admin auch das Profil eines anderen Users bearbeiten wollen. Dann ist ein /profile endpoint ohne ID relativ mühsam.

Let me know wenn ich irgendwas ausblende/übersehe.

**Comment by manuelmeister** [comment]
## Meeting Discussion

- Klären ob wir einen anderen Hydrator, anderen Service etc. für die gleiche Doctrine-Entity setzen können.

**Comment by manuelmeister** [comment]
## Core Meeting Decision

Ist uns aktuell nicht so wichtig. Kann aber immer noch gerne gelöst werden.

**Comment by BacLuc** [comment]
Können wir diesen issue schliessen?

**Comment by usu** [comment]
Implemented/superseded by https://github.com/ecamp/ecamp3/pull/2241
