### ISSUE TITLE
Library Updates

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#687]
How and when do we want to make library updates?

Possibilities:

1. Only when really really necessary
2. When we need new features
3. When the version is end of life
4. in a defined interval we update all Libraries to the latest stable release
5. Whenever a new version is available and someone has time
6. Automated with Github Actions

Current inducement: phpunit, we are at 6.5, it's eol since 2019-02-01, current Version is 9 (https://phpunit.de/supported-versions.html)

**Comment by carlobeltrame** [comment]
From my point of view, as far as we have enough test coverage, we should update as often as possible / as someone has time, especially minor and patch releases. I'd love to use automation for this, but I think we'd need very high test coverage first before attempting this. So I'm somewhere between options 5 and 6.

**Comment by usu** [comment]
> I'd love to use automation for this, but I think we'd need very high test coverage first before attempting this. So I'm somewhere between options 5 and 6.

Same opinion from my side. 6 would be nice, but needs much more tests / quality control. By the way, there's pretty good video from Marco Pivetta on Youtube on what high standard quality control means for PHP: https://www.youtube.com/watch?v=8rdTSYljts4

Maybe we can differentiate between major and minor versions and automate updating minor version. Not much should break there.

**Comment by manuelmeister** [comment]
## Meeting Discussion

- Automation would be nice, open for implementation

**Comment by manuelmeister** [comment]
Maybe have a look at this: https://github.com/marketplace/renovate
