### ISSUE TITLE
InCoreRole

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#69]
Ich habe mir überlegt, ob es möglich ist, eine "InCoreRole" zu definieren, welche man nur erhält, wenn der ServiceNestingLevel > 0 ist. Von der Architektur wäre dies kein Problem... Vorallem, weil die Role-Liste immer neu gerechnet wird (wohl nicht so performant...)

Dies würde es ermöglichen, einzelne ServiceMethoden vor externem gebrauch zu schützen.
Ein Beispiel wäre die CreateMethode auf dem UserService. 
Diese darf nur vom RegisterService aufgerufen werden, jedoch nicht vom User selber; glaube ich.

Könntest du dir sowas vorstellen?

**Comment by usu** [comment]
Ja, finde ich eine gute Idee. So hätten wir das friend concept elegant
gelöst.

**Comment by pmattmann** [comment]
Entsprechender PullRequest ist online;
