### ISSUE TITLE
Autofocus immediately triggers vee-rules

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#694]
![Screenshot from 2020-11-23 19-51-01](https://user-images.githubusercontent.com/7566995/100002733-438c2f80-2dc5-11eb-8783-979cd555c799.png)

**Comment by DeNic0la** [comment]
I would like to try that after #675 is merged, could someone assign me?

**Comment by DeNic0la** [comment]
Is it possible this was solved in this commit? (https://github.com/ecamp/ecamp3/commit/9a13c3d5a518b88bf2312b246440329f99ecd9d4)
this line seems to do a good job:
https://github.com/ecamp/ecamp3/blob/ea02e802a393c5119d0288606434767b34a7d272/frontend/src/components/dialog/DialogForm.vue#L13
I don't understand the code completely but it seems to work fine:

https://user-images.githubusercontent.com/57986114/123449676-d0a19c00-d5d3-11eb-9faf-e8e972bec670.mp4

the vee-rules only trigger if the field lost focus.

**Comment by carlobeltrame** [comment]
It's entirely possible that this was solved "accidentally" in the meantime. Thanks for checking and reporting :) I will close this issue in that case.
