### ISSUE TITLE
Database Migrations

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#705]
How can we automate / organize database migrations?
When you checkout another branch / pull request or update the deployment by a pull request and the current structure is no longer valid / does not contain the correct setup data, it is annoying and makes it unnecessarily difficult to compare. For example, if a camp was created with older data, new activity content will not be made available.

**Comment by manuelmeister** [comment]
@pmattmann Command Line Befehl implementieren
@carlobeltrame updated deployment script

**Comment by carlobeltrame** [comment]
API Platform comes with a fully working migration system. To discuss: Do we want to actively deactivate this at the moment, or do we embrace the default system and start working with it?
