### ISSUE TITLE
Use GitHub Environments to protect the secrets of deployments

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#709]
https://docs.github.com/en/free-pro-team@latest/actions/reference/environments
Apparently it is now possible to create environments with dedicated secrets (still in beta). I might try this out and change this PR yet again...

_Originally posted by @carlobeltrame in https://github.com/ecamp/ecamp3/issues/704#issuecomment-748012469_

**Comment by BacLuc** [comment]
Können wir schliessen, oder?

**Comment by carlobeltrame** [comment]
Ja, fixed in #2353
