### ISSUE TITLE
Readonly Entities entfernen

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#71]
Ich habe die Hoffnung, einen geeigneten Weg gefunden zu haben, die Readonly Entities zu entfernen, ohne dabei die Vergleichbarkeit zu verlieren :)

Die UnitOfWork von Doctrine kann ein ChangeSet bestimmen. Dies umfasst alle Differenzen zwischen dem aktuellen Entity-Stand und der DB. Dieses ChangeSet muss beim betreten des ersten Services (ServiceNestingLevel = 0) leer sein!
Ist das nicht der Fall, so hat jemand die Entities ausserhalb des ServiceLayers angefasst und wir werfen eine FatalException.

Dieser Test ist (wahrscheinlich) relativ rechenintensiv... kann aber in der Produktiven Umgebung entfernt werden; Es reicht ja, wenn den Entwicklern auf die Finger gehauen wird, wenn sie die Entities ausserhalb vom ServiceLayer anfassen.

Den Check würde ich an folgender stelle machen:
Core/Service/ValidationWrapper::begin() - Nach dem zurückstellen der ValidationException
(https://github.com/ecamp/ecamp3/blob/devel/application/Core/Service/ValidationWrapper.php#L81)

Was meinst du?

**Comment by usu** [comment]
Finde ich gut. Bin auch über den ChangeSet gestolpert, und habe versucht, diesen beim Eintreten in eine Service rückgängig zu machen. Bin aber gescheitert, etwas tolles hinzubringen.

Deine Idee, einfach eine Exception zu werfen, finde ich gut, denn wenn sich die Entities ausserhalb des Services ändern, ist eh schon was schief gelaufen.

Werde dies so einbauen. Hab grad noch ein paar andere pending Changes, die ich grad zusammen commiten kann.

**Comment by pmattmann** [comment]
Hab die Konzepte In-Service-Role und Readonly-Entity ChangeSet zusammengeführt.
Der entsprechende PullRequest sollte gleich alle vorherigen PullRequests beinhalten.
