### ISSUE TITLE
Picasso <-> List  over  Menu

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#809]
Toggle Picasso <-> List-View wird vor dem Menu angezeigt...

<img width="249" alt="Bildschirmfoto 2021-01-07 um 18 43 47" src="https://user-images.githubusercontent.com/470237/103925879-73df2180-5118-11eb-96a9-8e1f9158e074.png">

**Comment by carlobeltrame** [comment]
Nicht mehr aktuell, taucht möglicherweise nach #2349 wieder auf.
