### ISSUE TITLE
PHP: Use PHP RFC: Return (PHP 7)

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#838]
Seit PHP 7 ist der [PHP RFC: Return Type Declarations](https://wiki.php.net/rfc/return_types) implementiert.
Code umbauen von 
```php
/**
 * @return ReturnType
 */
function foo() { ... }
```
auf
```php
function foo(): ReturnType { ... }
```

**Comment by BacLuc** [comment]
+1

**Comment by pmattmann** [comment]
To discuss:
Was ist der korrekte ReturnType von Controller-Actions?
V1) 🎉 Möglichst spezifisch
V2) 🚀 ViewModel
V3) 👀 Response

**Comment by pmattmann** [comment]
Methoden ohen Return-Value:
V1) 🎉 void vernweden
V2) 👀 nix verwenden

**Comment by manuelmeister** [comment]
## Meeting Discuss
- ReturnType für Controller Actions: ViewModel oder Ableitung davon
- Methoden ohne Return-Value: void
