### ISSUE TITLE
Setup Documentation

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#96]
- phpDoc for Sourcecode
- Wiki for PlainText

**Comment by pmattmann** [comment]
Ich habe mich mal ein bisschen umgesehen und folgendes entdeckt:
http://phpundercontrol.org/

phpUnderControl stellt viele interessante Feature zur Verfügung. Es muss jedoch auf einem Server installiert werden.
@usu: kannst du dir das mal ansehen... Könnten wir etwas in dieser Form unter dev.ecamp3.ch installieren??

**Comment by robin-morand** [comment]
Hi ! 
I'm scout in Waadt (Vaud) and i'm trying to setup a dev envrionnement, my goal is to see if ecamp3 is useable for our needs (for "Lager" planing and also for J+S formation mangement) and then eventually translating it in french and/or contributing to the developpment. 

Actually I'm here : 
   1) clone repo
   2) composer update && install 
   3) bower install
   4) ./vendor/doctrine/doctrine-module/bin/doctrine-module orm:schema-tool:create
   5) php -S 0.0.0.0:8080 -t public/ public/index.php
DB has been poplated, but I have some issue with bootstrap :

```
     GET http://localhost:8080/assets/vendor/bootstrap/dist/css/bootstrap.css [HTTP/1.1 404 Not Found 35ms]
     GET http://localhost:8080/assets/vendor/fontawesome/css/font-awesome.min.css [HTTP/1.1 404 Not Found 69ms]
```

What am I missing ?

**Comment by ghost** [comment]
use n IDE such as phpstorm.
I also have problems with setting up the project in the ide.but pirmin
mattmann will. help me via skype. if we find time.

you could join.or i will screen. cpture my pc while setting it up.

Then we have an updatr tutorial to updatr the setup docu.

greetings fron zurich

fabian eigenmann v/o pixel
Am 20.05.2015 10:27 schrieb "Robin Fave" notifications@github.com:

**Comment by robin-morand** [comment]
Hi guys ! I talk about ecamp with other pfadi in waadt and i found an other Guy intersted by translating ecamp to french so give us posted when you have news about setting up a dev env. ;-)
Greeting from Lausanne
Alaskan - Robin

**Comment by ghost** [comment]
need for sql table - forte /smiley

**Comment by robin-morand** [comment]
Hey guys !
Do you have any news about an eventual setup documentation ?

The current version is stable enough to use it for managing a cours or a camp ?
Greeting from Lausanne
Alaskan - Robin

**Comment by carlobeltrame** [comment]
Hi Alaskan
I found you can just rely on the framework to route your request to the index script. As far as I understand, manually specifying public/index.php forces all requests (also the ones for the javascript files) to be handled by index.php. Try simply:
php -S 0.0.0.0:8080 -t public/
Best,
Carlo v/o Cosinus

**Comment by piiixel** [comment]
@sulazix Don't you have some 404-errors when you use "php- S 127.0.0.1:8080 -t public/"
 haven't found a solution for the assets (those desfined in the asset_manager)
Have you got a solution @sulazix or maybe @pmattmann or @usu have.
