### ISSUE TITLE
Replace hardcoded entityUris in dialogs with templated links

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#977]
In files:
* [x] DialogMaterialItemCreate.vue -> /material-items
* [ ] DialogActivityCreate.vue -> /activities
* [ ] DialogCategoryCreate.vue -> /categories
* [ ] DialogMaterialListCreate.vue -> /material-items
* [ ] DialogPeriodCreate.vue -> /periods

The URIs can be retrieved from the API as follows: `this.api.href(this.api.get(), 'materialItems').then(uri => { this.entityUri = uri })`.
If the root api endpoint does not have some of them already, they can be added in the method `apiAction()` in IndexController.php.

**Comment by feigenmann** [comment]
would takle this

**Comment by carlobeltrame** [comment]
Go for it

**Comment by carlobeltrame** [comment]
This ticket needs to be re-specified once we are up and running with API Platform. Right now the description is out of date.

**Comment by carlobeltrame** [comment]
In the meantime, the API is fully-featured again, and this issue can be implemented, based on the issue description.
